// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: substrait/expression.proto

package io.substrait.proto;

/**
 * Protobuf enum {@code substrait.AggregationPhase}
 */
public enum AggregationPhase
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>AGGREGATION_PHASE_UNSPECIFIED = 0;</code>
   */
  AGGREGATION_PHASE_UNSPECIFIED(0),
  /**
   * <code>AGGREGATION_PHASE_INITIAL_TO_INTERMEDIATE = 1;</code>
   */
  AGGREGATION_PHASE_INITIAL_TO_INTERMEDIATE(1),
  /**
   * <code>AGGREGATION_PHASE_INTERMEDIATE_TO_INTERMEDIATE = 2;</code>
   */
  AGGREGATION_PHASE_INTERMEDIATE_TO_INTERMEDIATE(2),
  /**
   * <code>AGGREGATION_PHASE_INITIAL_TO_RESULT = 3;</code>
   */
  AGGREGATION_PHASE_INITIAL_TO_RESULT(3),
  /**
   * <code>AGGREGATION_PHASE_INTERMEDIATE_TO_RESULT = 4;</code>
   */
  AGGREGATION_PHASE_INTERMEDIATE_TO_RESULT(4),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>AGGREGATION_PHASE_UNSPECIFIED = 0;</code>
   */
  public static final int AGGREGATION_PHASE_UNSPECIFIED_VALUE = 0;
  /**
   * <code>AGGREGATION_PHASE_INITIAL_TO_INTERMEDIATE = 1;</code>
   */
  public static final int AGGREGATION_PHASE_INITIAL_TO_INTERMEDIATE_VALUE = 1;
  /**
   * <code>AGGREGATION_PHASE_INTERMEDIATE_TO_INTERMEDIATE = 2;</code>
   */
  public static final int AGGREGATION_PHASE_INTERMEDIATE_TO_INTERMEDIATE_VALUE = 2;
  /**
   * <code>AGGREGATION_PHASE_INITIAL_TO_RESULT = 3;</code>
   */
  public static final int AGGREGATION_PHASE_INITIAL_TO_RESULT_VALUE = 3;
  /**
   * <code>AGGREGATION_PHASE_INTERMEDIATE_TO_RESULT = 4;</code>
   */
  public static final int AGGREGATION_PHASE_INTERMEDIATE_TO_RESULT_VALUE = 4;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static AggregationPhase valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static AggregationPhase forNumber(int value) {
    switch (value) {
      case 0: return AGGREGATION_PHASE_UNSPECIFIED;
      case 1: return AGGREGATION_PHASE_INITIAL_TO_INTERMEDIATE;
      case 2: return AGGREGATION_PHASE_INTERMEDIATE_TO_INTERMEDIATE;
      case 3: return AGGREGATION_PHASE_INITIAL_TO_RESULT;
      case 4: return AGGREGATION_PHASE_INTERMEDIATE_TO_RESULT;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<AggregationPhase>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      AggregationPhase> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<AggregationPhase>() {
          public AggregationPhase findValueByNumber(int number) {
            return AggregationPhase.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return io.substrait.proto.ExpressionOuterClass.getDescriptor().getEnumTypes().get(0);
  }

  private static final AggregationPhase[] VALUES = values();

  public static AggregationPhase valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private AggregationPhase(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:substrait.AggregationPhase)
}

