// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: substrait/capabilities.proto

package io.substrait.proto;

/**
 * <pre>
 * Defines a set of Capabilities that a system (producer or consumer) supports.
 * </pre>
 *
 * Protobuf type {@code substrait.Capabilities}
 */
public final class Capabilities extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:substrait.Capabilities)
    CapabilitiesOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Capabilities.newBuilder() to construct.
  private Capabilities(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Capabilities() {
    substraitVersions_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    advancedExtensionTypeUrls_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    simpleExtensions_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Capabilities();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Capabilities(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              substraitVersions_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            substraitVersions_.add(s);
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              advancedExtensionTypeUrls_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000002;
            }
            advancedExtensionTypeUrls_.add(s);
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000004) != 0)) {
              simpleExtensions_ = new java.util.ArrayList<io.substrait.proto.Capabilities.SimpleExtension>();
              mutable_bitField0_ |= 0x00000004;
            }
            simpleExtensions_.add(
                input.readMessage(io.substrait.proto.Capabilities.SimpleExtension.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        substraitVersions_ = substraitVersions_.getUnmodifiableView();
      }
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        advancedExtensionTypeUrls_ = advancedExtensionTypeUrls_.getUnmodifiableView();
      }
      if (((mutable_bitField0_ & 0x00000004) != 0)) {
        simpleExtensions_ = java.util.Collections.unmodifiableList(simpleExtensions_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.substrait.proto.CapabilitiesOuterClass.internal_static_substrait_Capabilities_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.substrait.proto.CapabilitiesOuterClass.internal_static_substrait_Capabilities_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.substrait.proto.Capabilities.class, io.substrait.proto.Capabilities.Builder.class);
  }

  public interface SimpleExtensionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:substrait.Capabilities.SimpleExtension)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string uri = 1;</code>
     * @return The uri.
     */
    java.lang.String getUri();
    /**
     * <code>string uri = 1;</code>
     * @return The bytes for uri.
     */
    com.google.protobuf.ByteString
        getUriBytes();

    /**
     * <code>repeated string function_keys = 2;</code>
     * @return A list containing the functionKeys.
     */
    java.util.List<java.lang.String>
        getFunctionKeysList();
    /**
     * <code>repeated string function_keys = 2;</code>
     * @return The count of functionKeys.
     */
    int getFunctionKeysCount();
    /**
     * <code>repeated string function_keys = 2;</code>
     * @param index The index of the element to return.
     * @return The functionKeys at the given index.
     */
    java.lang.String getFunctionKeys(int index);
    /**
     * <code>repeated string function_keys = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the functionKeys at the given index.
     */
    com.google.protobuf.ByteString
        getFunctionKeysBytes(int index);

    /**
     * <code>repeated string type_keys = 3;</code>
     * @return A list containing the typeKeys.
     */
    java.util.List<java.lang.String>
        getTypeKeysList();
    /**
     * <code>repeated string type_keys = 3;</code>
     * @return The count of typeKeys.
     */
    int getTypeKeysCount();
    /**
     * <code>repeated string type_keys = 3;</code>
     * @param index The index of the element to return.
     * @return The typeKeys at the given index.
     */
    java.lang.String getTypeKeys(int index);
    /**
     * <code>repeated string type_keys = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the typeKeys at the given index.
     */
    com.google.protobuf.ByteString
        getTypeKeysBytes(int index);

    /**
     * <code>repeated string type_variation_keys = 4;</code>
     * @return A list containing the typeVariationKeys.
     */
    java.util.List<java.lang.String>
        getTypeVariationKeysList();
    /**
     * <code>repeated string type_variation_keys = 4;</code>
     * @return The count of typeVariationKeys.
     */
    int getTypeVariationKeysCount();
    /**
     * <code>repeated string type_variation_keys = 4;</code>
     * @param index The index of the element to return.
     * @return The typeVariationKeys at the given index.
     */
    java.lang.String getTypeVariationKeys(int index);
    /**
     * <code>repeated string type_variation_keys = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the typeVariationKeys at the given index.
     */
    com.google.protobuf.ByteString
        getTypeVariationKeysBytes(int index);
  }
  /**
   * Protobuf type {@code substrait.Capabilities.SimpleExtension}
   */
  public static final class SimpleExtension extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:substrait.Capabilities.SimpleExtension)
      SimpleExtensionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SimpleExtension.newBuilder() to construct.
    private SimpleExtension(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SimpleExtension() {
      uri_ = "";
      functionKeys_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      typeKeys_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      typeVariationKeys_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SimpleExtension();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SimpleExtension(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              uri_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                functionKeys_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              functionKeys_.add(s);
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                typeKeys_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              typeKeys_.add(s);
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000004) != 0)) {
                typeVariationKeys_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              typeVariationKeys_.add(s);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          functionKeys_ = functionKeys_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000002) != 0)) {
          typeKeys_ = typeKeys_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000004) != 0)) {
          typeVariationKeys_ = typeVariationKeys_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.substrait.proto.CapabilitiesOuterClass.internal_static_substrait_Capabilities_SimpleExtension_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.substrait.proto.CapabilitiesOuterClass.internal_static_substrait_Capabilities_SimpleExtension_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.substrait.proto.Capabilities.SimpleExtension.class, io.substrait.proto.Capabilities.SimpleExtension.Builder.class);
    }

    public static final int URI_FIELD_NUMBER = 1;
    private volatile java.lang.Object uri_;
    /**
     * <code>string uri = 1;</code>
     * @return The uri.
     */
    @java.lang.Override
    public java.lang.String getUri() {
      java.lang.Object ref = uri_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uri_ = s;
        return s;
      }
    }
    /**
     * <code>string uri = 1;</code>
     * @return The bytes for uri.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUriBytes() {
      java.lang.Object ref = uri_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uri_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FUNCTION_KEYS_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList functionKeys_;
    /**
     * <code>repeated string function_keys = 2;</code>
     * @return A list containing the functionKeys.
     */
    public com.google.protobuf.ProtocolStringList
        getFunctionKeysList() {
      return functionKeys_;
    }
    /**
     * <code>repeated string function_keys = 2;</code>
     * @return The count of functionKeys.
     */
    public int getFunctionKeysCount() {
      return functionKeys_.size();
    }
    /**
     * <code>repeated string function_keys = 2;</code>
     * @param index The index of the element to return.
     * @return The functionKeys at the given index.
     */
    public java.lang.String getFunctionKeys(int index) {
      return functionKeys_.get(index);
    }
    /**
     * <code>repeated string function_keys = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the functionKeys at the given index.
     */
    public com.google.protobuf.ByteString
        getFunctionKeysBytes(int index) {
      return functionKeys_.getByteString(index);
    }

    public static final int TYPE_KEYS_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList typeKeys_;
    /**
     * <code>repeated string type_keys = 3;</code>
     * @return A list containing the typeKeys.
     */
    public com.google.protobuf.ProtocolStringList
        getTypeKeysList() {
      return typeKeys_;
    }
    /**
     * <code>repeated string type_keys = 3;</code>
     * @return The count of typeKeys.
     */
    public int getTypeKeysCount() {
      return typeKeys_.size();
    }
    /**
     * <code>repeated string type_keys = 3;</code>
     * @param index The index of the element to return.
     * @return The typeKeys at the given index.
     */
    public java.lang.String getTypeKeys(int index) {
      return typeKeys_.get(index);
    }
    /**
     * <code>repeated string type_keys = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the typeKeys at the given index.
     */
    public com.google.protobuf.ByteString
        getTypeKeysBytes(int index) {
      return typeKeys_.getByteString(index);
    }

    public static final int TYPE_VARIATION_KEYS_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList typeVariationKeys_;
    /**
     * <code>repeated string type_variation_keys = 4;</code>
     * @return A list containing the typeVariationKeys.
     */
    public com.google.protobuf.ProtocolStringList
        getTypeVariationKeysList() {
      return typeVariationKeys_;
    }
    /**
     * <code>repeated string type_variation_keys = 4;</code>
     * @return The count of typeVariationKeys.
     */
    public int getTypeVariationKeysCount() {
      return typeVariationKeys_.size();
    }
    /**
     * <code>repeated string type_variation_keys = 4;</code>
     * @param index The index of the element to return.
     * @return The typeVariationKeys at the given index.
     */
    public java.lang.String getTypeVariationKeys(int index) {
      return typeVariationKeys_.get(index);
    }
    /**
     * <code>repeated string type_variation_keys = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the typeVariationKeys at the given index.
     */
    public com.google.protobuf.ByteString
        getTypeVariationKeysBytes(int index) {
      return typeVariationKeys_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getUriBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, uri_);
      }
      for (int i = 0; i < functionKeys_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, functionKeys_.getRaw(i));
      }
      for (int i = 0; i < typeKeys_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, typeKeys_.getRaw(i));
      }
      for (int i = 0; i < typeVariationKeys_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, typeVariationKeys_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUriBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, uri_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < functionKeys_.size(); i++) {
          dataSize += computeStringSizeNoTag(functionKeys_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getFunctionKeysList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < typeKeys_.size(); i++) {
          dataSize += computeStringSizeNoTag(typeKeys_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getTypeKeysList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < typeVariationKeys_.size(); i++) {
          dataSize += computeStringSizeNoTag(typeVariationKeys_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getTypeVariationKeysList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.substrait.proto.Capabilities.SimpleExtension)) {
        return super.equals(obj);
      }
      io.substrait.proto.Capabilities.SimpleExtension other = (io.substrait.proto.Capabilities.SimpleExtension) obj;

      if (!getUri()
          .equals(other.getUri())) return false;
      if (!getFunctionKeysList()
          .equals(other.getFunctionKeysList())) return false;
      if (!getTypeKeysList()
          .equals(other.getTypeKeysList())) return false;
      if (!getTypeVariationKeysList()
          .equals(other.getTypeVariationKeysList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + URI_FIELD_NUMBER;
      hash = (53 * hash) + getUri().hashCode();
      if (getFunctionKeysCount() > 0) {
        hash = (37 * hash) + FUNCTION_KEYS_FIELD_NUMBER;
        hash = (53 * hash) + getFunctionKeysList().hashCode();
      }
      if (getTypeKeysCount() > 0) {
        hash = (37 * hash) + TYPE_KEYS_FIELD_NUMBER;
        hash = (53 * hash) + getTypeKeysList().hashCode();
      }
      if (getTypeVariationKeysCount() > 0) {
        hash = (37 * hash) + TYPE_VARIATION_KEYS_FIELD_NUMBER;
        hash = (53 * hash) + getTypeVariationKeysList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.substrait.proto.Capabilities.SimpleExtension parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.substrait.proto.Capabilities.SimpleExtension parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.substrait.proto.Capabilities.SimpleExtension parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.substrait.proto.Capabilities.SimpleExtension parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.substrait.proto.Capabilities.SimpleExtension parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.substrait.proto.Capabilities.SimpleExtension parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.substrait.proto.Capabilities.SimpleExtension parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.substrait.proto.Capabilities.SimpleExtension parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.substrait.proto.Capabilities.SimpleExtension parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.substrait.proto.Capabilities.SimpleExtension parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.substrait.proto.Capabilities.SimpleExtension parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.substrait.proto.Capabilities.SimpleExtension parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.substrait.proto.Capabilities.SimpleExtension prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code substrait.Capabilities.SimpleExtension}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:substrait.Capabilities.SimpleExtension)
        io.substrait.proto.Capabilities.SimpleExtensionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.substrait.proto.CapabilitiesOuterClass.internal_static_substrait_Capabilities_SimpleExtension_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.substrait.proto.CapabilitiesOuterClass.internal_static_substrait_Capabilities_SimpleExtension_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.substrait.proto.Capabilities.SimpleExtension.class, io.substrait.proto.Capabilities.SimpleExtension.Builder.class);
      }

      // Construct using io.substrait.proto.Capabilities.SimpleExtension.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        uri_ = "";

        functionKeys_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        typeKeys_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        typeVariationKeys_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.substrait.proto.CapabilitiesOuterClass.internal_static_substrait_Capabilities_SimpleExtension_descriptor;
      }

      @java.lang.Override
      public io.substrait.proto.Capabilities.SimpleExtension getDefaultInstanceForType() {
        return io.substrait.proto.Capabilities.SimpleExtension.getDefaultInstance();
      }

      @java.lang.Override
      public io.substrait.proto.Capabilities.SimpleExtension build() {
        io.substrait.proto.Capabilities.SimpleExtension result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.substrait.proto.Capabilities.SimpleExtension buildPartial() {
        io.substrait.proto.Capabilities.SimpleExtension result = new io.substrait.proto.Capabilities.SimpleExtension(this);
        int from_bitField0_ = bitField0_;
        result.uri_ = uri_;
        if (((bitField0_ & 0x00000001) != 0)) {
          functionKeys_ = functionKeys_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.functionKeys_ = functionKeys_;
        if (((bitField0_ & 0x00000002) != 0)) {
          typeKeys_ = typeKeys_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.typeKeys_ = typeKeys_;
        if (((bitField0_ & 0x00000004) != 0)) {
          typeVariationKeys_ = typeVariationKeys_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.typeVariationKeys_ = typeVariationKeys_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.substrait.proto.Capabilities.SimpleExtension) {
          return mergeFrom((io.substrait.proto.Capabilities.SimpleExtension)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.substrait.proto.Capabilities.SimpleExtension other) {
        if (other == io.substrait.proto.Capabilities.SimpleExtension.getDefaultInstance()) return this;
        if (!other.getUri().isEmpty()) {
          uri_ = other.uri_;
          onChanged();
        }
        if (!other.functionKeys_.isEmpty()) {
          if (functionKeys_.isEmpty()) {
            functionKeys_ = other.functionKeys_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureFunctionKeysIsMutable();
            functionKeys_.addAll(other.functionKeys_);
          }
          onChanged();
        }
        if (!other.typeKeys_.isEmpty()) {
          if (typeKeys_.isEmpty()) {
            typeKeys_ = other.typeKeys_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureTypeKeysIsMutable();
            typeKeys_.addAll(other.typeKeys_);
          }
          onChanged();
        }
        if (!other.typeVariationKeys_.isEmpty()) {
          if (typeVariationKeys_.isEmpty()) {
            typeVariationKeys_ = other.typeVariationKeys_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureTypeVariationKeysIsMutable();
            typeVariationKeys_.addAll(other.typeVariationKeys_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.substrait.proto.Capabilities.SimpleExtension parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.substrait.proto.Capabilities.SimpleExtension) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object uri_ = "";
      /**
       * <code>string uri = 1;</code>
       * @return The uri.
       */
      public java.lang.String getUri() {
        java.lang.Object ref = uri_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          uri_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string uri = 1;</code>
       * @return The bytes for uri.
       */
      public com.google.protobuf.ByteString
          getUriBytes() {
        java.lang.Object ref = uri_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uri_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string uri = 1;</code>
       * @param value The uri to set.
       * @return This builder for chaining.
       */
      public Builder setUri(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        uri_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string uri = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUri() {
        
        uri_ = getDefaultInstance().getUri();
        onChanged();
        return this;
      }
      /**
       * <code>string uri = 1;</code>
       * @param value The bytes for uri to set.
       * @return This builder for chaining.
       */
      public Builder setUriBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        uri_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList functionKeys_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureFunctionKeysIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          functionKeys_ = new com.google.protobuf.LazyStringArrayList(functionKeys_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string function_keys = 2;</code>
       * @return A list containing the functionKeys.
       */
      public com.google.protobuf.ProtocolStringList
          getFunctionKeysList() {
        return functionKeys_.getUnmodifiableView();
      }
      /**
       * <code>repeated string function_keys = 2;</code>
       * @return The count of functionKeys.
       */
      public int getFunctionKeysCount() {
        return functionKeys_.size();
      }
      /**
       * <code>repeated string function_keys = 2;</code>
       * @param index The index of the element to return.
       * @return The functionKeys at the given index.
       */
      public java.lang.String getFunctionKeys(int index) {
        return functionKeys_.get(index);
      }
      /**
       * <code>repeated string function_keys = 2;</code>
       * @param index The index of the value to return.
       * @return The bytes of the functionKeys at the given index.
       */
      public com.google.protobuf.ByteString
          getFunctionKeysBytes(int index) {
        return functionKeys_.getByteString(index);
      }
      /**
       * <code>repeated string function_keys = 2;</code>
       * @param index The index to set the value at.
       * @param value The functionKeys to set.
       * @return This builder for chaining.
       */
      public Builder setFunctionKeys(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFunctionKeysIsMutable();
        functionKeys_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string function_keys = 2;</code>
       * @param value The functionKeys to add.
       * @return This builder for chaining.
       */
      public Builder addFunctionKeys(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFunctionKeysIsMutable();
        functionKeys_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string function_keys = 2;</code>
       * @param values The functionKeys to add.
       * @return This builder for chaining.
       */
      public Builder addAllFunctionKeys(
          java.lang.Iterable<java.lang.String> values) {
        ensureFunctionKeysIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, functionKeys_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string function_keys = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearFunctionKeys() {
        functionKeys_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string function_keys = 2;</code>
       * @param value The bytes of the functionKeys to add.
       * @return This builder for chaining.
       */
      public Builder addFunctionKeysBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureFunctionKeysIsMutable();
        functionKeys_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList typeKeys_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureTypeKeysIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          typeKeys_ = new com.google.protobuf.LazyStringArrayList(typeKeys_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated string type_keys = 3;</code>
       * @return A list containing the typeKeys.
       */
      public com.google.protobuf.ProtocolStringList
          getTypeKeysList() {
        return typeKeys_.getUnmodifiableView();
      }
      /**
       * <code>repeated string type_keys = 3;</code>
       * @return The count of typeKeys.
       */
      public int getTypeKeysCount() {
        return typeKeys_.size();
      }
      /**
       * <code>repeated string type_keys = 3;</code>
       * @param index The index of the element to return.
       * @return The typeKeys at the given index.
       */
      public java.lang.String getTypeKeys(int index) {
        return typeKeys_.get(index);
      }
      /**
       * <code>repeated string type_keys = 3;</code>
       * @param index The index of the value to return.
       * @return The bytes of the typeKeys at the given index.
       */
      public com.google.protobuf.ByteString
          getTypeKeysBytes(int index) {
        return typeKeys_.getByteString(index);
      }
      /**
       * <code>repeated string type_keys = 3;</code>
       * @param index The index to set the value at.
       * @param value The typeKeys to set.
       * @return This builder for chaining.
       */
      public Builder setTypeKeys(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTypeKeysIsMutable();
        typeKeys_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string type_keys = 3;</code>
       * @param value The typeKeys to add.
       * @return This builder for chaining.
       */
      public Builder addTypeKeys(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTypeKeysIsMutable();
        typeKeys_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string type_keys = 3;</code>
       * @param values The typeKeys to add.
       * @return This builder for chaining.
       */
      public Builder addAllTypeKeys(
          java.lang.Iterable<java.lang.String> values) {
        ensureTypeKeysIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, typeKeys_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string type_keys = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTypeKeys() {
        typeKeys_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string type_keys = 3;</code>
       * @param value The bytes of the typeKeys to add.
       * @return This builder for chaining.
       */
      public Builder addTypeKeysBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureTypeKeysIsMutable();
        typeKeys_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList typeVariationKeys_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureTypeVariationKeysIsMutable() {
        if (!((bitField0_ & 0x00000004) != 0)) {
          typeVariationKeys_ = new com.google.protobuf.LazyStringArrayList(typeVariationKeys_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated string type_variation_keys = 4;</code>
       * @return A list containing the typeVariationKeys.
       */
      public com.google.protobuf.ProtocolStringList
          getTypeVariationKeysList() {
        return typeVariationKeys_.getUnmodifiableView();
      }
      /**
       * <code>repeated string type_variation_keys = 4;</code>
       * @return The count of typeVariationKeys.
       */
      public int getTypeVariationKeysCount() {
        return typeVariationKeys_.size();
      }
      /**
       * <code>repeated string type_variation_keys = 4;</code>
       * @param index The index of the element to return.
       * @return The typeVariationKeys at the given index.
       */
      public java.lang.String getTypeVariationKeys(int index) {
        return typeVariationKeys_.get(index);
      }
      /**
       * <code>repeated string type_variation_keys = 4;</code>
       * @param index The index of the value to return.
       * @return The bytes of the typeVariationKeys at the given index.
       */
      public com.google.protobuf.ByteString
          getTypeVariationKeysBytes(int index) {
        return typeVariationKeys_.getByteString(index);
      }
      /**
       * <code>repeated string type_variation_keys = 4;</code>
       * @param index The index to set the value at.
       * @param value The typeVariationKeys to set.
       * @return This builder for chaining.
       */
      public Builder setTypeVariationKeys(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTypeVariationKeysIsMutable();
        typeVariationKeys_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string type_variation_keys = 4;</code>
       * @param value The typeVariationKeys to add.
       * @return This builder for chaining.
       */
      public Builder addTypeVariationKeys(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTypeVariationKeysIsMutable();
        typeVariationKeys_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string type_variation_keys = 4;</code>
       * @param values The typeVariationKeys to add.
       * @return This builder for chaining.
       */
      public Builder addAllTypeVariationKeys(
          java.lang.Iterable<java.lang.String> values) {
        ensureTypeVariationKeysIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, typeVariationKeys_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string type_variation_keys = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearTypeVariationKeys() {
        typeVariationKeys_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string type_variation_keys = 4;</code>
       * @param value The bytes of the typeVariationKeys to add.
       * @return This builder for chaining.
       */
      public Builder addTypeVariationKeysBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureTypeVariationKeysIsMutable();
        typeVariationKeys_.add(value);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:substrait.Capabilities.SimpleExtension)
    }

    // @@protoc_insertion_point(class_scope:substrait.Capabilities.SimpleExtension)
    private static final io.substrait.proto.Capabilities.SimpleExtension DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.substrait.proto.Capabilities.SimpleExtension();
    }

    public static io.substrait.proto.Capabilities.SimpleExtension getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SimpleExtension>
        PARSER = new com.google.protobuf.AbstractParser<SimpleExtension>() {
      @java.lang.Override
      public SimpleExtension parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SimpleExtension(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SimpleExtension> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SimpleExtension> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.substrait.proto.Capabilities.SimpleExtension getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int SUBSTRAIT_VERSIONS_FIELD_NUMBER = 1;
  private com.google.protobuf.LazyStringList substraitVersions_;
  /**
   * <pre>
   * List of Substrait versions this system supports
   * </pre>
   *
   * <code>repeated string substrait_versions = 1;</code>
   * @return A list containing the substraitVersions.
   */
  public com.google.protobuf.ProtocolStringList
      getSubstraitVersionsList() {
    return substraitVersions_;
  }
  /**
   * <pre>
   * List of Substrait versions this system supports
   * </pre>
   *
   * <code>repeated string substrait_versions = 1;</code>
   * @return The count of substraitVersions.
   */
  public int getSubstraitVersionsCount() {
    return substraitVersions_.size();
  }
  /**
   * <pre>
   * List of Substrait versions this system supports
   * </pre>
   *
   * <code>repeated string substrait_versions = 1;</code>
   * @param index The index of the element to return.
   * @return The substraitVersions at the given index.
   */
  public java.lang.String getSubstraitVersions(int index) {
    return substraitVersions_.get(index);
  }
  /**
   * <pre>
   * List of Substrait versions this system supports
   * </pre>
   *
   * <code>repeated string substrait_versions = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the substraitVersions at the given index.
   */
  public com.google.protobuf.ByteString
      getSubstraitVersionsBytes(int index) {
    return substraitVersions_.getByteString(index);
  }

  public static final int ADVANCED_EXTENSION_TYPE_URLS_FIELD_NUMBER = 2;
  private com.google.protobuf.LazyStringList advancedExtensionTypeUrls_;
  /**
   * <pre>
   * list of com.google.Any message types this system supports for advanced
   * extensions.
   * </pre>
   *
   * <code>repeated string advanced_extension_type_urls = 2;</code>
   * @return A list containing the advancedExtensionTypeUrls.
   */
  public com.google.protobuf.ProtocolStringList
      getAdvancedExtensionTypeUrlsList() {
    return advancedExtensionTypeUrls_;
  }
  /**
   * <pre>
   * list of com.google.Any message types this system supports for advanced
   * extensions.
   * </pre>
   *
   * <code>repeated string advanced_extension_type_urls = 2;</code>
   * @return The count of advancedExtensionTypeUrls.
   */
  public int getAdvancedExtensionTypeUrlsCount() {
    return advancedExtensionTypeUrls_.size();
  }
  /**
   * <pre>
   * list of com.google.Any message types this system supports for advanced
   * extensions.
   * </pre>
   *
   * <code>repeated string advanced_extension_type_urls = 2;</code>
   * @param index The index of the element to return.
   * @return The advancedExtensionTypeUrls at the given index.
   */
  public java.lang.String getAdvancedExtensionTypeUrls(int index) {
    return advancedExtensionTypeUrls_.get(index);
  }
  /**
   * <pre>
   * list of com.google.Any message types this system supports for advanced
   * extensions.
   * </pre>
   *
   * <code>repeated string advanced_extension_type_urls = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the advancedExtensionTypeUrls at the given index.
   */
  public com.google.protobuf.ByteString
      getAdvancedExtensionTypeUrlsBytes(int index) {
    return advancedExtensionTypeUrls_.getByteString(index);
  }

  public static final int SIMPLE_EXTENSIONS_FIELD_NUMBER = 3;
  private java.util.List<io.substrait.proto.Capabilities.SimpleExtension> simpleExtensions_;
  /**
   * <pre>
   * list of simple extensions this system supports.
   * </pre>
   *
   * <code>repeated .substrait.Capabilities.SimpleExtension simple_extensions = 3;</code>
   */
  @java.lang.Override
  public java.util.List<io.substrait.proto.Capabilities.SimpleExtension> getSimpleExtensionsList() {
    return simpleExtensions_;
  }
  /**
   * <pre>
   * list of simple extensions this system supports.
   * </pre>
   *
   * <code>repeated .substrait.Capabilities.SimpleExtension simple_extensions = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends io.substrait.proto.Capabilities.SimpleExtensionOrBuilder> 
      getSimpleExtensionsOrBuilderList() {
    return simpleExtensions_;
  }
  /**
   * <pre>
   * list of simple extensions this system supports.
   * </pre>
   *
   * <code>repeated .substrait.Capabilities.SimpleExtension simple_extensions = 3;</code>
   */
  @java.lang.Override
  public int getSimpleExtensionsCount() {
    return simpleExtensions_.size();
  }
  /**
   * <pre>
   * list of simple extensions this system supports.
   * </pre>
   *
   * <code>repeated .substrait.Capabilities.SimpleExtension simple_extensions = 3;</code>
   */
  @java.lang.Override
  public io.substrait.proto.Capabilities.SimpleExtension getSimpleExtensions(int index) {
    return simpleExtensions_.get(index);
  }
  /**
   * <pre>
   * list of simple extensions this system supports.
   * </pre>
   *
   * <code>repeated .substrait.Capabilities.SimpleExtension simple_extensions = 3;</code>
   */
  @java.lang.Override
  public io.substrait.proto.Capabilities.SimpleExtensionOrBuilder getSimpleExtensionsOrBuilder(
      int index) {
    return simpleExtensions_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < substraitVersions_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, substraitVersions_.getRaw(i));
    }
    for (int i = 0; i < advancedExtensionTypeUrls_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, advancedExtensionTypeUrls_.getRaw(i));
    }
    for (int i = 0; i < simpleExtensions_.size(); i++) {
      output.writeMessage(3, simpleExtensions_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < substraitVersions_.size(); i++) {
        dataSize += computeStringSizeNoTag(substraitVersions_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getSubstraitVersionsList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < advancedExtensionTypeUrls_.size(); i++) {
        dataSize += computeStringSizeNoTag(advancedExtensionTypeUrls_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getAdvancedExtensionTypeUrlsList().size();
    }
    for (int i = 0; i < simpleExtensions_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, simpleExtensions_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.substrait.proto.Capabilities)) {
      return super.equals(obj);
    }
    io.substrait.proto.Capabilities other = (io.substrait.proto.Capabilities) obj;

    if (!getSubstraitVersionsList()
        .equals(other.getSubstraitVersionsList())) return false;
    if (!getAdvancedExtensionTypeUrlsList()
        .equals(other.getAdvancedExtensionTypeUrlsList())) return false;
    if (!getSimpleExtensionsList()
        .equals(other.getSimpleExtensionsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getSubstraitVersionsCount() > 0) {
      hash = (37 * hash) + SUBSTRAIT_VERSIONS_FIELD_NUMBER;
      hash = (53 * hash) + getSubstraitVersionsList().hashCode();
    }
    if (getAdvancedExtensionTypeUrlsCount() > 0) {
      hash = (37 * hash) + ADVANCED_EXTENSION_TYPE_URLS_FIELD_NUMBER;
      hash = (53 * hash) + getAdvancedExtensionTypeUrlsList().hashCode();
    }
    if (getSimpleExtensionsCount() > 0) {
      hash = (37 * hash) + SIMPLE_EXTENSIONS_FIELD_NUMBER;
      hash = (53 * hash) + getSimpleExtensionsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.substrait.proto.Capabilities parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.substrait.proto.Capabilities parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.substrait.proto.Capabilities parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.substrait.proto.Capabilities parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.substrait.proto.Capabilities parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.substrait.proto.Capabilities parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.substrait.proto.Capabilities parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.substrait.proto.Capabilities parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.substrait.proto.Capabilities parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.substrait.proto.Capabilities parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.substrait.proto.Capabilities parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.substrait.proto.Capabilities parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.substrait.proto.Capabilities prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Defines a set of Capabilities that a system (producer or consumer) supports.
   * </pre>
   *
   * Protobuf type {@code substrait.Capabilities}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:substrait.Capabilities)
      io.substrait.proto.CapabilitiesOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.substrait.proto.CapabilitiesOuterClass.internal_static_substrait_Capabilities_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.substrait.proto.CapabilitiesOuterClass.internal_static_substrait_Capabilities_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.substrait.proto.Capabilities.class, io.substrait.proto.Capabilities.Builder.class);
    }

    // Construct using io.substrait.proto.Capabilities.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getSimpleExtensionsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      substraitVersions_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      advancedExtensionTypeUrls_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      if (simpleExtensionsBuilder_ == null) {
        simpleExtensions_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
      } else {
        simpleExtensionsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.substrait.proto.CapabilitiesOuterClass.internal_static_substrait_Capabilities_descriptor;
    }

    @java.lang.Override
    public io.substrait.proto.Capabilities getDefaultInstanceForType() {
      return io.substrait.proto.Capabilities.getDefaultInstance();
    }

    @java.lang.Override
    public io.substrait.proto.Capabilities build() {
      io.substrait.proto.Capabilities result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.substrait.proto.Capabilities buildPartial() {
      io.substrait.proto.Capabilities result = new io.substrait.proto.Capabilities(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) != 0)) {
        substraitVersions_ = substraitVersions_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.substraitVersions_ = substraitVersions_;
      if (((bitField0_ & 0x00000002) != 0)) {
        advancedExtensionTypeUrls_ = advancedExtensionTypeUrls_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.advancedExtensionTypeUrls_ = advancedExtensionTypeUrls_;
      if (simpleExtensionsBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          simpleExtensions_ = java.util.Collections.unmodifiableList(simpleExtensions_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.simpleExtensions_ = simpleExtensions_;
      } else {
        result.simpleExtensions_ = simpleExtensionsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.substrait.proto.Capabilities) {
        return mergeFrom((io.substrait.proto.Capabilities)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.substrait.proto.Capabilities other) {
      if (other == io.substrait.proto.Capabilities.getDefaultInstance()) return this;
      if (!other.substraitVersions_.isEmpty()) {
        if (substraitVersions_.isEmpty()) {
          substraitVersions_ = other.substraitVersions_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureSubstraitVersionsIsMutable();
          substraitVersions_.addAll(other.substraitVersions_);
        }
        onChanged();
      }
      if (!other.advancedExtensionTypeUrls_.isEmpty()) {
        if (advancedExtensionTypeUrls_.isEmpty()) {
          advancedExtensionTypeUrls_ = other.advancedExtensionTypeUrls_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureAdvancedExtensionTypeUrlsIsMutable();
          advancedExtensionTypeUrls_.addAll(other.advancedExtensionTypeUrls_);
        }
        onChanged();
      }
      if (simpleExtensionsBuilder_ == null) {
        if (!other.simpleExtensions_.isEmpty()) {
          if (simpleExtensions_.isEmpty()) {
            simpleExtensions_ = other.simpleExtensions_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureSimpleExtensionsIsMutable();
            simpleExtensions_.addAll(other.simpleExtensions_);
          }
          onChanged();
        }
      } else {
        if (!other.simpleExtensions_.isEmpty()) {
          if (simpleExtensionsBuilder_.isEmpty()) {
            simpleExtensionsBuilder_.dispose();
            simpleExtensionsBuilder_ = null;
            simpleExtensions_ = other.simpleExtensions_;
            bitField0_ = (bitField0_ & ~0x00000004);
            simpleExtensionsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getSimpleExtensionsFieldBuilder() : null;
          } else {
            simpleExtensionsBuilder_.addAllMessages(other.simpleExtensions_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.substrait.proto.Capabilities parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.substrait.proto.Capabilities) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringList substraitVersions_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureSubstraitVersionsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        substraitVersions_ = new com.google.protobuf.LazyStringArrayList(substraitVersions_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <pre>
     * List of Substrait versions this system supports
     * </pre>
     *
     * <code>repeated string substrait_versions = 1;</code>
     * @return A list containing the substraitVersions.
     */
    public com.google.protobuf.ProtocolStringList
        getSubstraitVersionsList() {
      return substraitVersions_.getUnmodifiableView();
    }
    /**
     * <pre>
     * List of Substrait versions this system supports
     * </pre>
     *
     * <code>repeated string substrait_versions = 1;</code>
     * @return The count of substraitVersions.
     */
    public int getSubstraitVersionsCount() {
      return substraitVersions_.size();
    }
    /**
     * <pre>
     * List of Substrait versions this system supports
     * </pre>
     *
     * <code>repeated string substrait_versions = 1;</code>
     * @param index The index of the element to return.
     * @return The substraitVersions at the given index.
     */
    public java.lang.String getSubstraitVersions(int index) {
      return substraitVersions_.get(index);
    }
    /**
     * <pre>
     * List of Substrait versions this system supports
     * </pre>
     *
     * <code>repeated string substrait_versions = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the substraitVersions at the given index.
     */
    public com.google.protobuf.ByteString
        getSubstraitVersionsBytes(int index) {
      return substraitVersions_.getByteString(index);
    }
    /**
     * <pre>
     * List of Substrait versions this system supports
     * </pre>
     *
     * <code>repeated string substrait_versions = 1;</code>
     * @param index The index to set the value at.
     * @param value The substraitVersions to set.
     * @return This builder for chaining.
     */
    public Builder setSubstraitVersions(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureSubstraitVersionsIsMutable();
      substraitVersions_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * List of Substrait versions this system supports
     * </pre>
     *
     * <code>repeated string substrait_versions = 1;</code>
     * @param value The substraitVersions to add.
     * @return This builder for chaining.
     */
    public Builder addSubstraitVersions(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureSubstraitVersionsIsMutable();
      substraitVersions_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * List of Substrait versions this system supports
     * </pre>
     *
     * <code>repeated string substrait_versions = 1;</code>
     * @param values The substraitVersions to add.
     * @return This builder for chaining.
     */
    public Builder addAllSubstraitVersions(
        java.lang.Iterable<java.lang.String> values) {
      ensureSubstraitVersionsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, substraitVersions_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * List of Substrait versions this system supports
     * </pre>
     *
     * <code>repeated string substrait_versions = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSubstraitVersions() {
      substraitVersions_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * List of Substrait versions this system supports
     * </pre>
     *
     * <code>repeated string substrait_versions = 1;</code>
     * @param value The bytes of the substraitVersions to add.
     * @return This builder for chaining.
     */
    public Builder addSubstraitVersionsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureSubstraitVersionsIsMutable();
      substraitVersions_.add(value);
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList advancedExtensionTypeUrls_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureAdvancedExtensionTypeUrlsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        advancedExtensionTypeUrls_ = new com.google.protobuf.LazyStringArrayList(advancedExtensionTypeUrls_);
        bitField0_ |= 0x00000002;
       }
    }
    /**
     * <pre>
     * list of com.google.Any message types this system supports for advanced
     * extensions.
     * </pre>
     *
     * <code>repeated string advanced_extension_type_urls = 2;</code>
     * @return A list containing the advancedExtensionTypeUrls.
     */
    public com.google.protobuf.ProtocolStringList
        getAdvancedExtensionTypeUrlsList() {
      return advancedExtensionTypeUrls_.getUnmodifiableView();
    }
    /**
     * <pre>
     * list of com.google.Any message types this system supports for advanced
     * extensions.
     * </pre>
     *
     * <code>repeated string advanced_extension_type_urls = 2;</code>
     * @return The count of advancedExtensionTypeUrls.
     */
    public int getAdvancedExtensionTypeUrlsCount() {
      return advancedExtensionTypeUrls_.size();
    }
    /**
     * <pre>
     * list of com.google.Any message types this system supports for advanced
     * extensions.
     * </pre>
     *
     * <code>repeated string advanced_extension_type_urls = 2;</code>
     * @param index The index of the element to return.
     * @return The advancedExtensionTypeUrls at the given index.
     */
    public java.lang.String getAdvancedExtensionTypeUrls(int index) {
      return advancedExtensionTypeUrls_.get(index);
    }
    /**
     * <pre>
     * list of com.google.Any message types this system supports for advanced
     * extensions.
     * </pre>
     *
     * <code>repeated string advanced_extension_type_urls = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the advancedExtensionTypeUrls at the given index.
     */
    public com.google.protobuf.ByteString
        getAdvancedExtensionTypeUrlsBytes(int index) {
      return advancedExtensionTypeUrls_.getByteString(index);
    }
    /**
     * <pre>
     * list of com.google.Any message types this system supports for advanced
     * extensions.
     * </pre>
     *
     * <code>repeated string advanced_extension_type_urls = 2;</code>
     * @param index The index to set the value at.
     * @param value The advancedExtensionTypeUrls to set.
     * @return This builder for chaining.
     */
    public Builder setAdvancedExtensionTypeUrls(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureAdvancedExtensionTypeUrlsIsMutable();
      advancedExtensionTypeUrls_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * list of com.google.Any message types this system supports for advanced
     * extensions.
     * </pre>
     *
     * <code>repeated string advanced_extension_type_urls = 2;</code>
     * @param value The advancedExtensionTypeUrls to add.
     * @return This builder for chaining.
     */
    public Builder addAdvancedExtensionTypeUrls(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureAdvancedExtensionTypeUrlsIsMutable();
      advancedExtensionTypeUrls_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * list of com.google.Any message types this system supports for advanced
     * extensions.
     * </pre>
     *
     * <code>repeated string advanced_extension_type_urls = 2;</code>
     * @param values The advancedExtensionTypeUrls to add.
     * @return This builder for chaining.
     */
    public Builder addAllAdvancedExtensionTypeUrls(
        java.lang.Iterable<java.lang.String> values) {
      ensureAdvancedExtensionTypeUrlsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, advancedExtensionTypeUrls_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * list of com.google.Any message types this system supports for advanced
     * extensions.
     * </pre>
     *
     * <code>repeated string advanced_extension_type_urls = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearAdvancedExtensionTypeUrls() {
      advancedExtensionTypeUrls_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * list of com.google.Any message types this system supports for advanced
     * extensions.
     * </pre>
     *
     * <code>repeated string advanced_extension_type_urls = 2;</code>
     * @param value The bytes of the advancedExtensionTypeUrls to add.
     * @return This builder for chaining.
     */
    public Builder addAdvancedExtensionTypeUrlsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureAdvancedExtensionTypeUrlsIsMutable();
      advancedExtensionTypeUrls_.add(value);
      onChanged();
      return this;
    }

    private java.util.List<io.substrait.proto.Capabilities.SimpleExtension> simpleExtensions_ =
      java.util.Collections.emptyList();
    private void ensureSimpleExtensionsIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        simpleExtensions_ = new java.util.ArrayList<io.substrait.proto.Capabilities.SimpleExtension>(simpleExtensions_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.substrait.proto.Capabilities.SimpleExtension, io.substrait.proto.Capabilities.SimpleExtension.Builder, io.substrait.proto.Capabilities.SimpleExtensionOrBuilder> simpleExtensionsBuilder_;

    /**
     * <pre>
     * list of simple extensions this system supports.
     * </pre>
     *
     * <code>repeated .substrait.Capabilities.SimpleExtension simple_extensions = 3;</code>
     */
    public java.util.List<io.substrait.proto.Capabilities.SimpleExtension> getSimpleExtensionsList() {
      if (simpleExtensionsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(simpleExtensions_);
      } else {
        return simpleExtensionsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * list of simple extensions this system supports.
     * </pre>
     *
     * <code>repeated .substrait.Capabilities.SimpleExtension simple_extensions = 3;</code>
     */
    public int getSimpleExtensionsCount() {
      if (simpleExtensionsBuilder_ == null) {
        return simpleExtensions_.size();
      } else {
        return simpleExtensionsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * list of simple extensions this system supports.
     * </pre>
     *
     * <code>repeated .substrait.Capabilities.SimpleExtension simple_extensions = 3;</code>
     */
    public io.substrait.proto.Capabilities.SimpleExtension getSimpleExtensions(int index) {
      if (simpleExtensionsBuilder_ == null) {
        return simpleExtensions_.get(index);
      } else {
        return simpleExtensionsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * list of simple extensions this system supports.
     * </pre>
     *
     * <code>repeated .substrait.Capabilities.SimpleExtension simple_extensions = 3;</code>
     */
    public Builder setSimpleExtensions(
        int index, io.substrait.proto.Capabilities.SimpleExtension value) {
      if (simpleExtensionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSimpleExtensionsIsMutable();
        simpleExtensions_.set(index, value);
        onChanged();
      } else {
        simpleExtensionsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * list of simple extensions this system supports.
     * </pre>
     *
     * <code>repeated .substrait.Capabilities.SimpleExtension simple_extensions = 3;</code>
     */
    public Builder setSimpleExtensions(
        int index, io.substrait.proto.Capabilities.SimpleExtension.Builder builderForValue) {
      if (simpleExtensionsBuilder_ == null) {
        ensureSimpleExtensionsIsMutable();
        simpleExtensions_.set(index, builderForValue.build());
        onChanged();
      } else {
        simpleExtensionsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * list of simple extensions this system supports.
     * </pre>
     *
     * <code>repeated .substrait.Capabilities.SimpleExtension simple_extensions = 3;</code>
     */
    public Builder addSimpleExtensions(io.substrait.proto.Capabilities.SimpleExtension value) {
      if (simpleExtensionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSimpleExtensionsIsMutable();
        simpleExtensions_.add(value);
        onChanged();
      } else {
        simpleExtensionsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * list of simple extensions this system supports.
     * </pre>
     *
     * <code>repeated .substrait.Capabilities.SimpleExtension simple_extensions = 3;</code>
     */
    public Builder addSimpleExtensions(
        int index, io.substrait.proto.Capabilities.SimpleExtension value) {
      if (simpleExtensionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSimpleExtensionsIsMutable();
        simpleExtensions_.add(index, value);
        onChanged();
      } else {
        simpleExtensionsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * list of simple extensions this system supports.
     * </pre>
     *
     * <code>repeated .substrait.Capabilities.SimpleExtension simple_extensions = 3;</code>
     */
    public Builder addSimpleExtensions(
        io.substrait.proto.Capabilities.SimpleExtension.Builder builderForValue) {
      if (simpleExtensionsBuilder_ == null) {
        ensureSimpleExtensionsIsMutable();
        simpleExtensions_.add(builderForValue.build());
        onChanged();
      } else {
        simpleExtensionsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * list of simple extensions this system supports.
     * </pre>
     *
     * <code>repeated .substrait.Capabilities.SimpleExtension simple_extensions = 3;</code>
     */
    public Builder addSimpleExtensions(
        int index, io.substrait.proto.Capabilities.SimpleExtension.Builder builderForValue) {
      if (simpleExtensionsBuilder_ == null) {
        ensureSimpleExtensionsIsMutable();
        simpleExtensions_.add(index, builderForValue.build());
        onChanged();
      } else {
        simpleExtensionsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * list of simple extensions this system supports.
     * </pre>
     *
     * <code>repeated .substrait.Capabilities.SimpleExtension simple_extensions = 3;</code>
     */
    public Builder addAllSimpleExtensions(
        java.lang.Iterable<? extends io.substrait.proto.Capabilities.SimpleExtension> values) {
      if (simpleExtensionsBuilder_ == null) {
        ensureSimpleExtensionsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, simpleExtensions_);
        onChanged();
      } else {
        simpleExtensionsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * list of simple extensions this system supports.
     * </pre>
     *
     * <code>repeated .substrait.Capabilities.SimpleExtension simple_extensions = 3;</code>
     */
    public Builder clearSimpleExtensions() {
      if (simpleExtensionsBuilder_ == null) {
        simpleExtensions_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        simpleExtensionsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * list of simple extensions this system supports.
     * </pre>
     *
     * <code>repeated .substrait.Capabilities.SimpleExtension simple_extensions = 3;</code>
     */
    public Builder removeSimpleExtensions(int index) {
      if (simpleExtensionsBuilder_ == null) {
        ensureSimpleExtensionsIsMutable();
        simpleExtensions_.remove(index);
        onChanged();
      } else {
        simpleExtensionsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * list of simple extensions this system supports.
     * </pre>
     *
     * <code>repeated .substrait.Capabilities.SimpleExtension simple_extensions = 3;</code>
     */
    public io.substrait.proto.Capabilities.SimpleExtension.Builder getSimpleExtensionsBuilder(
        int index) {
      return getSimpleExtensionsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * list of simple extensions this system supports.
     * </pre>
     *
     * <code>repeated .substrait.Capabilities.SimpleExtension simple_extensions = 3;</code>
     */
    public io.substrait.proto.Capabilities.SimpleExtensionOrBuilder getSimpleExtensionsOrBuilder(
        int index) {
      if (simpleExtensionsBuilder_ == null) {
        return simpleExtensions_.get(index);  } else {
        return simpleExtensionsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * list of simple extensions this system supports.
     * </pre>
     *
     * <code>repeated .substrait.Capabilities.SimpleExtension simple_extensions = 3;</code>
     */
    public java.util.List<? extends io.substrait.proto.Capabilities.SimpleExtensionOrBuilder> 
         getSimpleExtensionsOrBuilderList() {
      if (simpleExtensionsBuilder_ != null) {
        return simpleExtensionsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(simpleExtensions_);
      }
    }
    /**
     * <pre>
     * list of simple extensions this system supports.
     * </pre>
     *
     * <code>repeated .substrait.Capabilities.SimpleExtension simple_extensions = 3;</code>
     */
    public io.substrait.proto.Capabilities.SimpleExtension.Builder addSimpleExtensionsBuilder() {
      return getSimpleExtensionsFieldBuilder().addBuilder(
          io.substrait.proto.Capabilities.SimpleExtension.getDefaultInstance());
    }
    /**
     * <pre>
     * list of simple extensions this system supports.
     * </pre>
     *
     * <code>repeated .substrait.Capabilities.SimpleExtension simple_extensions = 3;</code>
     */
    public io.substrait.proto.Capabilities.SimpleExtension.Builder addSimpleExtensionsBuilder(
        int index) {
      return getSimpleExtensionsFieldBuilder().addBuilder(
          index, io.substrait.proto.Capabilities.SimpleExtension.getDefaultInstance());
    }
    /**
     * <pre>
     * list of simple extensions this system supports.
     * </pre>
     *
     * <code>repeated .substrait.Capabilities.SimpleExtension simple_extensions = 3;</code>
     */
    public java.util.List<io.substrait.proto.Capabilities.SimpleExtension.Builder> 
         getSimpleExtensionsBuilderList() {
      return getSimpleExtensionsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.substrait.proto.Capabilities.SimpleExtension, io.substrait.proto.Capabilities.SimpleExtension.Builder, io.substrait.proto.Capabilities.SimpleExtensionOrBuilder> 
        getSimpleExtensionsFieldBuilder() {
      if (simpleExtensionsBuilder_ == null) {
        simpleExtensionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            io.substrait.proto.Capabilities.SimpleExtension, io.substrait.proto.Capabilities.SimpleExtension.Builder, io.substrait.proto.Capabilities.SimpleExtensionOrBuilder>(
                simpleExtensions_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        simpleExtensions_ = null;
      }
      return simpleExtensionsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:substrait.Capabilities)
  }

  // @@protoc_insertion_point(class_scope:substrait.Capabilities)
  private static final io.substrait.proto.Capabilities DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.substrait.proto.Capabilities();
  }

  public static io.substrait.proto.Capabilities getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Capabilities>
      PARSER = new com.google.protobuf.AbstractParser<Capabilities>() {
    @java.lang.Override
    public Capabilities parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Capabilities(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Capabilities> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Capabilities> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.substrait.proto.Capabilities getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

