// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: substrait/expression.proto

package io.substrait.proto;

public final class ExpressionOuterClass {
  private ExpressionOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_substrait_Expression_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_substrait_Expression_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_substrait_Expression_Enum_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_substrait_Expression_Enum_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_substrait_Expression_Enum_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_substrait_Expression_Enum_Empty_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_substrait_Expression_Literal_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_substrait_Expression_Literal_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_substrait_Expression_Literal_VarChar_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_substrait_Expression_Literal_VarChar_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_substrait_Expression_Literal_Decimal_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_substrait_Expression_Literal_Decimal_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_substrait_Expression_Literal_Map_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_substrait_Expression_Literal_Map_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_substrait_Expression_Literal_Map_KeyValue_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_substrait_Expression_Literal_Map_KeyValue_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_substrait_Expression_Literal_IntervalYearToMonth_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_substrait_Expression_Literal_IntervalYearToMonth_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_substrait_Expression_Literal_IntervalDayToSecond_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_substrait_Expression_Literal_IntervalDayToSecond_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_substrait_Expression_Literal_Struct_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_substrait_Expression_Literal_Struct_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_substrait_Expression_Literal_List_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_substrait_Expression_Literal_List_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_substrait_Expression_ScalarFunction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_substrait_Expression_ScalarFunction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_substrait_Expression_WindowFunction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_substrait_Expression_WindowFunction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_substrait_Expression_WindowFunction_Bound_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_substrait_Expression_WindowFunction_Bound_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_substrait_Expression_WindowFunction_Bound_Preceding_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_substrait_Expression_WindowFunction_Bound_Preceding_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_substrait_Expression_WindowFunction_Bound_Following_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_substrait_Expression_WindowFunction_Bound_Following_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_substrait_Expression_WindowFunction_Bound_CurrentRow_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_substrait_Expression_WindowFunction_Bound_CurrentRow_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_substrait_Expression_WindowFunction_Bound_Unbounded_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_substrait_Expression_WindowFunction_Bound_Unbounded_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_substrait_Expression_IfThen_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_substrait_Expression_IfThen_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_substrait_Expression_IfThen_IfClause_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_substrait_Expression_IfThen_IfClause_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_substrait_Expression_Cast_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_substrait_Expression_Cast_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_substrait_Expression_SwitchExpression_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_substrait_Expression_SwitchExpression_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_substrait_Expression_SwitchExpression_IfValue_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_substrait_Expression_SwitchExpression_IfValue_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_substrait_Expression_SingularOrList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_substrait_Expression_SingularOrList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_substrait_Expression_MultiOrList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_substrait_Expression_MultiOrList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_substrait_Expression_MultiOrList_Record_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_substrait_Expression_MultiOrList_Record_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_substrait_Expression_EmbeddedFunction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_substrait_Expression_EmbeddedFunction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_substrait_Expression_EmbeddedFunction_PythonPickleFunction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_substrait_Expression_EmbeddedFunction_PythonPickleFunction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_substrait_Expression_EmbeddedFunction_WebAssemblyFunction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_substrait_Expression_EmbeddedFunction_WebAssemblyFunction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_substrait_Expression_ReferenceSegment_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_substrait_Expression_ReferenceSegment_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_substrait_Expression_ReferenceSegment_MapKey_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_substrait_Expression_ReferenceSegment_MapKey_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_substrait_Expression_ReferenceSegment_StructField_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_substrait_Expression_ReferenceSegment_StructField_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_substrait_Expression_ReferenceSegment_ListElement_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_substrait_Expression_ReferenceSegment_ListElement_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_substrait_Expression_MaskExpression_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_substrait_Expression_MaskExpression_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_substrait_Expression_MaskExpression_Select_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_substrait_Expression_MaskExpression_Select_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_substrait_Expression_MaskExpression_StructSelect_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_substrait_Expression_MaskExpression_StructSelect_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_substrait_Expression_MaskExpression_StructItem_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_substrait_Expression_MaskExpression_StructItem_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_substrait_Expression_MaskExpression_ListSelect_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_substrait_Expression_MaskExpression_ListSelect_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_substrait_Expression_MaskExpression_ListSelect_ListSelectItem_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_substrait_Expression_MaskExpression_ListSelect_ListSelectItem_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_substrait_Expression_MaskExpression_ListSelect_ListSelectItem_ListElement_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_substrait_Expression_MaskExpression_ListSelect_ListSelectItem_ListElement_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_substrait_Expression_MaskExpression_ListSelect_ListSelectItem_ListSlice_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_substrait_Expression_MaskExpression_ListSelect_ListSelectItem_ListSlice_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_substrait_Expression_MaskExpression_MapSelect_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_substrait_Expression_MaskExpression_MapSelect_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_substrait_Expression_MaskExpression_MapSelect_MapKey_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_substrait_Expression_MaskExpression_MapSelect_MapKey_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_substrait_Expression_MaskExpression_MapSelect_MapKeyExpression_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_substrait_Expression_MaskExpression_MapSelect_MapKeyExpression_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_substrait_Expression_FieldReference_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_substrait_Expression_FieldReference_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_substrait_Expression_FieldReference_RootReference_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_substrait_Expression_FieldReference_RootReference_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_substrait_SortField_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_substrait_SortField_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_substrait_AggregateFunction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_substrait_AggregateFunction_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032substrait/expression.proto\022\tsubstrait\032" +
      "\024substrait/type.proto\"\2101\n\nExpression\0220\n\007" +
      "literal\030\001 \001(\0132\035.substrait.Expression.Lit" +
      "eralH\000\0229\n\tselection\030\002 \001(\0132$.substrait.Ex" +
      "pression.FieldReferenceH\000\022?\n\017scalar_func" +
      "tion\030\003 \001(\0132$.substrait.Expression.Scalar" +
      "FunctionH\000\022?\n\017window_function\030\005 \001(\0132$.su" +
      "bstrait.Expression.WindowFunctionH\000\022/\n\007i" +
      "f_then\030\006 \001(\0132\034.substrait.Expression.IfTh" +
      "enH\000\022C\n\021switch_expression\030\007 \001(\0132&.substr" +
      "ait.Expression.SwitchExpressionH\000\022@\n\020sin" +
      "gular_or_list\030\010 \001(\0132$.substrait.Expressi" +
      "on.SingularOrListH\000\022:\n\rmulti_or_list\030\t \001" +
      "(\0132!.substrait.Expression.MultiOrListH\000\022" +
      "*\n\004enum\030\n \001(\0132\032.substrait.Expression.Enu" +
      "mH\000\022*\n\004cast\030\013 \001(\0132\032.substrait.Expression" +
      ".CastH\000\032j\n\004Enum\022\023\n\tspecified\030\001 \001(\tH\000\0227\n\013" +
      "unspecified\030\002 \001(\0132 .substrait.Expression" +
      ".Enum.EmptyH\000\032\007\n\005EmptyB\013\n\tenum_kind\032\354\n\n\007" +
      "Literal\022\021\n\007boolean\030\001 \001(\010H\000\022\014\n\002i8\030\002 \001(\005H\000" +
      "\022\r\n\003i16\030\003 \001(\005H\000\022\r\n\003i32\030\005 \001(\005H\000\022\r\n\003i64\030\007 " +
      "\001(\003H\000\022\016\n\004fp32\030\n \001(\002H\000\022\016\n\004fp64\030\013 \001(\001H\000\022\020\n" +
      "\006string\030\014 \001(\tH\000\022\020\n\006binary\030\r \001(\014H\000\022\023\n\ttim" +
      "estamp\030\016 \001(\003H\000\022\016\n\004date\030\020 \001(\005H\000\022\016\n\004time\030\021" +
      " \001(\003H\000\022S\n\026interval_year_to_month\030\023 \001(\01321" +
      ".substrait.Expression.Literal.IntervalYe" +
      "arToMonthH\000\022S\n\026interval_day_to_second\030\024 " +
      "\001(\01321.substrait.Expression.Literal.Inter" +
      "valDayToSecondH\000\022\024\n\nfixed_char\030\025 \001(\tH\000\0229" +
      "\n\010var_char\030\026 \001(\0132%.substrait.Expression." +
      "Literal.VarCharH\000\022\026\n\014fixed_binary\030\027 \001(\014H" +
      "\000\0228\n\007decimal\030\030 \001(\0132%.substrait.Expressio" +
      "n.Literal.DecimalH\000\0226\n\006struct\030\031 \001(\0132$.su" +
      "bstrait.Expression.Literal.StructH\000\0220\n\003m" +
      "ap\030\032 \001(\0132!.substrait.Expression.Literal." +
      "MapH\000\022\026\n\014timestamp_tz\030\033 \001(\003H\000\022\016\n\004uuid\030\034 " +
      "\001(\014H\000\022\037\n\004null\030\035 \001(\0132\017.substrait.TypeH\000\0222" +
      "\n\004list\030\036 \001(\0132\".substrait.Expression.Lite" +
      "ral.ListH\000\022*\n\nempty_list\030\037 \001(\0132\024.substra" +
      "it.Type.ListH\000\022(\n\tempty_map\030  \001(\0132\023.subs" +
      "trait.Type.MapH\000\022\020\n\010nullable\0302 \001(\010\032(\n\007Va" +
      "rChar\022\r\n\005value\030\001 \001(\t\022\016\n\006length\030\002 \001(\r\032:\n\007" +
      "Decimal\022\r\n\005value\030\001 \001(\014\022\021\n\tprecision\030\002 \001(" +
      "\005\022\r\n\005scale\030\003 \001(\005\032\253\001\n\003Map\022>\n\nkey_values\030\001" +
      " \003(\0132*.substrait.Expression.Literal.Map." +
      "KeyValue\032d\n\010KeyValue\022*\n\003key\030\001 \001(\0132\035.subs" +
      "trait.Expression.Literal\022,\n\005value\030\002 \001(\0132" +
      "\035.substrait.Expression.Literal\0324\n\023Interv" +
      "alYearToMonth\022\r\n\005years\030\001 \001(\005\022\016\n\006months\030\002" +
      " \001(\005\0324\n\023IntervalDayToSecond\022\014\n\004days\030\001 \001(" +
      "\005\022\017\n\007seconds\030\002 \001(\005\0327\n\006Struct\022-\n\006fields\030\001" +
      " \003(\0132\035.substrait.Expression.Literal\0325\n\004L" +
      "ist\022-\n\006values\030\001 \003(\0132\035.substrait.Expressi" +
      "on.LiteralB\016\n\014literal_type\032w\n\016ScalarFunc" +
      "tion\022\032\n\022function_reference\030\001 \001(\r\022#\n\004args" +
      "\030\002 \003(\0132\025.substrait.Expression\022$\n\013output_" +
      "type\030\003 \001(\0132\017.substrait.Type\032\213\006\n\016WindowFu" +
      "nction\022\032\n\022function_reference\030\001 \001(\r\022)\n\npa" +
      "rtitions\030\002 \003(\0132\025.substrait.Expression\022#\n" +
      "\005sorts\030\003 \003(\0132\024.substrait.SortField\022?\n\013up" +
      "per_bound\030\004 \001(\0132*.substrait.Expression.W" +
      "indowFunction.Bound\022?\n\013lower_bound\030\005 \001(\013" +
      "2*.substrait.Expression.WindowFunction.B" +
      "ound\022*\n\005phase\030\006 \001(\0162\033.substrait.Aggregat" +
      "ionPhase\022$\n\013output_type\030\007 \001(\0132\017.substrai" +
      "t.Type\022#\n\004args\030\010 \003(\0132\025.substrait.Express" +
      "ion\032\223\003\n\005Bound\022I\n\tpreceding\030\001 \001(\01324.subst" +
      "rait.Expression.WindowFunction.Bound.Pre" +
      "cedingH\000\022I\n\tfollowing\030\002 \001(\01324.substrait." +
      "Expression.WindowFunction.Bound.Followin" +
      "gH\000\022L\n\013current_row\030\003 \001(\01325.substrait.Exp" +
      "ression.WindowFunction.Bound.CurrentRowH" +
      "\000\022I\n\tunbounded\030\004 \001(\01324.substrait.Express" +
      "ion.WindowFunction.Bound.UnboundedH\000\032\033\n\t" +
      "Preceding\022\016\n\006offset\030\001 \001(\003\032\033\n\tFollowing\022\016" +
      "\n\006offset\030\001 \001(\003\032\014\n\nCurrentRow\032\013\n\tUnbounde" +
      "dB\006\n\004kind\032\265\001\n\006IfThen\0222\n\003ifs\030\001 \003(\0132%.subs" +
      "trait.Expression.IfThen.IfClause\022#\n\004else" +
      "\030\002 \001(\0132\025.substrait.Expression\032R\n\010IfClaus" +
      "e\022!\n\002if\030\001 \001(\0132\025.substrait.Expression\022#\n\004" +
      "then\030\002 \001(\0132\025.substrait.Expression\032K\n\004Cas" +
      "t\022\035\n\004type\030\001 \001(\0132\017.substrait.Type\022$\n\005inpu" +
      "t\030\002 \001(\0132\025.substrait.Expression\032\317\001\n\020Switc" +
      "hExpression\022;\n\003ifs\030\001 \003(\0132..substrait.Exp" +
      "ression.SwitchExpression.IfValue\022#\n\004else" +
      "\030\002 \001(\0132\025.substrait.Expression\032Y\n\007IfValue" +
      "\022)\n\002if\030\001 \001(\0132\035.substrait.Expression.Lite" +
      "ral\022#\n\004then\030\002 \001(\0132\025.substrait.Expression" +
      "\032^\n\016SingularOrList\022$\n\005value\030\001 \001(\0132\025.subs" +
      "trait.Expression\022&\n\007options\030\002 \003(\0132\025.subs" +
      "trait.Expression\032\237\001\n\013MultiOrList\022$\n\005valu" +
      "e\030\001 \003(\0132\025.substrait.Expression\0229\n\007option" +
      "s\030\002 \003(\0132(.substrait.Expression.MultiOrLi" +
      "st.Record\032/\n\006Record\022%\n\006fields\030\001 \003(\0132\025.su" +
      "bstrait.Expression\032\243\003\n\020EmbeddedFunction\022" +
      "(\n\targuments\030\001 \003(\0132\025.substrait.Expressio" +
      "n\022$\n\013output_type\030\002 \001(\0132\017.substrait.Type\022" +
      "]\n\026python_pickle_function\030\003 \001(\0132;.substr" +
      "ait.Expression.EmbeddedFunction.PythonPi" +
      "ckleFunctionH\000\022[\n\025web_assembly_function\030" +
      "\004 \001(\0132:.substrait.Expression.EmbeddedFun" +
      "ction.WebAssemblyFunctionH\000\032>\n\024PythonPic" +
      "kleFunction\022\020\n\010function\030\001 \001(\014\022\024\n\014prerequ" +
      "isite\030\002 \003(\t\032;\n\023WebAssemblyFunction\022\016\n\006sc" +
      "ript\030\001 \001(\014\022\024\n\014prerequisite\030\002 \003(\tB\006\n\004kind" +
      "\032\232\004\n\020ReferenceSegment\022@\n\007map_key\030\001 \001(\0132-" +
      ".substrait.Expression.ReferenceSegment.M" +
      "apKeyH\000\022J\n\014struct_field\030\002 \001(\01322.substrai" +
      "t.Expression.ReferenceSegment.StructFiel" +
      "dH\000\022J\n\014list_element\030\003 \001(\01322.substrait.Ex" +
      "pression.ReferenceSegment.ListElementH\000\032" +
      "o\n\006MapKey\022.\n\007map_key\030\001 \001(\0132\035.substrait.E" +
      "xpression.Literal\0225\n\005child\030\002 \001(\0132&.subst" +
      "rait.Expression.ReferenceSegment\032S\n\013Stru" +
      "ctField\022\r\n\005field\030\001 \001(\005\0225\n\005child\030\002 \001(\0132&." +
      "substrait.Expression.ReferenceSegment\032T\n" +
      "\013ListElement\022\016\n\006offset\030\001 \001(\005\0225\n\005child\030\002 " +
      "\001(\0132&.substrait.Expression.ReferenceSegm" +
      "entB\020\n\016reference_type\032\360\t\n\016MaskExpression" +
      "\022A\n\006select\030\001 \001(\01321.substrait.Expression." +
      "MaskExpression.StructSelect\022 \n\030maintain_" +
      "singular_struct\030\002 \001(\010\032\325\001\n\006Select\022C\n\006stru" +
      "ct\030\001 \001(\01321.substrait.Expression.MaskExpr" +
      "ession.StructSelectH\000\022?\n\004list\030\002 \001(\0132/.su" +
      "bstrait.Expression.MaskExpression.ListSe" +
      "lectH\000\022=\n\003map\030\003 \001(\0132..substrait.Expressi" +
      "on.MaskExpression.MapSelectH\000B\006\n\004type\032U\n" +
      "\014StructSelect\022E\n\014struct_items\030\001 \003(\0132/.su" +
      "bstrait.Expression.MaskExpression.Struct" +
      "Item\032W\n\nStructItem\022\r\n\005field\030\001 \001(\005\022:\n\005chi" +
      "ld\030\002 \001(\0132+.substrait.Expression.MaskExpr" +
      "ession.Select\032\264\003\n\nListSelect\022Q\n\tselectio" +
      "n\030\001 \003(\0132>.substrait.Expression.MaskExpre" +
      "ssion.ListSelect.ListSelectItem\022:\n\005child" +
      "\030\002 \001(\0132+.substrait.Expression.MaskExpres" +
      "sion.Select\032\226\002\n\016ListSelectItem\022Z\n\004item\030\001" +
      " \001(\0132J.substrait.Expression.MaskExpressi" +
      "on.ListSelect.ListSelectItem.ListElement" +
      "H\000\022Y\n\005slice\030\002 \001(\0132H.substrait.Expression" +
      ".MaskExpression.ListSelect.ListSelectIte" +
      "m.ListSliceH\000\032\034\n\013ListElement\022\r\n\005field\030\001 " +
      "\001(\005\032\'\n\tListSlice\022\r\n\005start\030\001 \001(\005\022\013\n\003end\030\002" +
      " \001(\005B\006\n\004type\032\271\002\n\tMapSelect\022D\n\003key\030\001 \001(\0132" +
      "5.substrait.Expression.MaskExpression.Ma" +
      "pSelect.MapKeyH\000\022U\n\nexpression\030\002 \001(\0132?.s" +
      "ubstrait.Expression.MaskExpression.MapSe" +
      "lect.MapKeyExpressionH\000\022:\n\005child\030\003 \001(\0132+" +
      ".substrait.Expression.MaskExpression.Sel" +
      "ect\032\031\n\006MapKey\022\017\n\007map_key\030\001 \001(\t\032.\n\020MapKey" +
      "Expression\022\032\n\022map_key_expression\030\001 \001(\tB\010" +
      "\n\006select\032\301\002\n\016FieldReference\022B\n\020direct_re" +
      "ference\030\001 \001(\0132&.substrait.Expression.Ref" +
      "erenceSegmentH\000\022@\n\020masked_reference\030\002 \001(" +
      "\0132$.substrait.Expression.MaskExpressionH" +
      "\000\022+\n\nexpression\030\003 \001(\0132\025.substrait.Expres" +
      "sionH\001\022L\n\016root_reference\030\004 \001(\01322.substra" +
      "it.Expression.FieldReference.RootReferen" +
      "ceH\001\032\017\n\rRootReferenceB\020\n\016reference_typeB" +
      "\013\n\troot_typeB\n\n\010rex_type\"\377\002\n\tSortField\022#" +
      "\n\004expr\030\001 \001(\0132\025.substrait.Expression\0227\n\td" +
      "irection\030\002 \001(\0162\".substrait.SortField.Sor" +
      "tDirectionH\000\022\'\n\035comparison_function_refe" +
      "rence\030\003 \001(\rH\000\"\335\001\n\rSortDirection\022\036\n\032SORT_" +
      "DIRECTION_UNSPECIFIED\020\000\022\"\n\036SORT_DIRECTIO" +
      "N_ASC_NULLS_FIRST\020\001\022!\n\035SORT_DIRECTION_AS" +
      "C_NULLS_LAST\020\002\022#\n\037SORT_DIRECTION_DESC_NU" +
      "LLS_FIRST\020\003\022\"\n\036SORT_DIRECTION_DESC_NULLS" +
      "_LAST\020\004\022\034\n\030SORT_DIRECTION_CLUSTERED\020\005B\013\n" +
      "\tsort_kind\"\313\001\n\021AggregateFunction\022\032\n\022func" +
      "tion_reference\030\001 \001(\r\022#\n\004args\030\002 \003(\0132\025.sub" +
      "strait.Expression\022#\n\005sorts\030\003 \003(\0132\024.subst" +
      "rait.SortField\022*\n\005phase\030\004 \001(\0162\033.substrai" +
      "t.AggregationPhase\022$\n\013output_type\030\005 \001(\0132" +
      "\017.substrait.Type*\357\001\n\020AggregationPhase\022!\n" +
      "\035AGGREGATION_PHASE_UNSPECIFIED\020\000\022-\n)AGGR" +
      "EGATION_PHASE_INITIAL_TO_INTERMEDIATE\020\001\022" +
      "2\n.AGGREGATION_PHASE_INTERMEDIATE_TO_INT" +
      "ERMEDIATE\020\002\022\'\n#AGGREGATION_PHASE_INITIAL" +
      "_TO_RESULT\020\003\022,\n(AGGREGATION_PHASE_INTERM" +
      "EDIATE_TO_RESULT\020\004B+\n\022io.substrait.proto" +
      "P\001\252\002\022Substrait.Protobufb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.substrait.proto.TypeOuterClass.getDescriptor(),
        });
    internal_static_substrait_Expression_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_substrait_Expression_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_substrait_Expression_descriptor,
        new java.lang.String[] { "Literal", "Selection", "ScalarFunction", "WindowFunction", "IfThen", "SwitchExpression", "SingularOrList", "MultiOrList", "Enum", "Cast", "RexType", });
    internal_static_substrait_Expression_Enum_descriptor =
      internal_static_substrait_Expression_descriptor.getNestedTypes().get(0);
    internal_static_substrait_Expression_Enum_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_substrait_Expression_Enum_descriptor,
        new java.lang.String[] { "Specified", "Unspecified", "EnumKind", });
    internal_static_substrait_Expression_Enum_Empty_descriptor =
      internal_static_substrait_Expression_Enum_descriptor.getNestedTypes().get(0);
    internal_static_substrait_Expression_Enum_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_substrait_Expression_Enum_Empty_descriptor,
        new java.lang.String[] { });
    internal_static_substrait_Expression_Literal_descriptor =
      internal_static_substrait_Expression_descriptor.getNestedTypes().get(1);
    internal_static_substrait_Expression_Literal_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_substrait_Expression_Literal_descriptor,
        new java.lang.String[] { "Boolean", "I8", "I16", "I32", "I64", "Fp32", "Fp64", "String", "Binary", "Timestamp", "Date", "Time", "IntervalYearToMonth", "IntervalDayToSecond", "FixedChar", "VarChar", "FixedBinary", "Decimal", "Struct", "Map", "TimestampTz", "Uuid", "Null", "List", "EmptyList", "EmptyMap", "Nullable", "LiteralType", });
    internal_static_substrait_Expression_Literal_VarChar_descriptor =
      internal_static_substrait_Expression_Literal_descriptor.getNestedTypes().get(0);
    internal_static_substrait_Expression_Literal_VarChar_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_substrait_Expression_Literal_VarChar_descriptor,
        new java.lang.String[] { "Value", "Length", });
    internal_static_substrait_Expression_Literal_Decimal_descriptor =
      internal_static_substrait_Expression_Literal_descriptor.getNestedTypes().get(1);
    internal_static_substrait_Expression_Literal_Decimal_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_substrait_Expression_Literal_Decimal_descriptor,
        new java.lang.String[] { "Value", "Precision", "Scale", });
    internal_static_substrait_Expression_Literal_Map_descriptor =
      internal_static_substrait_Expression_Literal_descriptor.getNestedTypes().get(2);
    internal_static_substrait_Expression_Literal_Map_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_substrait_Expression_Literal_Map_descriptor,
        new java.lang.String[] { "KeyValues", });
    internal_static_substrait_Expression_Literal_Map_KeyValue_descriptor =
      internal_static_substrait_Expression_Literal_Map_descriptor.getNestedTypes().get(0);
    internal_static_substrait_Expression_Literal_Map_KeyValue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_substrait_Expression_Literal_Map_KeyValue_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_substrait_Expression_Literal_IntervalYearToMonth_descriptor =
      internal_static_substrait_Expression_Literal_descriptor.getNestedTypes().get(3);
    internal_static_substrait_Expression_Literal_IntervalYearToMonth_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_substrait_Expression_Literal_IntervalYearToMonth_descriptor,
        new java.lang.String[] { "Years", "Months", });
    internal_static_substrait_Expression_Literal_IntervalDayToSecond_descriptor =
      internal_static_substrait_Expression_Literal_descriptor.getNestedTypes().get(4);
    internal_static_substrait_Expression_Literal_IntervalDayToSecond_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_substrait_Expression_Literal_IntervalDayToSecond_descriptor,
        new java.lang.String[] { "Days", "Seconds", });
    internal_static_substrait_Expression_Literal_Struct_descriptor =
      internal_static_substrait_Expression_Literal_descriptor.getNestedTypes().get(5);
    internal_static_substrait_Expression_Literal_Struct_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_substrait_Expression_Literal_Struct_descriptor,
        new java.lang.String[] { "Fields", });
    internal_static_substrait_Expression_Literal_List_descriptor =
      internal_static_substrait_Expression_Literal_descriptor.getNestedTypes().get(6);
    internal_static_substrait_Expression_Literal_List_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_substrait_Expression_Literal_List_descriptor,
        new java.lang.String[] { "Values", });
    internal_static_substrait_Expression_ScalarFunction_descriptor =
      internal_static_substrait_Expression_descriptor.getNestedTypes().get(2);
    internal_static_substrait_Expression_ScalarFunction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_substrait_Expression_ScalarFunction_descriptor,
        new java.lang.String[] { "FunctionReference", "Args", "OutputType", });
    internal_static_substrait_Expression_WindowFunction_descriptor =
      internal_static_substrait_Expression_descriptor.getNestedTypes().get(3);
    internal_static_substrait_Expression_WindowFunction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_substrait_Expression_WindowFunction_descriptor,
        new java.lang.String[] { "FunctionReference", "Partitions", "Sorts", "UpperBound", "LowerBound", "Phase", "OutputType", "Args", });
    internal_static_substrait_Expression_WindowFunction_Bound_descriptor =
      internal_static_substrait_Expression_WindowFunction_descriptor.getNestedTypes().get(0);
    internal_static_substrait_Expression_WindowFunction_Bound_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_substrait_Expression_WindowFunction_Bound_descriptor,
        new java.lang.String[] { "Preceding", "Following", "CurrentRow", "Unbounded", "Kind", });
    internal_static_substrait_Expression_WindowFunction_Bound_Preceding_descriptor =
      internal_static_substrait_Expression_WindowFunction_Bound_descriptor.getNestedTypes().get(0);
    internal_static_substrait_Expression_WindowFunction_Bound_Preceding_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_substrait_Expression_WindowFunction_Bound_Preceding_descriptor,
        new java.lang.String[] { "Offset", });
    internal_static_substrait_Expression_WindowFunction_Bound_Following_descriptor =
      internal_static_substrait_Expression_WindowFunction_Bound_descriptor.getNestedTypes().get(1);
    internal_static_substrait_Expression_WindowFunction_Bound_Following_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_substrait_Expression_WindowFunction_Bound_Following_descriptor,
        new java.lang.String[] { "Offset", });
    internal_static_substrait_Expression_WindowFunction_Bound_CurrentRow_descriptor =
      internal_static_substrait_Expression_WindowFunction_Bound_descriptor.getNestedTypes().get(2);
    internal_static_substrait_Expression_WindowFunction_Bound_CurrentRow_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_substrait_Expression_WindowFunction_Bound_CurrentRow_descriptor,
        new java.lang.String[] { });
    internal_static_substrait_Expression_WindowFunction_Bound_Unbounded_descriptor =
      internal_static_substrait_Expression_WindowFunction_Bound_descriptor.getNestedTypes().get(3);
    internal_static_substrait_Expression_WindowFunction_Bound_Unbounded_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_substrait_Expression_WindowFunction_Bound_Unbounded_descriptor,
        new java.lang.String[] { });
    internal_static_substrait_Expression_IfThen_descriptor =
      internal_static_substrait_Expression_descriptor.getNestedTypes().get(4);
    internal_static_substrait_Expression_IfThen_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_substrait_Expression_IfThen_descriptor,
        new java.lang.String[] { "Ifs", "Else", });
    internal_static_substrait_Expression_IfThen_IfClause_descriptor =
      internal_static_substrait_Expression_IfThen_descriptor.getNestedTypes().get(0);
    internal_static_substrait_Expression_IfThen_IfClause_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_substrait_Expression_IfThen_IfClause_descriptor,
        new java.lang.String[] { "If", "Then", });
    internal_static_substrait_Expression_Cast_descriptor =
      internal_static_substrait_Expression_descriptor.getNestedTypes().get(5);
    internal_static_substrait_Expression_Cast_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_substrait_Expression_Cast_descriptor,
        new java.lang.String[] { "Type", "Input", });
    internal_static_substrait_Expression_SwitchExpression_descriptor =
      internal_static_substrait_Expression_descriptor.getNestedTypes().get(6);
    internal_static_substrait_Expression_SwitchExpression_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_substrait_Expression_SwitchExpression_descriptor,
        new java.lang.String[] { "Ifs", "Else", });
    internal_static_substrait_Expression_SwitchExpression_IfValue_descriptor =
      internal_static_substrait_Expression_SwitchExpression_descriptor.getNestedTypes().get(0);
    internal_static_substrait_Expression_SwitchExpression_IfValue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_substrait_Expression_SwitchExpression_IfValue_descriptor,
        new java.lang.String[] { "If", "Then", });
    internal_static_substrait_Expression_SingularOrList_descriptor =
      internal_static_substrait_Expression_descriptor.getNestedTypes().get(7);
    internal_static_substrait_Expression_SingularOrList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_substrait_Expression_SingularOrList_descriptor,
        new java.lang.String[] { "Value", "Options", });
    internal_static_substrait_Expression_MultiOrList_descriptor =
      internal_static_substrait_Expression_descriptor.getNestedTypes().get(8);
    internal_static_substrait_Expression_MultiOrList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_substrait_Expression_MultiOrList_descriptor,
        new java.lang.String[] { "Value", "Options", });
    internal_static_substrait_Expression_MultiOrList_Record_descriptor =
      internal_static_substrait_Expression_MultiOrList_descriptor.getNestedTypes().get(0);
    internal_static_substrait_Expression_MultiOrList_Record_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_substrait_Expression_MultiOrList_Record_descriptor,
        new java.lang.String[] { "Fields", });
    internal_static_substrait_Expression_EmbeddedFunction_descriptor =
      internal_static_substrait_Expression_descriptor.getNestedTypes().get(9);
    internal_static_substrait_Expression_EmbeddedFunction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_substrait_Expression_EmbeddedFunction_descriptor,
        new java.lang.String[] { "Arguments", "OutputType", "PythonPickleFunction", "WebAssemblyFunction", "Kind", });
    internal_static_substrait_Expression_EmbeddedFunction_PythonPickleFunction_descriptor =
      internal_static_substrait_Expression_EmbeddedFunction_descriptor.getNestedTypes().get(0);
    internal_static_substrait_Expression_EmbeddedFunction_PythonPickleFunction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_substrait_Expression_EmbeddedFunction_PythonPickleFunction_descriptor,
        new java.lang.String[] { "Function", "Prerequisite", });
    internal_static_substrait_Expression_EmbeddedFunction_WebAssemblyFunction_descriptor =
      internal_static_substrait_Expression_EmbeddedFunction_descriptor.getNestedTypes().get(1);
    internal_static_substrait_Expression_EmbeddedFunction_WebAssemblyFunction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_substrait_Expression_EmbeddedFunction_WebAssemblyFunction_descriptor,
        new java.lang.String[] { "Script", "Prerequisite", });
    internal_static_substrait_Expression_ReferenceSegment_descriptor =
      internal_static_substrait_Expression_descriptor.getNestedTypes().get(10);
    internal_static_substrait_Expression_ReferenceSegment_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_substrait_Expression_ReferenceSegment_descriptor,
        new java.lang.String[] { "MapKey", "StructField", "ListElement", "ReferenceType", });
    internal_static_substrait_Expression_ReferenceSegment_MapKey_descriptor =
      internal_static_substrait_Expression_ReferenceSegment_descriptor.getNestedTypes().get(0);
    internal_static_substrait_Expression_ReferenceSegment_MapKey_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_substrait_Expression_ReferenceSegment_MapKey_descriptor,
        new java.lang.String[] { "MapKey", "Child", });
    internal_static_substrait_Expression_ReferenceSegment_StructField_descriptor =
      internal_static_substrait_Expression_ReferenceSegment_descriptor.getNestedTypes().get(1);
    internal_static_substrait_Expression_ReferenceSegment_StructField_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_substrait_Expression_ReferenceSegment_StructField_descriptor,
        new java.lang.String[] { "Field", "Child", });
    internal_static_substrait_Expression_ReferenceSegment_ListElement_descriptor =
      internal_static_substrait_Expression_ReferenceSegment_descriptor.getNestedTypes().get(2);
    internal_static_substrait_Expression_ReferenceSegment_ListElement_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_substrait_Expression_ReferenceSegment_ListElement_descriptor,
        new java.lang.String[] { "Offset", "Child", });
    internal_static_substrait_Expression_MaskExpression_descriptor =
      internal_static_substrait_Expression_descriptor.getNestedTypes().get(11);
    internal_static_substrait_Expression_MaskExpression_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_substrait_Expression_MaskExpression_descriptor,
        new java.lang.String[] { "Select", "MaintainSingularStruct", });
    internal_static_substrait_Expression_MaskExpression_Select_descriptor =
      internal_static_substrait_Expression_MaskExpression_descriptor.getNestedTypes().get(0);
    internal_static_substrait_Expression_MaskExpression_Select_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_substrait_Expression_MaskExpression_Select_descriptor,
        new java.lang.String[] { "Struct", "List", "Map", "Type", });
    internal_static_substrait_Expression_MaskExpression_StructSelect_descriptor =
      internal_static_substrait_Expression_MaskExpression_descriptor.getNestedTypes().get(1);
    internal_static_substrait_Expression_MaskExpression_StructSelect_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_substrait_Expression_MaskExpression_StructSelect_descriptor,
        new java.lang.String[] { "StructItems", });
    internal_static_substrait_Expression_MaskExpression_StructItem_descriptor =
      internal_static_substrait_Expression_MaskExpression_descriptor.getNestedTypes().get(2);
    internal_static_substrait_Expression_MaskExpression_StructItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_substrait_Expression_MaskExpression_StructItem_descriptor,
        new java.lang.String[] { "Field", "Child", });
    internal_static_substrait_Expression_MaskExpression_ListSelect_descriptor =
      internal_static_substrait_Expression_MaskExpression_descriptor.getNestedTypes().get(3);
    internal_static_substrait_Expression_MaskExpression_ListSelect_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_substrait_Expression_MaskExpression_ListSelect_descriptor,
        new java.lang.String[] { "Selection", "Child", });
    internal_static_substrait_Expression_MaskExpression_ListSelect_ListSelectItem_descriptor =
      internal_static_substrait_Expression_MaskExpression_ListSelect_descriptor.getNestedTypes().get(0);
    internal_static_substrait_Expression_MaskExpression_ListSelect_ListSelectItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_substrait_Expression_MaskExpression_ListSelect_ListSelectItem_descriptor,
        new java.lang.String[] { "Item", "Slice", "Type", });
    internal_static_substrait_Expression_MaskExpression_ListSelect_ListSelectItem_ListElement_descriptor =
      internal_static_substrait_Expression_MaskExpression_ListSelect_ListSelectItem_descriptor.getNestedTypes().get(0);
    internal_static_substrait_Expression_MaskExpression_ListSelect_ListSelectItem_ListElement_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_substrait_Expression_MaskExpression_ListSelect_ListSelectItem_ListElement_descriptor,
        new java.lang.String[] { "Field", });
    internal_static_substrait_Expression_MaskExpression_ListSelect_ListSelectItem_ListSlice_descriptor =
      internal_static_substrait_Expression_MaskExpression_ListSelect_ListSelectItem_descriptor.getNestedTypes().get(1);
    internal_static_substrait_Expression_MaskExpression_ListSelect_ListSelectItem_ListSlice_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_substrait_Expression_MaskExpression_ListSelect_ListSelectItem_ListSlice_descriptor,
        new java.lang.String[] { "Start", "End", });
    internal_static_substrait_Expression_MaskExpression_MapSelect_descriptor =
      internal_static_substrait_Expression_MaskExpression_descriptor.getNestedTypes().get(4);
    internal_static_substrait_Expression_MaskExpression_MapSelect_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_substrait_Expression_MaskExpression_MapSelect_descriptor,
        new java.lang.String[] { "Key", "Expression", "Child", "Select", });
    internal_static_substrait_Expression_MaskExpression_MapSelect_MapKey_descriptor =
      internal_static_substrait_Expression_MaskExpression_MapSelect_descriptor.getNestedTypes().get(0);
    internal_static_substrait_Expression_MaskExpression_MapSelect_MapKey_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_substrait_Expression_MaskExpression_MapSelect_MapKey_descriptor,
        new java.lang.String[] { "MapKey", });
    internal_static_substrait_Expression_MaskExpression_MapSelect_MapKeyExpression_descriptor =
      internal_static_substrait_Expression_MaskExpression_MapSelect_descriptor.getNestedTypes().get(1);
    internal_static_substrait_Expression_MaskExpression_MapSelect_MapKeyExpression_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_substrait_Expression_MaskExpression_MapSelect_MapKeyExpression_descriptor,
        new java.lang.String[] { "MapKeyExpression", });
    internal_static_substrait_Expression_FieldReference_descriptor =
      internal_static_substrait_Expression_descriptor.getNestedTypes().get(12);
    internal_static_substrait_Expression_FieldReference_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_substrait_Expression_FieldReference_descriptor,
        new java.lang.String[] { "DirectReference", "MaskedReference", "Expression", "RootReference", "ReferenceType", "RootType", });
    internal_static_substrait_Expression_FieldReference_RootReference_descriptor =
      internal_static_substrait_Expression_FieldReference_descriptor.getNestedTypes().get(0);
    internal_static_substrait_Expression_FieldReference_RootReference_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_substrait_Expression_FieldReference_RootReference_descriptor,
        new java.lang.String[] { });
    internal_static_substrait_SortField_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_substrait_SortField_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_substrait_SortField_descriptor,
        new java.lang.String[] { "Expr", "Direction", "ComparisonFunctionReference", "SortKind", });
    internal_static_substrait_AggregateFunction_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_substrait_AggregateFunction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_substrait_AggregateFunction_descriptor,
        new java.lang.String[] { "FunctionReference", "Args", "Sorts", "Phase", "OutputType", });
    io.substrait.proto.TypeOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
