// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: substrait/relations.proto

package io.substrait.proto;

public interface ExtensionLeafRelOrBuilder extends
    // @@protoc_insertion_point(interface_extends:substrait.ExtensionLeafRel)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.substrait.RelCommon common = 1;</code>
   * @return Whether the common field is set.
   */
  boolean hasCommon();
  /**
   * <code>.substrait.RelCommon common = 1;</code>
   * @return The common.
   */
  io.substrait.proto.RelCommon getCommon();
  /**
   * <code>.substrait.RelCommon common = 1;</code>
   */
  io.substrait.proto.RelCommonOrBuilder getCommonOrBuilder();

  /**
   * <code>.google.protobuf.Any detail = 2;</code>
   * @return Whether the detail field is set.
   */
  boolean hasDetail();
  /**
   * <code>.google.protobuf.Any detail = 2;</code>
   * @return The detail.
   */
  com.google.protobuf.Any getDetail();
  /**
   * <code>.google.protobuf.Any detail = 2;</code>
   */
  com.google.protobuf.AnyOrBuilder getDetailOrBuilder();
}
