// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: substrait/relations.proto

package io.substrait.proto;

public interface ExtensionMultiRelOrBuilder extends
    // @@protoc_insertion_point(interface_extends:substrait.ExtensionMultiRel)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.substrait.RelCommon common = 1;</code>
   * @return Whether the common field is set.
   */
  boolean hasCommon();
  /**
   * <code>.substrait.RelCommon common = 1;</code>
   * @return The common.
   */
  io.substrait.proto.RelCommon getCommon();
  /**
   * <code>.substrait.RelCommon common = 1;</code>
   */
  io.substrait.proto.RelCommonOrBuilder getCommonOrBuilder();

  /**
   * <code>repeated .substrait.Rel inputs = 2;</code>
   */
  java.util.List<io.substrait.proto.Rel> 
      getInputsList();
  /**
   * <code>repeated .substrait.Rel inputs = 2;</code>
   */
  io.substrait.proto.Rel getInputs(int index);
  /**
   * <code>repeated .substrait.Rel inputs = 2;</code>
   */
  int getInputsCount();
  /**
   * <code>repeated .substrait.Rel inputs = 2;</code>
   */
  java.util.List<? extends io.substrait.proto.RelOrBuilder> 
      getInputsOrBuilderList();
  /**
   * <code>repeated .substrait.Rel inputs = 2;</code>
   */
  io.substrait.proto.RelOrBuilder getInputsOrBuilder(
      int index);

  /**
   * <code>.google.protobuf.Any detail = 3;</code>
   * @return Whether the detail field is set.
   */
  boolean hasDetail();
  /**
   * <code>.google.protobuf.Any detail = 3;</code>
   * @return The detail.
   */
  com.google.protobuf.Any getDetail();
  /**
   * <code>.google.protobuf.Any detail = 3;</code>
   */
  com.google.protobuf.AnyOrBuilder getDetailOrBuilder();
}
