// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: substrait/relations.proto

package io.substrait.proto;

public interface FilterRelOrBuilder extends
    // @@protoc_insertion_point(interface_extends:substrait.FilterRel)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.substrait.RelCommon common = 1;</code>
   * @return Whether the common field is set.
   */
  boolean hasCommon();
  /**
   * <code>.substrait.RelCommon common = 1;</code>
   * @return The common.
   */
  io.substrait.proto.RelCommon getCommon();
  /**
   * <code>.substrait.RelCommon common = 1;</code>
   */
  io.substrait.proto.RelCommonOrBuilder getCommonOrBuilder();

  /**
   * <code>.substrait.Rel input = 2;</code>
   * @return Whether the input field is set.
   */
  boolean hasInput();
  /**
   * <code>.substrait.Rel input = 2;</code>
   * @return The input.
   */
  io.substrait.proto.Rel getInput();
  /**
   * <code>.substrait.Rel input = 2;</code>
   */
  io.substrait.proto.RelOrBuilder getInputOrBuilder();

  /**
   * <code>.substrait.Expression condition = 3;</code>
   * @return Whether the condition field is set.
   */
  boolean hasCondition();
  /**
   * <code>.substrait.Expression condition = 3;</code>
   * @return The condition.
   */
  io.substrait.proto.Expression getCondition();
  /**
   * <code>.substrait.Expression condition = 3;</code>
   */
  io.substrait.proto.ExpressionOrBuilder getConditionOrBuilder();

  /**
   * <code>.substrait.extensions.AdvancedExtension advanced_extension = 10;</code>
   * @return Whether the advancedExtension field is set.
   */
  boolean hasAdvancedExtension();
  /**
   * <code>.substrait.extensions.AdvancedExtension advanced_extension = 10;</code>
   * @return The advancedExtension.
   */
  io.substrait.proto.AdvancedExtension getAdvancedExtension();
  /**
   * <code>.substrait.extensions.AdvancedExtension advanced_extension = 10;</code>
   */
  io.substrait.proto.AdvancedExtensionOrBuilder getAdvancedExtensionOrBuilder();
}
