// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: substrait/relations.proto

package io.substrait.proto;

public interface ProjectRelOrBuilder extends
    // @@protoc_insertion_point(interface_extends:substrait.ProjectRel)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.substrait.RelCommon common = 1;</code>
   * @return Whether the common field is set.
   */
  boolean hasCommon();
  /**
   * <code>.substrait.RelCommon common = 1;</code>
   * @return The common.
   */
  io.substrait.proto.RelCommon getCommon();
  /**
   * <code>.substrait.RelCommon common = 1;</code>
   */
  io.substrait.proto.RelCommonOrBuilder getCommonOrBuilder();

  /**
   * <code>.substrait.Rel input = 2;</code>
   * @return Whether the input field is set.
   */
  boolean hasInput();
  /**
   * <code>.substrait.Rel input = 2;</code>
   * @return The input.
   */
  io.substrait.proto.Rel getInput();
  /**
   * <code>.substrait.Rel input = 2;</code>
   */
  io.substrait.proto.RelOrBuilder getInputOrBuilder();

  /**
   * <code>repeated .substrait.Expression expressions = 3;</code>
   */
  java.util.List<io.substrait.proto.Expression> 
      getExpressionsList();
  /**
   * <code>repeated .substrait.Expression expressions = 3;</code>
   */
  io.substrait.proto.Expression getExpressions(int index);
  /**
   * <code>repeated .substrait.Expression expressions = 3;</code>
   */
  int getExpressionsCount();
  /**
   * <code>repeated .substrait.Expression expressions = 3;</code>
   */
  java.util.List<? extends io.substrait.proto.ExpressionOrBuilder> 
      getExpressionsOrBuilderList();
  /**
   * <code>repeated .substrait.Expression expressions = 3;</code>
   */
  io.substrait.proto.ExpressionOrBuilder getExpressionsOrBuilder(
      int index);

  /**
   * <code>.substrait.extensions.AdvancedExtension advanced_extension = 10;</code>
   * @return Whether the advancedExtension field is set.
   */
  boolean hasAdvancedExtension();
  /**
   * <code>.substrait.extensions.AdvancedExtension advanced_extension = 10;</code>
   * @return The advancedExtension.
   */
  io.substrait.proto.AdvancedExtension getAdvancedExtension();
  /**
   * <code>.substrait.extensions.AdvancedExtension advanced_extension = 10;</code>
   */
  io.substrait.proto.AdvancedExtensionOrBuilder getAdvancedExtensionOrBuilder();
}
