// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: substrait/relations.proto

package io.substrait.proto;

public final class Relations {
  private Relations() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_substrait_RelCommon_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_substrait_RelCommon_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_substrait_RelCommon_Direct_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_substrait_RelCommon_Direct_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_substrait_RelCommon_Emit_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_substrait_RelCommon_Emit_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_substrait_RelCommon_Hint_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_substrait_RelCommon_Hint_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_substrait_RelCommon_Hint_Stats_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_substrait_RelCommon_Hint_Stats_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_substrait_RelCommon_Hint_RuntimeConstraint_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_substrait_RelCommon_Hint_RuntimeConstraint_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_substrait_ReadRel_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_substrait_ReadRel_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_substrait_ReadRel_NamedTable_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_substrait_ReadRel_NamedTable_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_substrait_ReadRel_VirtualTable_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_substrait_ReadRel_VirtualTable_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_substrait_ReadRel_ExtensionTable_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_substrait_ReadRel_ExtensionTable_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_substrait_ReadRel_LocalFiles_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_substrait_ReadRel_LocalFiles_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_substrait_ReadRel_LocalFiles_FileOrFiles_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_substrait_ReadRel_LocalFiles_FileOrFiles_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_substrait_ProjectRel_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_substrait_ProjectRel_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_substrait_JoinRel_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_substrait_JoinRel_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_substrait_FetchRel_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_substrait_FetchRel_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_substrait_AggregateRel_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_substrait_AggregateRel_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_substrait_AggregateRel_Grouping_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_substrait_AggregateRel_Grouping_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_substrait_AggregateRel_Measure_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_substrait_AggregateRel_Measure_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_substrait_SortRel_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_substrait_SortRel_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_substrait_FilterRel_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_substrait_FilterRel_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_substrait_SetRel_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_substrait_SetRel_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_substrait_ExtensionSingleRel_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_substrait_ExtensionSingleRel_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_substrait_ExtensionLeafRel_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_substrait_ExtensionLeafRel_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_substrait_ExtensionMultiRel_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_substrait_ExtensionMultiRel_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_substrait_RelRoot_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_substrait_RelRoot_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_substrait_Rel_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_substrait_Rel_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031substrait/relations.proto\022\tsubstrait\032\024" +
      "substrait/type.proto\032\032substrait/expressi" +
      "on.proto\032%substrait/extensions/extension" +
      "s.proto\032\031google/protobuf/any.proto\"\231\005\n\tR" +
      "elCommon\022-\n\006direct\030\001 \001(\0132\033.substrait.Rel" +
      "Common.DirectH\000\022)\n\004emit\030\002 \001(\0132\031.substrai" +
      "t.RelCommon.EmitH\000\022\'\n\004hint\030\003 \001(\0132\031.subst" +
      "rait.RelCommon.Hint\022C\n\022advanced_extensio" +
      "n\030\004 \001(\0132\'.substrait.extensions.AdvancedE" +
      "xtension\032\010\n\006Direct\032\036\n\004Emit\022\026\n\016output_map" +
      "ping\030\001 \003(\005\032\214\003\n\004Hint\022.\n\005stats\030\001 \001(\0132\037.sub" +
      "strait.RelCommon.Hint.Stats\022?\n\nconstrain" +
      "t\030\002 \001(\0132+.substrait.RelCommon.Hint.Runti" +
      "meConstraint\022C\n\022advanced_extension\030\n \001(\013" +
      "2\'.substrait.extensions.AdvancedExtensio" +
      "n\032t\n\005Stats\022\021\n\trow_count\030\001 \001(\001\022\023\n\013record_" +
      "size\030\002 \001(\001\022C\n\022advanced_extension\030\n \001(\0132\'" +
      ".substrait.extensions.AdvancedExtension\032" +
      "X\n\021RuntimeConstraint\022C\n\022advanced_extensi" +
      "on\030\n \001(\0132\'.substrait.extensions.Advanced" +
      "ExtensionB\013\n\temit_kind\"\227\t\n\007ReadRel\022$\n\006co" +
      "mmon\030\001 \001(\0132\024.substrait.RelCommon\022+\n\013base" +
      "_schema\030\002 \001(\0132\026.substrait.NamedStruct\022%\n" +
      "\006filter\030\003 \001(\0132\025.substrait.Expression\0228\n\n" +
      "projection\030\004 \001(\0132$.substrait.Expression." +
      "MaskExpression\022C\n\022advanced_extension\030\n \001" +
      "(\0132\'.substrait.extensions.AdvancedExtens" +
      "ion\0228\n\rvirtual_table\030\005 \001(\0132\037.substrait.R" +
      "eadRel.VirtualTableH\000\0224\n\013local_files\030\006 \001" +
      "(\0132\035.substrait.ReadRel.LocalFilesH\000\0224\n\013n" +
      "amed_table\030\007 \001(\0132\035.substrait.ReadRel.Nam" +
      "edTableH\000\022<\n\017extension_table\030\010 \001(\0132!.sub" +
      "strait.ReadRel.ExtensionTableH\000\032`\n\nNamed" +
      "Table\022\r\n\005names\030\001 \003(\t\022C\n\022advanced_extensi" +
      "on\030\n \001(\0132\'.substrait.extensions.Advanced" +
      "Extension\032D\n\014VirtualTable\0224\n\006values\030\001 \003(" +
      "\0132$.substrait.Expression.Literal.Struct\032" +
      "6\n\016ExtensionTable\022$\n\006detail\030\001 \001(\0132\024.goog" +
      "le.protobuf.Any\032\301\003\n\nLocalFiles\0228\n\005items\030" +
      "\001 \003(\0132).substrait.ReadRel.LocalFiles.Fil" +
      "eOrFiles\022C\n\022advanced_extension\030\n \001(\0132\'.s" +
      "ubstrait.extensions.AdvancedExtension\032\263\002" +
      "\n\013FileOrFiles\022\022\n\010uri_path\030\001 \001(\tH\000\022\027\n\ruri" +
      "_path_glob\030\002 \001(\tH\000\022\022\n\010uri_file\030\003 \001(\tH\000\022\024" +
      "\n\nuri_folder\030\004 \001(\tH\000\022D\n\006format\030\005 \001(\01624.s" +
      "ubstrait.ReadRel.LocalFiles.FileOrFiles." +
      "FileFormat\022\027\n\017partition_index\030\006 \001(\004\022\r\n\005s" +
      "tart\030\007 \001(\004\022\016\n\006length\030\010 \001(\004\"B\n\nFileFormat" +
      "\022\033\n\027FILE_FORMAT_UNSPECIFIED\020\000\022\027\n\023FILE_FO" +
      "RMAT_PARQUET\020\001B\013\n\tpath_typeB\013\n\tread_type" +
      "\"\302\001\n\nProjectRel\022$\n\006common\030\001 \001(\0132\024.substr" +
      "ait.RelCommon\022\035\n\005input\030\002 \001(\0132\016.substrait" +
      ".Rel\022*\n\013expressions\030\003 \003(\0132\025.substrait.Ex" +
      "pression\022C\n\022advanced_extension\030\n \001(\0132\'.s" +
      "ubstrait.extensions.AdvancedExtension\"\333\003" +
      "\n\007JoinRel\022$\n\006common\030\001 \001(\0132\024.substrait.Re" +
      "lCommon\022\034\n\004left\030\002 \001(\0132\016.substrait.Rel\022\035\n" +
      "\005right\030\003 \001(\0132\016.substrait.Rel\022)\n\nexpressi" +
      "on\030\004 \001(\0132\025.substrait.Expression\022/\n\020post_" +
      "join_filter\030\005 \001(\0132\025.substrait.Expression" +
      "\022)\n\004type\030\006 \001(\0162\033.substrait.JoinRel.JoinT" +
      "ype\022C\n\022advanced_extension\030\n \001(\0132\'.substr" +
      "ait.extensions.AdvancedExtension\"\240\001\n\010Joi" +
      "nType\022\031\n\025JOIN_TYPE_UNSPECIFIED\020\000\022\023\n\017JOIN" +
      "_TYPE_INNER\020\001\022\023\n\017JOIN_TYPE_OUTER\020\002\022\022\n\016JO" +
      "IN_TYPE_LEFT\020\003\022\023\n\017JOIN_TYPE_RIGHT\020\004\022\022\n\016J" +
      "OIN_TYPE_SEMI\020\005\022\022\n\016JOIN_TYPE_ANTI\020\006\"\263\001\n\010" +
      "FetchRel\022$\n\006common\030\001 \001(\0132\024.substrait.Rel" +
      "Common\022\035\n\005input\030\002 \001(\0132\016.substrait.Rel\022\016\n" +
      "\006offset\030\003 \001(\003\022\r\n\005count\030\004 \001(\003\022C\n\022advanced" +
      "_extension\030\n \001(\0132\'.substrait.extensions." +
      "AdvancedExtension\"\242\003\n\014AggregateRel\022$\n\006co" +
      "mmon\030\001 \001(\0132\024.substrait.RelCommon\022\035\n\005inpu" +
      "t\030\002 \001(\0132\016.substrait.Rel\0223\n\tgroupings\030\003 \003" +
      "(\0132 .substrait.AggregateRel.Grouping\0221\n\010" +
      "measures\030\004 \003(\0132\037.substrait.AggregateRel." +
      "Measure\022C\n\022advanced_extension\030\n \001(\0132\'.su" +
      "bstrait.extensions.AdvancedExtension\032?\n\010" +
      "Grouping\0223\n\024grouping_expressions\030\001 \003(\0132\025" +
      ".substrait.Expression\032_\n\007Measure\022-\n\007meas" +
      "ure\030\001 \001(\0132\034.substrait.AggregateFunction\022" +
      "%\n\006filter\030\002 \001(\0132\025.substrait.Expression\"\270" +
      "\001\n\007SortRel\022$\n\006common\030\001 \001(\0132\024.substrait.R" +
      "elCommon\022\035\n\005input\030\002 \001(\0132\016.substrait.Rel\022" +
      "#\n\005sorts\030\003 \003(\0132\024.substrait.SortField\022C\n\022" +
      "advanced_extension\030\n \001(\0132\'.substrait.ext" +
      "ensions.AdvancedExtension\"\277\001\n\tFilterRel\022" +
      "$\n\006common\030\001 \001(\0132\024.substrait.RelCommon\022\035\n" +
      "\005input\030\002 \001(\0132\016.substrait.Rel\022(\n\tconditio" +
      "n\030\003 \001(\0132\025.substrait.Expression\022C\n\022advanc" +
      "ed_extension\030\n \001(\0132\'.substrait.extension" +
      "s.AdvancedExtension\"\203\003\n\006SetRel\022$\n\006common" +
      "\030\001 \001(\0132\024.substrait.RelCommon\022\036\n\006inputs\030\002" +
      " \003(\0132\016.substrait.Rel\022#\n\002op\030\003 \001(\0162\027.subst" +
      "rait.SetRel.SetOp\022C\n\022advanced_extension\030" +
      "\n \001(\0132\'.substrait.extensions.AdvancedExt" +
      "ension\"\310\001\n\005SetOp\022\026\n\022SET_OP_UNSPECIFIED\020\000" +
      "\022\030\n\024SET_OP_MINUS_PRIMARY\020\001\022\031\n\025SET_OP_MIN" +
      "US_MULTISET\020\002\022\037\n\033SET_OP_INTERSECTION_PRI" +
      "MARY\020\003\022 \n\034SET_OP_INTERSECTION_MULTISET\020\004" +
      "\022\031\n\025SET_OP_UNION_DISTINCT\020\005\022\024\n\020SET_OP_UN" +
      "ION_ALL\020\006\"\177\n\022ExtensionSingleRel\022$\n\006commo" +
      "n\030\001 \001(\0132\024.substrait.RelCommon\022\035\n\005input\030\002" +
      " \001(\0132\016.substrait.Rel\022$\n\006detail\030\003 \001(\0132\024.g" +
      "oogle.protobuf.Any\"^\n\020ExtensionLeafRel\022$" +
      "\n\006common\030\001 \001(\0132\024.substrait.RelCommon\022$\n\006" +
      "detail\030\002 \001(\0132\024.google.protobuf.Any\"\177\n\021Ex" +
      "tensionMultiRel\022$\n\006common\030\001 \001(\0132\024.substr" +
      "ait.RelCommon\022\036\n\006inputs\030\002 \003(\0132\016.substrai" +
      "t.Rel\022$\n\006detail\030\003 \001(\0132\024.google.protobuf." +
      "Any\"7\n\007RelRoot\022\035\n\005input\030\001 \001(\0132\016.substrai" +
      "t.Rel\022\r\n\005names\030\002 \003(\t\"\360\003\n\003Rel\022\"\n\004read\030\001 \001" +
      "(\0132\022.substrait.ReadRelH\000\022&\n\006filter\030\002 \001(\013" +
      "2\024.substrait.FilterRelH\000\022$\n\005fetch\030\003 \001(\0132" +
      "\023.substrait.FetchRelH\000\022,\n\taggregate\030\004 \001(" +
      "\0132\027.substrait.AggregateRelH\000\022\"\n\004sort\030\005 \001" +
      "(\0132\022.substrait.SortRelH\000\022\"\n\004join\030\006 \001(\0132\022" +
      ".substrait.JoinRelH\000\022(\n\007project\030\007 \001(\0132\025." +
      "substrait.ProjectRelH\000\022 \n\003set\030\010 \001(\0132\021.su" +
      "bstrait.SetRelH\000\0229\n\020extension_single\030\t \001" +
      "(\0132\035.substrait.ExtensionSingleRelH\000\0227\n\017e" +
      "xtension_multi\030\n \001(\0132\034.substrait.Extensi" +
      "onMultiRelH\000\0225\n\016extension_leaf\030\013 \001(\0132\033.s" +
      "ubstrait.ExtensionLeafRelH\000B\n\n\010rel_typeB" +
      "+\n\022io.substrait.protoP\001\252\002\022Substrait.Prot" +
      "obufb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.substrait.proto.TypeOuterClass.getDescriptor(),
          io.substrait.proto.ExpressionOuterClass.getDescriptor(),
          io.substrait.proto.Extensions.getDescriptor(),
          com.google.protobuf.AnyProto.getDescriptor(),
        });
    internal_static_substrait_RelCommon_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_substrait_RelCommon_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_substrait_RelCommon_descriptor,
        new java.lang.String[] { "Direct", "Emit", "Hint", "AdvancedExtension", "EmitKind", });
    internal_static_substrait_RelCommon_Direct_descriptor =
      internal_static_substrait_RelCommon_descriptor.getNestedTypes().get(0);
    internal_static_substrait_RelCommon_Direct_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_substrait_RelCommon_Direct_descriptor,
        new java.lang.String[] { });
    internal_static_substrait_RelCommon_Emit_descriptor =
      internal_static_substrait_RelCommon_descriptor.getNestedTypes().get(1);
    internal_static_substrait_RelCommon_Emit_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_substrait_RelCommon_Emit_descriptor,
        new java.lang.String[] { "OutputMapping", });
    internal_static_substrait_RelCommon_Hint_descriptor =
      internal_static_substrait_RelCommon_descriptor.getNestedTypes().get(2);
    internal_static_substrait_RelCommon_Hint_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_substrait_RelCommon_Hint_descriptor,
        new java.lang.String[] { "Stats", "Constraint", "AdvancedExtension", });
    internal_static_substrait_RelCommon_Hint_Stats_descriptor =
      internal_static_substrait_RelCommon_Hint_descriptor.getNestedTypes().get(0);
    internal_static_substrait_RelCommon_Hint_Stats_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_substrait_RelCommon_Hint_Stats_descriptor,
        new java.lang.String[] { "RowCount", "RecordSize", "AdvancedExtension", });
    internal_static_substrait_RelCommon_Hint_RuntimeConstraint_descriptor =
      internal_static_substrait_RelCommon_Hint_descriptor.getNestedTypes().get(1);
    internal_static_substrait_RelCommon_Hint_RuntimeConstraint_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_substrait_RelCommon_Hint_RuntimeConstraint_descriptor,
        new java.lang.String[] { "AdvancedExtension", });
    internal_static_substrait_ReadRel_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_substrait_ReadRel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_substrait_ReadRel_descriptor,
        new java.lang.String[] { "Common", "BaseSchema", "Filter", "Projection", "AdvancedExtension", "VirtualTable", "LocalFiles", "NamedTable", "ExtensionTable", "ReadType", });
    internal_static_substrait_ReadRel_NamedTable_descriptor =
      internal_static_substrait_ReadRel_descriptor.getNestedTypes().get(0);
    internal_static_substrait_ReadRel_NamedTable_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_substrait_ReadRel_NamedTable_descriptor,
        new java.lang.String[] { "Names", "AdvancedExtension", });
    internal_static_substrait_ReadRel_VirtualTable_descriptor =
      internal_static_substrait_ReadRel_descriptor.getNestedTypes().get(1);
    internal_static_substrait_ReadRel_VirtualTable_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_substrait_ReadRel_VirtualTable_descriptor,
        new java.lang.String[] { "Values", });
    internal_static_substrait_ReadRel_ExtensionTable_descriptor =
      internal_static_substrait_ReadRel_descriptor.getNestedTypes().get(2);
    internal_static_substrait_ReadRel_ExtensionTable_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_substrait_ReadRel_ExtensionTable_descriptor,
        new java.lang.String[] { "Detail", });
    internal_static_substrait_ReadRel_LocalFiles_descriptor =
      internal_static_substrait_ReadRel_descriptor.getNestedTypes().get(3);
    internal_static_substrait_ReadRel_LocalFiles_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_substrait_ReadRel_LocalFiles_descriptor,
        new java.lang.String[] { "Items", "AdvancedExtension", });
    internal_static_substrait_ReadRel_LocalFiles_FileOrFiles_descriptor =
      internal_static_substrait_ReadRel_LocalFiles_descriptor.getNestedTypes().get(0);
    internal_static_substrait_ReadRel_LocalFiles_FileOrFiles_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_substrait_ReadRel_LocalFiles_FileOrFiles_descriptor,
        new java.lang.String[] { "UriPath", "UriPathGlob", "UriFile", "UriFolder", "Format", "PartitionIndex", "Start", "Length", "PathType", });
    internal_static_substrait_ProjectRel_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_substrait_ProjectRel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_substrait_ProjectRel_descriptor,
        new java.lang.String[] { "Common", "Input", "Expressions", "AdvancedExtension", });
    internal_static_substrait_JoinRel_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_substrait_JoinRel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_substrait_JoinRel_descriptor,
        new java.lang.String[] { "Common", "Left", "Right", "Expression", "PostJoinFilter", "Type", "AdvancedExtension", });
    internal_static_substrait_FetchRel_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_substrait_FetchRel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_substrait_FetchRel_descriptor,
        new java.lang.String[] { "Common", "Input", "Offset", "Count", "AdvancedExtension", });
    internal_static_substrait_AggregateRel_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_substrait_AggregateRel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_substrait_AggregateRel_descriptor,
        new java.lang.String[] { "Common", "Input", "Groupings", "Measures", "AdvancedExtension", });
    internal_static_substrait_AggregateRel_Grouping_descriptor =
      internal_static_substrait_AggregateRel_descriptor.getNestedTypes().get(0);
    internal_static_substrait_AggregateRel_Grouping_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_substrait_AggregateRel_Grouping_descriptor,
        new java.lang.String[] { "GroupingExpressions", });
    internal_static_substrait_AggregateRel_Measure_descriptor =
      internal_static_substrait_AggregateRel_descriptor.getNestedTypes().get(1);
    internal_static_substrait_AggregateRel_Measure_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_substrait_AggregateRel_Measure_descriptor,
        new java.lang.String[] { "Measure", "Filter", });
    internal_static_substrait_SortRel_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_substrait_SortRel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_substrait_SortRel_descriptor,
        new java.lang.String[] { "Common", "Input", "Sorts", "AdvancedExtension", });
    internal_static_substrait_FilterRel_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_substrait_FilterRel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_substrait_FilterRel_descriptor,
        new java.lang.String[] { "Common", "Input", "Condition", "AdvancedExtension", });
    internal_static_substrait_SetRel_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_substrait_SetRel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_substrait_SetRel_descriptor,
        new java.lang.String[] { "Common", "Inputs", "Op", "AdvancedExtension", });
    internal_static_substrait_ExtensionSingleRel_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_substrait_ExtensionSingleRel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_substrait_ExtensionSingleRel_descriptor,
        new java.lang.String[] { "Common", "Input", "Detail", });
    internal_static_substrait_ExtensionLeafRel_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_substrait_ExtensionLeafRel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_substrait_ExtensionLeafRel_descriptor,
        new java.lang.String[] { "Common", "Detail", });
    internal_static_substrait_ExtensionMultiRel_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_substrait_ExtensionMultiRel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_substrait_ExtensionMultiRel_descriptor,
        new java.lang.String[] { "Common", "Inputs", "Detail", });
    internal_static_substrait_RelRoot_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_substrait_RelRoot_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_substrait_RelRoot_descriptor,
        new java.lang.String[] { "Input", "Names", });
    internal_static_substrait_Rel_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_substrait_Rel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_substrait_Rel_descriptor,
        new java.lang.String[] { "Read", "Filter", "Fetch", "Aggregate", "Sort", "Join", "Project", "Set", "ExtensionSingle", "ExtensionMulti", "ExtensionLeaf", "RelType", });
    io.substrait.proto.TypeOuterClass.getDescriptor();
    io.substrait.proto.ExpressionOuterClass.getDescriptor();
    io.substrait.proto.Extensions.getDescriptor();
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
