// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: substrait/expression.proto

package io.substrait.proto;

/**
 * Protobuf type {@code substrait.SortField}
 */
public final class SortField extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:substrait.SortField)
    SortFieldOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SortField.newBuilder() to construct.
  private SortField(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SortField() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SortField();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SortField(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            io.substrait.proto.Expression.Builder subBuilder = null;
            if (expr_ != null) {
              subBuilder = expr_.toBuilder();
            }
            expr_ = input.readMessage(io.substrait.proto.Expression.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(expr_);
              expr_ = subBuilder.buildPartial();
            }

            break;
          }
          case 16: {
            int rawValue = input.readEnum();
            sortKindCase_ = 2;
            sortKind_ = rawValue;
            break;
          }
          case 24: {
            sortKindCase_ = 3;
            sortKind_ = input.readUInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.substrait.proto.ExpressionOuterClass.internal_static_substrait_SortField_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.substrait.proto.ExpressionOuterClass.internal_static_substrait_SortField_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.substrait.proto.SortField.class, io.substrait.proto.SortField.Builder.class);
  }

  /**
   * Protobuf enum {@code substrait.SortField.SortDirection}
   */
  public enum SortDirection
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>SORT_DIRECTION_UNSPECIFIED = 0;</code>
     */
    SORT_DIRECTION_UNSPECIFIED(0),
    /**
     * <code>SORT_DIRECTION_ASC_NULLS_FIRST = 1;</code>
     */
    SORT_DIRECTION_ASC_NULLS_FIRST(1),
    /**
     * <code>SORT_DIRECTION_ASC_NULLS_LAST = 2;</code>
     */
    SORT_DIRECTION_ASC_NULLS_LAST(2),
    /**
     * <code>SORT_DIRECTION_DESC_NULLS_FIRST = 3;</code>
     */
    SORT_DIRECTION_DESC_NULLS_FIRST(3),
    /**
     * <code>SORT_DIRECTION_DESC_NULLS_LAST = 4;</code>
     */
    SORT_DIRECTION_DESC_NULLS_LAST(4),
    /**
     * <code>SORT_DIRECTION_CLUSTERED = 5;</code>
     */
    SORT_DIRECTION_CLUSTERED(5),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>SORT_DIRECTION_UNSPECIFIED = 0;</code>
     */
    public static final int SORT_DIRECTION_UNSPECIFIED_VALUE = 0;
    /**
     * <code>SORT_DIRECTION_ASC_NULLS_FIRST = 1;</code>
     */
    public static final int SORT_DIRECTION_ASC_NULLS_FIRST_VALUE = 1;
    /**
     * <code>SORT_DIRECTION_ASC_NULLS_LAST = 2;</code>
     */
    public static final int SORT_DIRECTION_ASC_NULLS_LAST_VALUE = 2;
    /**
     * <code>SORT_DIRECTION_DESC_NULLS_FIRST = 3;</code>
     */
    public static final int SORT_DIRECTION_DESC_NULLS_FIRST_VALUE = 3;
    /**
     * <code>SORT_DIRECTION_DESC_NULLS_LAST = 4;</code>
     */
    public static final int SORT_DIRECTION_DESC_NULLS_LAST_VALUE = 4;
    /**
     * <code>SORT_DIRECTION_CLUSTERED = 5;</code>
     */
    public static final int SORT_DIRECTION_CLUSTERED_VALUE = 5;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static SortDirection valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static SortDirection forNumber(int value) {
      switch (value) {
        case 0: return SORT_DIRECTION_UNSPECIFIED;
        case 1: return SORT_DIRECTION_ASC_NULLS_FIRST;
        case 2: return SORT_DIRECTION_ASC_NULLS_LAST;
        case 3: return SORT_DIRECTION_DESC_NULLS_FIRST;
        case 4: return SORT_DIRECTION_DESC_NULLS_LAST;
        case 5: return SORT_DIRECTION_CLUSTERED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<SortDirection>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        SortDirection> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<SortDirection>() {
            public SortDirection findValueByNumber(int number) {
              return SortDirection.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return io.substrait.proto.SortField.getDescriptor().getEnumTypes().get(0);
    }

    private static final SortDirection[] VALUES = values();

    public static SortDirection valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private SortDirection(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:substrait.SortField.SortDirection)
  }

  private int sortKindCase_ = 0;
  private java.lang.Object sortKind_;
  public enum SortKindCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    DIRECTION(2),
    COMPARISON_FUNCTION_REFERENCE(3),
    SORTKIND_NOT_SET(0);
    private final int value;
    private SortKindCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static SortKindCase valueOf(int value) {
      return forNumber(value);
    }

    public static SortKindCase forNumber(int value) {
      switch (value) {
        case 2: return DIRECTION;
        case 3: return COMPARISON_FUNCTION_REFERENCE;
        case 0: return SORTKIND_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public SortKindCase
  getSortKindCase() {
    return SortKindCase.forNumber(
        sortKindCase_);
  }

  public static final int EXPR_FIELD_NUMBER = 1;
  private io.substrait.proto.Expression expr_;
  /**
   * <code>.substrait.Expression expr = 1;</code>
   * @return Whether the expr field is set.
   */
  @java.lang.Override
  public boolean hasExpr() {
    return expr_ != null;
  }
  /**
   * <code>.substrait.Expression expr = 1;</code>
   * @return The expr.
   */
  @java.lang.Override
  public io.substrait.proto.Expression getExpr() {
    return expr_ == null ? io.substrait.proto.Expression.getDefaultInstance() : expr_;
  }
  /**
   * <code>.substrait.Expression expr = 1;</code>
   */
  @java.lang.Override
  public io.substrait.proto.ExpressionOrBuilder getExprOrBuilder() {
    return getExpr();
  }

  public static final int DIRECTION_FIELD_NUMBER = 2;
  /**
   * <code>.substrait.SortField.SortDirection direction = 2;</code>
   * @return The enum numeric value on the wire for direction.
   */
  public int getDirectionValue() {
    if (sortKindCase_ == 2) {
      return (java.lang.Integer) sortKind_;
    }
    return 0;
  }
  /**
   * <code>.substrait.SortField.SortDirection direction = 2;</code>
   * @return The direction.
   */
  public io.substrait.proto.SortField.SortDirection getDirection() {
    if (sortKindCase_ == 2) {
      @SuppressWarnings("deprecation")
      io.substrait.proto.SortField.SortDirection result = io.substrait.proto.SortField.SortDirection.valueOf(
          (java.lang.Integer) sortKind_);
      return result == null ? io.substrait.proto.SortField.SortDirection.UNRECOGNIZED : result;
    }
    return io.substrait.proto.SortField.SortDirection.SORT_DIRECTION_UNSPECIFIED;
  }

  public static final int COMPARISON_FUNCTION_REFERENCE_FIELD_NUMBER = 3;
  /**
   * <code>uint32 comparison_function_reference = 3;</code>
   * @return The comparisonFunctionReference.
   */
  @java.lang.Override
  public int getComparisonFunctionReference() {
    if (sortKindCase_ == 3) {
      return (java.lang.Integer) sortKind_;
    }
    return 0;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (expr_ != null) {
      output.writeMessage(1, getExpr());
    }
    if (sortKindCase_ == 2) {
      output.writeEnum(2, ((java.lang.Integer) sortKind_));
    }
    if (sortKindCase_ == 3) {
      output.writeUInt32(
          3, (int)((java.lang.Integer) sortKind_));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (expr_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getExpr());
    }
    if (sortKindCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, ((java.lang.Integer) sortKind_));
    }
    if (sortKindCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(
            3, (int)((java.lang.Integer) sortKind_));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.substrait.proto.SortField)) {
      return super.equals(obj);
    }
    io.substrait.proto.SortField other = (io.substrait.proto.SortField) obj;

    if (hasExpr() != other.hasExpr()) return false;
    if (hasExpr()) {
      if (!getExpr()
          .equals(other.getExpr())) return false;
    }
    if (!getSortKindCase().equals(other.getSortKindCase())) return false;
    switch (sortKindCase_) {
      case 2:
        if (getDirectionValue()
            != other.getDirectionValue()) return false;
        break;
      case 3:
        if (getComparisonFunctionReference()
            != other.getComparisonFunctionReference()) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasExpr()) {
      hash = (37 * hash) + EXPR_FIELD_NUMBER;
      hash = (53 * hash) + getExpr().hashCode();
    }
    switch (sortKindCase_) {
      case 2:
        hash = (37 * hash) + DIRECTION_FIELD_NUMBER;
        hash = (53 * hash) + getDirectionValue();
        break;
      case 3:
        hash = (37 * hash) + COMPARISON_FUNCTION_REFERENCE_FIELD_NUMBER;
        hash = (53 * hash) + getComparisonFunctionReference();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.substrait.proto.SortField parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.substrait.proto.SortField parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.substrait.proto.SortField parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.substrait.proto.SortField parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.substrait.proto.SortField parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.substrait.proto.SortField parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.substrait.proto.SortField parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.substrait.proto.SortField parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.substrait.proto.SortField parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.substrait.proto.SortField parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.substrait.proto.SortField parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.substrait.proto.SortField parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.substrait.proto.SortField prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code substrait.SortField}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:substrait.SortField)
      io.substrait.proto.SortFieldOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.substrait.proto.ExpressionOuterClass.internal_static_substrait_SortField_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.substrait.proto.ExpressionOuterClass.internal_static_substrait_SortField_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.substrait.proto.SortField.class, io.substrait.proto.SortField.Builder.class);
    }

    // Construct using io.substrait.proto.SortField.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (exprBuilder_ == null) {
        expr_ = null;
      } else {
        expr_ = null;
        exprBuilder_ = null;
      }
      sortKindCase_ = 0;
      sortKind_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.substrait.proto.ExpressionOuterClass.internal_static_substrait_SortField_descriptor;
    }

    @java.lang.Override
    public io.substrait.proto.SortField getDefaultInstanceForType() {
      return io.substrait.proto.SortField.getDefaultInstance();
    }

    @java.lang.Override
    public io.substrait.proto.SortField build() {
      io.substrait.proto.SortField result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.substrait.proto.SortField buildPartial() {
      io.substrait.proto.SortField result = new io.substrait.proto.SortField(this);
      if (exprBuilder_ == null) {
        result.expr_ = expr_;
      } else {
        result.expr_ = exprBuilder_.build();
      }
      if (sortKindCase_ == 2) {
        result.sortKind_ = sortKind_;
      }
      if (sortKindCase_ == 3) {
        result.sortKind_ = sortKind_;
      }
      result.sortKindCase_ = sortKindCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.substrait.proto.SortField) {
        return mergeFrom((io.substrait.proto.SortField)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.substrait.proto.SortField other) {
      if (other == io.substrait.proto.SortField.getDefaultInstance()) return this;
      if (other.hasExpr()) {
        mergeExpr(other.getExpr());
      }
      switch (other.getSortKindCase()) {
        case DIRECTION: {
          setDirectionValue(other.getDirectionValue());
          break;
        }
        case COMPARISON_FUNCTION_REFERENCE: {
          setComparisonFunctionReference(other.getComparisonFunctionReference());
          break;
        }
        case SORTKIND_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.substrait.proto.SortField parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.substrait.proto.SortField) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int sortKindCase_ = 0;
    private java.lang.Object sortKind_;
    public SortKindCase
        getSortKindCase() {
      return SortKindCase.forNumber(
          sortKindCase_);
    }

    public Builder clearSortKind() {
      sortKindCase_ = 0;
      sortKind_ = null;
      onChanged();
      return this;
    }


    private io.substrait.proto.Expression expr_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.substrait.proto.Expression, io.substrait.proto.Expression.Builder, io.substrait.proto.ExpressionOrBuilder> exprBuilder_;
    /**
     * <code>.substrait.Expression expr = 1;</code>
     * @return Whether the expr field is set.
     */
    public boolean hasExpr() {
      return exprBuilder_ != null || expr_ != null;
    }
    /**
     * <code>.substrait.Expression expr = 1;</code>
     * @return The expr.
     */
    public io.substrait.proto.Expression getExpr() {
      if (exprBuilder_ == null) {
        return expr_ == null ? io.substrait.proto.Expression.getDefaultInstance() : expr_;
      } else {
        return exprBuilder_.getMessage();
      }
    }
    /**
     * <code>.substrait.Expression expr = 1;</code>
     */
    public Builder setExpr(io.substrait.proto.Expression value) {
      if (exprBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        expr_ = value;
        onChanged();
      } else {
        exprBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.substrait.Expression expr = 1;</code>
     */
    public Builder setExpr(
        io.substrait.proto.Expression.Builder builderForValue) {
      if (exprBuilder_ == null) {
        expr_ = builderForValue.build();
        onChanged();
      } else {
        exprBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.substrait.Expression expr = 1;</code>
     */
    public Builder mergeExpr(io.substrait.proto.Expression value) {
      if (exprBuilder_ == null) {
        if (expr_ != null) {
          expr_ =
            io.substrait.proto.Expression.newBuilder(expr_).mergeFrom(value).buildPartial();
        } else {
          expr_ = value;
        }
        onChanged();
      } else {
        exprBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.substrait.Expression expr = 1;</code>
     */
    public Builder clearExpr() {
      if (exprBuilder_ == null) {
        expr_ = null;
        onChanged();
      } else {
        expr_ = null;
        exprBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.substrait.Expression expr = 1;</code>
     */
    public io.substrait.proto.Expression.Builder getExprBuilder() {
      
      onChanged();
      return getExprFieldBuilder().getBuilder();
    }
    /**
     * <code>.substrait.Expression expr = 1;</code>
     */
    public io.substrait.proto.ExpressionOrBuilder getExprOrBuilder() {
      if (exprBuilder_ != null) {
        return exprBuilder_.getMessageOrBuilder();
      } else {
        return expr_ == null ?
            io.substrait.proto.Expression.getDefaultInstance() : expr_;
      }
    }
    /**
     * <code>.substrait.Expression expr = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.substrait.proto.Expression, io.substrait.proto.Expression.Builder, io.substrait.proto.ExpressionOrBuilder> 
        getExprFieldBuilder() {
      if (exprBuilder_ == null) {
        exprBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.substrait.proto.Expression, io.substrait.proto.Expression.Builder, io.substrait.proto.ExpressionOrBuilder>(
                getExpr(),
                getParentForChildren(),
                isClean());
        expr_ = null;
      }
      return exprBuilder_;
    }

    /**
     * <code>.substrait.SortField.SortDirection direction = 2;</code>
     * @return The enum numeric value on the wire for direction.
     */
    @java.lang.Override
    public int getDirectionValue() {
      if (sortKindCase_ == 2) {
        return ((java.lang.Integer) sortKind_).intValue();
      }
      return 0;
    }
    /**
     * <code>.substrait.SortField.SortDirection direction = 2;</code>
     * @param value The enum numeric value on the wire for direction to set.
     * @return This builder for chaining.
     */
    public Builder setDirectionValue(int value) {
      sortKindCase_ = 2;
      sortKind_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.substrait.SortField.SortDirection direction = 2;</code>
     * @return The direction.
     */
    @java.lang.Override
    public io.substrait.proto.SortField.SortDirection getDirection() {
      if (sortKindCase_ == 2) {
        @SuppressWarnings("deprecation")
        io.substrait.proto.SortField.SortDirection result = io.substrait.proto.SortField.SortDirection.valueOf(
            (java.lang.Integer) sortKind_);
        return result == null ? io.substrait.proto.SortField.SortDirection.UNRECOGNIZED : result;
      }
      return io.substrait.proto.SortField.SortDirection.SORT_DIRECTION_UNSPECIFIED;
    }
    /**
     * <code>.substrait.SortField.SortDirection direction = 2;</code>
     * @param value The direction to set.
     * @return This builder for chaining.
     */
    public Builder setDirection(io.substrait.proto.SortField.SortDirection value) {
      if (value == null) {
        throw new NullPointerException();
      }
      sortKindCase_ = 2;
      sortKind_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.substrait.SortField.SortDirection direction = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDirection() {
      if (sortKindCase_ == 2) {
        sortKindCase_ = 0;
        sortKind_ = null;
        onChanged();
      }
      return this;
    }

    /**
     * <code>uint32 comparison_function_reference = 3;</code>
     * @return The comparisonFunctionReference.
     */
    public int getComparisonFunctionReference() {
      if (sortKindCase_ == 3) {
        return (java.lang.Integer) sortKind_;
      }
      return 0;
    }
    /**
     * <code>uint32 comparison_function_reference = 3;</code>
     * @param value The comparisonFunctionReference to set.
     * @return This builder for chaining.
     */
    public Builder setComparisonFunctionReference(int value) {
      sortKindCase_ = 3;
      sortKind_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 comparison_function_reference = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearComparisonFunctionReference() {
      if (sortKindCase_ == 3) {
        sortKindCase_ = 0;
        sortKind_ = null;
        onChanged();
      }
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:substrait.SortField)
  }

  // @@protoc_insertion_point(class_scope:substrait.SortField)
  private static final io.substrait.proto.SortField DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.substrait.proto.SortField();
  }

  public static io.substrait.proto.SortField getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SortField>
      PARSER = new com.google.protobuf.AbstractParser<SortField>() {
    @java.lang.Override
    public SortField parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SortField(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SortField> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SortField> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.substrait.proto.SortField getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

