// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: expression.proto

package io.substrait;

public final class ExpressionOuterClass {
  private ExpressionOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_substrait_Expression_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_substrait_Expression_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_substrait_Expression_Enum_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_substrait_Expression_Enum_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_substrait_Expression_Enum_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_substrait_Expression_Enum_Empty_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_substrait_Expression_Literal_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_substrait_Expression_Literal_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_substrait_Expression_Literal_Map_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_substrait_Expression_Literal_Map_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_substrait_Expression_Literal_Map_KeyValue_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_substrait_Expression_Literal_Map_KeyValue_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_substrait_Expression_Literal_IntervalYearToMonth_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_substrait_Expression_Literal_IntervalYearToMonth_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_substrait_Expression_Literal_IntervalDayToSecond_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_substrait_Expression_Literal_IntervalDayToSecond_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_substrait_Expression_Literal_Struct_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_substrait_Expression_Literal_Struct_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_substrait_Expression_Literal_List_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_substrait_Expression_Literal_List_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_substrait_Expression_ScalarFunction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_substrait_Expression_ScalarFunction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_substrait_Expression_AggregateFunction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_substrait_Expression_AggregateFunction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_substrait_Expression_WindowFunction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_substrait_Expression_WindowFunction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_substrait_Expression_WindowFunction_Bound_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_substrait_Expression_WindowFunction_Bound_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_substrait_Expression_WindowFunction_Bound_Preceding_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_substrait_Expression_WindowFunction_Bound_Preceding_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_substrait_Expression_WindowFunction_Bound_Following_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_substrait_Expression_WindowFunction_Bound_Following_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_substrait_Expression_WindowFunction_Bound_CurrentRow_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_substrait_Expression_WindowFunction_Bound_CurrentRow_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_substrait_Expression_WindowFunction_Bound_Unbounded_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_substrait_Expression_WindowFunction_Bound_Unbounded_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_substrait_Expression_SortField_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_substrait_Expression_SortField_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_substrait_Expression_IfThen_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_substrait_Expression_IfThen_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_substrait_Expression_IfThen_IfClause_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_substrait_Expression_IfThen_IfClause_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_substrait_Expression_SwitchExpression_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_substrait_Expression_SwitchExpression_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_substrait_Expression_SwitchExpression_IfValue_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_substrait_Expression_SwitchExpression_IfValue_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_substrait_Expression_SingularOrList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_substrait_Expression_SingularOrList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_substrait_Expression_MultiOrList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_substrait_Expression_MultiOrList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_substrait_Expression_MultiOrList_Record_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_substrait_Expression_MultiOrList_Record_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_substrait_Expression_EmbeddedFunction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_substrait_Expression_EmbeddedFunction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_substrait_Expression_EmbeddedFunction_PythonPickleFunction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_substrait_Expression_EmbeddedFunction_PythonPickleFunction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_substrait_Expression_EmbeddedFunction_WebAssemblyFunction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_substrait_Expression_EmbeddedFunction_WebAssemblyFunction_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020expression.proto\022\014io.substrait\032\ntype.p" +
      "roto\032\017selection.proto\032\020extensions.proto\"" +
      "\301$\n\nExpression\0223\n\007literal\030\001 \001(\0132 .io.sub" +
      "strait.Expression.LiteralH\000\0221\n\tselection" +
      "\030\002 \001(\0132\034.io.substrait.FieldReferenceH\000\022B" +
      "\n\017scalar_function\030\003 \001(\0132\'.io.substrait.E" +
      "xpression.ScalarFunctionH\000\022B\n\017window_fun" +
      "ction\030\005 \001(\0132\'.io.substrait.Expression.Wi" +
      "ndowFunctionH\000\0222\n\007if_then\030\006 \001(\0132\037.io.sub" +
      "strait.Expression.IfThenH\000\022F\n\021switch_exp" +
      "ression\030\007 \001(\0132).io.substrait.Expression." +
      "SwitchExpressionH\000\022C\n\020singular_or_list\030\010" +
      " \001(\0132\'.io.substrait.Expression.SingularO" +
      "rListH\000\022=\n\rmulti_or_list\030\t \001(\0132$.io.subs" +
      "trait.Expression.MultiOrListH\000\022-\n\004enum\030\n" +
      " \001(\0132\035.io.substrait.Expression.EnumH\000\032m\n" +
      "\004Enum\022\023\n\tspecified\030\001 \001(\tH\000\022:\n\013unspecifie" +
      "d\030\002 \001(\0132#.io.substrait.Expression.Enum.E" +
      "mptyH\000\032\007\n\005EmptyB\013\n\tenum_kind\032\361\010\n\007Literal" +
      "\022\021\n\007boolean\030\001 \001(\010H\000\022\014\n\002i8\030\002 \001(\005H\000\022\r\n\003i16" +
      "\030\003 \001(\005H\000\022\r\n\003i32\030\005 \001(\005H\000\022\r\n\003i64\030\007 \001(\003H\000\022\016" +
      "\n\004fp32\030\n \001(\002H\000\022\016\n\004fp64\030\013 \001(\001H\000\022\020\n\006string" +
      "\030\014 \001(\tH\000\022\020\n\006binary\030\r \001(\014H\000\022\023\n\ttimestamp\030" +
      "\016 \001(\006H\000\022\016\n\004date\030\020 \001(\007H\000\022\016\n\004time\030\021 \001(\004H\000\022" +
      "V\n\026interval_year_to_month\030\023 \001(\01324.io.sub" +
      "strait.Expression.Literal.IntervalYearTo" +
      "MonthH\000\022V\n\026interval_day_to_second\030\024 \001(\0132" +
      "4.io.substrait.Expression.Literal.Interv" +
      "alDayToSecondH\000\022\024\n\nfixed_char\030\025 \001(\tH\000\022\022\n" +
      "\010var_char\030\026 \001(\tH\000\022\026\n\014fixed_binary\030\027 \001(\014H" +
      "\000\022\021\n\007decimal\030\030 \001(\014H\000\0229\n\006struct\030\031 \001(\0132\'.i" +
      "o.substrait.Expression.Literal.StructH\000\022" +
      "3\n\003map\030\032 \001(\0132$.io.substrait.Expression.L" +
      "iteral.MapH\000\022\026\n\014timestamp_tz\030\033 \001(\006H\000\022\016\n\004" +
      "uuid\030\034 \001(\014H\000\022\"\n\004null\030\035 \001(\0132\022.io.substrai" +
      "t.TypeH\000\0225\n\004list\030\036 \001(\0132%.io.substrait.Ex" +
      "pression.Literal.ListH\000\032\264\001\n\003Map\022A\n\nkey_v" +
      "alues\030\001 \003(\0132-.io.substrait.Expression.Li" +
      "teral.Map.KeyValue\032j\n\010KeyValue\022-\n\003key\030\001 " +
      "\001(\0132 .io.substrait.Expression.Literal\022/\n" +
      "\005value\030\002 \001(\0132 .io.substrait.Expression.L" +
      "iteral\0324\n\023IntervalYearToMonth\022\r\n\005years\030\001" +
      " \001(\005\022\016\n\006months\030\002 \001(\005\0324\n\023IntervalDayToSec" +
      "ond\022\014\n\004days\030\001 \001(\005\022\017\n\007seconds\030\002 \001(\005\032:\n\006St" +
      "ruct\0220\n\006fields\030\001 \003(\0132 .io.substrait.Expr" +
      "ession.Literal\0328\n\004List\0220\n\006values\030\001 \003(\0132 " +
      ".io.substrait.Expression.LiteralB\016\n\014lite" +
      "ral_type\032\222\001\n\016ScalarFunction\022/\n\002id\030\001 \001(\0132" +
      "#.io.substrait.Extensions.FunctionId\022&\n\004" +
      "args\030\002 \003(\0132\030.io.substrait.Expression\022\'\n\013" +
      "output_type\030\003 \001(\0132\022.io.substrait.Type\032\202\002" +
      "\n\021AggregateFunction\022/\n\002id\030\001 \001(\0132#.io.sub" +
      "strait.Extensions.FunctionId\022&\n\004args\030\002 \003" +
      "(\0132\030.io.substrait.Expression\0221\n\005sorts\030\003 " +
      "\003(\0132\".io.substrait.Expression.SortField\022" +
      "8\n\005phase\030\004 \001(\0162).io.substrait.Expression" +
      ".AggregationPhase\022\'\n\013output_type\030\005 \001(\0132\022" +
      ".io.substrait.Type\032\327\006\n\016WindowFunction\022/\n" +
      "\002id\030\001 \001(\0132#.io.substrait.Extensions.Func" +
      "tionId\022,\n\npartitions\030\002 \003(\0132\030.io.substrai" +
      "t.Expression\0221\n\005sorts\030\003 \003(\0132\".io.substra" +
      "it.Expression.SortField\022B\n\013upper_bound\030\004" +
      " \001(\0132-.io.substrait.Expression.WindowFun" +
      "ction.Bound\022B\n\013lower_bound\030\005 \001(\0132-.io.su" +
      "bstrait.Expression.WindowFunction.Bound\022" +
      "8\n\005phase\030\006 \001(\0162).io.substrait.Expression" +
      ".AggregationPhase\022\'\n\013output_type\030\007 \001(\0132\022" +
      ".io.substrait.Type\022&\n\004args\030\010 \003(\0132\030.io.su" +
      "bstrait.Expression\032\237\003\n\005Bound\022L\n\tprecedin" +
      "g\030\001 \001(\01327.io.substrait.Expression.Window" +
      "Function.Bound.PrecedingH\000\022L\n\tfollowing\030" +
      "\002 \001(\01327.io.substrait.Expression.WindowFu" +
      "nction.Bound.FollowingH\000\022O\n\013current_row\030" +
      "\003 \001(\01328.io.substrait.Expression.WindowFu" +
      "nction.Bound.CurrentRowH\000\022L\n\tunbounded\030\004" +
      " \001(\01327.io.substrait.Expression.WindowFun" +
      "ction.Bound.UnboundedH\000\032\033\n\tPreceding\022\016\n\006" +
      "offset\030\001 \001(\003\032\033\n\tFollowing\022\016\n\006offset\030\001 \001(" +
      "\003\032\014\n\nCurrentRow\032\013\n\tUnboundedB\006\n\004kind\032\277\002\n" +
      "\tSortField\022&\n\004expr\030\001 \001(\0132\030.io.substrait." +
      "Expression\022=\n\006formal\030\002 \001(\0162+.io.substrai" +
      "t.Expression.SortField.SortTypeH\000\022B\n\023com" +
      "parison_function\030\003 \001(\0132#.io.substrait.Ex" +
      "tensions.FunctionIdH\000\"z\n\010SortType\022\013\n\007UNK" +
      "NOWN\020\000\022\023\n\017ASC_NULLS_FIRST\020\001\022\022\n\016ASC_NULLS" +
      "_LAST\020\002\022\024\n\020DESC_NULLS_FIRST\020\003\022\023\n\017DESC_NU" +
      "LLS_LAST\020\004\022\r\n\tCLUSTERED\020\005B\013\n\tsort_kind\032\301" +
      "\001\n\006IfThen\0225\n\003ifs\030\001 \003(\0132(.io.substrait.Ex" +
      "pression.IfThen.IfClause\022&\n\004else\030\002 \001(\0132\030" +
      ".io.substrait.Expression\032X\n\010IfClause\022$\n\002" +
      "if\030\001 \001(\0132\030.io.substrait.Expression\022&\n\004th" +
      "en\030\002 \001(\0132\030.io.substrait.Expression\032\323\001\n\020S" +
      "witchExpression\022>\n\003ifs\030\001 \003(\01321.io.substr" +
      "ait.Expression.SwitchExpression.IfValue\022" +
      "&\n\004else\030\002 \001(\0132\030.io.substrait.Expression\032" +
      "W\n\007IfValue\022$\n\002if\030\001 \001(\0132\030.io.substrait.Ex" +
      "pression\022&\n\004then\030\002 \001(\0132\030.io.substrait.Ex" +
      "pression\032d\n\016SingularOrList\022\'\n\005value\030\001 \001(" +
      "\0132\030.io.substrait.Expression\022)\n\007options\030\002" +
      " \003(\0132\030.io.substrait.Expression\032\250\001\n\013Multi" +
      "OrList\022\'\n\005value\030\001 \003(\0132\030.io.substrait.Exp" +
      "ression\022<\n\007options\030\002 \003(\0132+.io.substrait." +
      "Expression.MultiOrList.Record\0322\n\006Record\022" +
      "(\n\006fields\030\001 \003(\0132\030.io.substrait.Expressio" +
      "n\032\257\003\n\020EmbeddedFunction\022+\n\targuments\030\001 \003(" +
      "\0132\030.io.substrait.Expression\022\'\n\013output_ty" +
      "pe\030\002 \001(\0132\022.io.substrait.Type\022`\n\026python_p" +
      "ickle_function\030\003 \001(\0132>.io.substrait.Expr" +
      "ession.EmbeddedFunction.PythonPickleFunc" +
      "tionH\000\022^\n\025web_assembly_function\030\004 \001(\0132=." +
      "io.substrait.Expression.EmbeddedFunction" +
      ".WebAssemblyFunctionH\000\032>\n\024PythonPickleFu" +
      "nction\022\020\n\010function\030\001 \001(\014\022\024\n\014prerequisite" +
      "\030\002 \003(\t\032;\n\023WebAssemblyFunction\022\016\n\006script\030" +
      "\001 \001(\014\022\024\n\014prerequisite\030\002 \003(\tB\006\n\004kind\"\221\001\n\020" +
      "AggregationPhase\022\013\n\007UNKNOWN\020\000\022\033\n\027INITIAL" +
      "_TO_INTERMEDIATE\020\001\022 \n\034INTERMEDIATE_TO_IN" +
      "TERMEDIATE\020\002\022\025\n\021INITIAL_TO_RESULT\020\003\022\032\n\026I" +
      "NTERMEDIATE_TO_RESULT\020\004B\n\n\010rex_typeB\027P\001\252" +
      "\002\022Substrait.Protobufb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.substrait.TypeOuterClass.getDescriptor(),
          io.substrait.Selection.getDescriptor(),
          io.substrait.ExtensionsOuterClass.getDescriptor(),
        });
    internal_static_io_substrait_Expression_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_substrait_Expression_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_substrait_Expression_descriptor,
        new java.lang.String[] { "Literal", "Selection", "ScalarFunction", "WindowFunction", "IfThen", "SwitchExpression", "SingularOrList", "MultiOrList", "Enum", "RexType", });
    internal_static_io_substrait_Expression_Enum_descriptor =
      internal_static_io_substrait_Expression_descriptor.getNestedTypes().get(0);
    internal_static_io_substrait_Expression_Enum_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_substrait_Expression_Enum_descriptor,
        new java.lang.String[] { "Specified", "Unspecified", "EnumKind", });
    internal_static_io_substrait_Expression_Enum_Empty_descriptor =
      internal_static_io_substrait_Expression_Enum_descriptor.getNestedTypes().get(0);
    internal_static_io_substrait_Expression_Enum_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_substrait_Expression_Enum_Empty_descriptor,
        new java.lang.String[] { });
    internal_static_io_substrait_Expression_Literal_descriptor =
      internal_static_io_substrait_Expression_descriptor.getNestedTypes().get(1);
    internal_static_io_substrait_Expression_Literal_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_substrait_Expression_Literal_descriptor,
        new java.lang.String[] { "Boolean", "I8", "I16", "I32", "I64", "Fp32", "Fp64", "String", "Binary", "Timestamp", "Date", "Time", "IntervalYearToMonth", "IntervalDayToSecond", "FixedChar", "VarChar", "FixedBinary", "Decimal", "Struct", "Map", "TimestampTz", "Uuid", "Null", "List", "LiteralType", });
    internal_static_io_substrait_Expression_Literal_Map_descriptor =
      internal_static_io_substrait_Expression_Literal_descriptor.getNestedTypes().get(0);
    internal_static_io_substrait_Expression_Literal_Map_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_substrait_Expression_Literal_Map_descriptor,
        new java.lang.String[] { "KeyValues", });
    internal_static_io_substrait_Expression_Literal_Map_KeyValue_descriptor =
      internal_static_io_substrait_Expression_Literal_Map_descriptor.getNestedTypes().get(0);
    internal_static_io_substrait_Expression_Literal_Map_KeyValue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_substrait_Expression_Literal_Map_KeyValue_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_io_substrait_Expression_Literal_IntervalYearToMonth_descriptor =
      internal_static_io_substrait_Expression_Literal_descriptor.getNestedTypes().get(1);
    internal_static_io_substrait_Expression_Literal_IntervalYearToMonth_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_substrait_Expression_Literal_IntervalYearToMonth_descriptor,
        new java.lang.String[] { "Years", "Months", });
    internal_static_io_substrait_Expression_Literal_IntervalDayToSecond_descriptor =
      internal_static_io_substrait_Expression_Literal_descriptor.getNestedTypes().get(2);
    internal_static_io_substrait_Expression_Literal_IntervalDayToSecond_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_substrait_Expression_Literal_IntervalDayToSecond_descriptor,
        new java.lang.String[] { "Days", "Seconds", });
    internal_static_io_substrait_Expression_Literal_Struct_descriptor =
      internal_static_io_substrait_Expression_Literal_descriptor.getNestedTypes().get(3);
    internal_static_io_substrait_Expression_Literal_Struct_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_substrait_Expression_Literal_Struct_descriptor,
        new java.lang.String[] { "Fields", });
    internal_static_io_substrait_Expression_Literal_List_descriptor =
      internal_static_io_substrait_Expression_Literal_descriptor.getNestedTypes().get(4);
    internal_static_io_substrait_Expression_Literal_List_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_substrait_Expression_Literal_List_descriptor,
        new java.lang.String[] { "Values", });
    internal_static_io_substrait_Expression_ScalarFunction_descriptor =
      internal_static_io_substrait_Expression_descriptor.getNestedTypes().get(2);
    internal_static_io_substrait_Expression_ScalarFunction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_substrait_Expression_ScalarFunction_descriptor,
        new java.lang.String[] { "Id", "Args", "OutputType", });
    internal_static_io_substrait_Expression_AggregateFunction_descriptor =
      internal_static_io_substrait_Expression_descriptor.getNestedTypes().get(3);
    internal_static_io_substrait_Expression_AggregateFunction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_substrait_Expression_AggregateFunction_descriptor,
        new java.lang.String[] { "Id", "Args", "Sorts", "Phase", "OutputType", });
    internal_static_io_substrait_Expression_WindowFunction_descriptor =
      internal_static_io_substrait_Expression_descriptor.getNestedTypes().get(4);
    internal_static_io_substrait_Expression_WindowFunction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_substrait_Expression_WindowFunction_descriptor,
        new java.lang.String[] { "Id", "Partitions", "Sorts", "UpperBound", "LowerBound", "Phase", "OutputType", "Args", });
    internal_static_io_substrait_Expression_WindowFunction_Bound_descriptor =
      internal_static_io_substrait_Expression_WindowFunction_descriptor.getNestedTypes().get(0);
    internal_static_io_substrait_Expression_WindowFunction_Bound_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_substrait_Expression_WindowFunction_Bound_descriptor,
        new java.lang.String[] { "Preceding", "Following", "CurrentRow", "Unbounded", "Kind", });
    internal_static_io_substrait_Expression_WindowFunction_Bound_Preceding_descriptor =
      internal_static_io_substrait_Expression_WindowFunction_Bound_descriptor.getNestedTypes().get(0);
    internal_static_io_substrait_Expression_WindowFunction_Bound_Preceding_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_substrait_Expression_WindowFunction_Bound_Preceding_descriptor,
        new java.lang.String[] { "Offset", });
    internal_static_io_substrait_Expression_WindowFunction_Bound_Following_descriptor =
      internal_static_io_substrait_Expression_WindowFunction_Bound_descriptor.getNestedTypes().get(1);
    internal_static_io_substrait_Expression_WindowFunction_Bound_Following_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_substrait_Expression_WindowFunction_Bound_Following_descriptor,
        new java.lang.String[] { "Offset", });
    internal_static_io_substrait_Expression_WindowFunction_Bound_CurrentRow_descriptor =
      internal_static_io_substrait_Expression_WindowFunction_Bound_descriptor.getNestedTypes().get(2);
    internal_static_io_substrait_Expression_WindowFunction_Bound_CurrentRow_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_substrait_Expression_WindowFunction_Bound_CurrentRow_descriptor,
        new java.lang.String[] { });
    internal_static_io_substrait_Expression_WindowFunction_Bound_Unbounded_descriptor =
      internal_static_io_substrait_Expression_WindowFunction_Bound_descriptor.getNestedTypes().get(3);
    internal_static_io_substrait_Expression_WindowFunction_Bound_Unbounded_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_substrait_Expression_WindowFunction_Bound_Unbounded_descriptor,
        new java.lang.String[] { });
    internal_static_io_substrait_Expression_SortField_descriptor =
      internal_static_io_substrait_Expression_descriptor.getNestedTypes().get(5);
    internal_static_io_substrait_Expression_SortField_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_substrait_Expression_SortField_descriptor,
        new java.lang.String[] { "Expr", "Formal", "ComparisonFunction", "SortKind", });
    internal_static_io_substrait_Expression_IfThen_descriptor =
      internal_static_io_substrait_Expression_descriptor.getNestedTypes().get(6);
    internal_static_io_substrait_Expression_IfThen_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_substrait_Expression_IfThen_descriptor,
        new java.lang.String[] { "Ifs", "Else", });
    internal_static_io_substrait_Expression_IfThen_IfClause_descriptor =
      internal_static_io_substrait_Expression_IfThen_descriptor.getNestedTypes().get(0);
    internal_static_io_substrait_Expression_IfThen_IfClause_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_substrait_Expression_IfThen_IfClause_descriptor,
        new java.lang.String[] { "If", "Then", });
    internal_static_io_substrait_Expression_SwitchExpression_descriptor =
      internal_static_io_substrait_Expression_descriptor.getNestedTypes().get(7);
    internal_static_io_substrait_Expression_SwitchExpression_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_substrait_Expression_SwitchExpression_descriptor,
        new java.lang.String[] { "Ifs", "Else", });
    internal_static_io_substrait_Expression_SwitchExpression_IfValue_descriptor =
      internal_static_io_substrait_Expression_SwitchExpression_descriptor.getNestedTypes().get(0);
    internal_static_io_substrait_Expression_SwitchExpression_IfValue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_substrait_Expression_SwitchExpression_IfValue_descriptor,
        new java.lang.String[] { "If", "Then", });
    internal_static_io_substrait_Expression_SingularOrList_descriptor =
      internal_static_io_substrait_Expression_descriptor.getNestedTypes().get(8);
    internal_static_io_substrait_Expression_SingularOrList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_substrait_Expression_SingularOrList_descriptor,
        new java.lang.String[] { "Value", "Options", });
    internal_static_io_substrait_Expression_MultiOrList_descriptor =
      internal_static_io_substrait_Expression_descriptor.getNestedTypes().get(9);
    internal_static_io_substrait_Expression_MultiOrList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_substrait_Expression_MultiOrList_descriptor,
        new java.lang.String[] { "Value", "Options", });
    internal_static_io_substrait_Expression_MultiOrList_Record_descriptor =
      internal_static_io_substrait_Expression_MultiOrList_descriptor.getNestedTypes().get(0);
    internal_static_io_substrait_Expression_MultiOrList_Record_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_substrait_Expression_MultiOrList_Record_descriptor,
        new java.lang.String[] { "Fields", });
    internal_static_io_substrait_Expression_EmbeddedFunction_descriptor =
      internal_static_io_substrait_Expression_descriptor.getNestedTypes().get(10);
    internal_static_io_substrait_Expression_EmbeddedFunction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_substrait_Expression_EmbeddedFunction_descriptor,
        new java.lang.String[] { "Arguments", "OutputType", "PythonPickleFunction", "WebAssemblyFunction", "Kind", });
    internal_static_io_substrait_Expression_EmbeddedFunction_PythonPickleFunction_descriptor =
      internal_static_io_substrait_Expression_EmbeddedFunction_descriptor.getNestedTypes().get(0);
    internal_static_io_substrait_Expression_EmbeddedFunction_PythonPickleFunction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_substrait_Expression_EmbeddedFunction_PythonPickleFunction_descriptor,
        new java.lang.String[] { "Function", "Prerequisite", });
    internal_static_io_substrait_Expression_EmbeddedFunction_WebAssemblyFunction_descriptor =
      internal_static_io_substrait_Expression_EmbeddedFunction_descriptor.getNestedTypes().get(1);
    internal_static_io_substrait_Expression_EmbeddedFunction_WebAssemblyFunction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_substrait_Expression_EmbeddedFunction_WebAssemblyFunction_descriptor,
        new java.lang.String[] { "Script", "Prerequisite", });
    io.substrait.TypeOuterClass.getDescriptor();
    io.substrait.Selection.getDescriptor();
    io.substrait.ExtensionsOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
