// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: extensions.proto

package io.substrait;

public final class ExtensionsOuterClass {
  private ExtensionsOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_substrait_Extensions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_substrait_Extensions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_substrait_Extensions_Extension_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_substrait_Extensions_Extension_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_substrait_Extensions_Extension_TypeExtension_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_substrait_Extensions_Extension_TypeExtension_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_substrait_Extensions_Extension_FunctionExtension_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_substrait_Extensions_Extension_FunctionExtension_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_substrait_Extensions_Mapping_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_substrait_Extensions_Mapping_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_substrait_Extensions_Mapping_TypeMapping_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_substrait_Extensions_Mapping_TypeMapping_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_substrait_Extensions_Mapping_FunctionMapping_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_substrait_Extensions_Mapping_FunctionMapping_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_substrait_Extensions_Mapping_FunctionMapping_Option_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_substrait_Extensions_Mapping_FunctionMapping_Option_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_substrait_Extensions_ExtensionId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_substrait_Extensions_ExtensionId_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_substrait_Extensions_FunctionId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_substrait_Extensions_FunctionId_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_substrait_Extensions_TypeId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_substrait_Extensions_TypeId_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020extensions.proto\022\014io.substrait\"\356\007\n\nExt" +
      "ensions\032\301\002\n\tExtension\022:\n\014extension_id\030\001 " +
      "\001(\0132$.io.substrait.Extensions.ExtensionI" +
      "d\022J\n\016type_extension\030\002 \001(\01320.io.substrait" +
      ".Extensions.Extension.TypeExtensionH\000\022R\n" +
      "\022function_extension\030\003 \001(\01324.io.substrait" +
      ".Extensions.Extension.FunctionExtensionH" +
      "\000\032 \n\rTypeExtension\022\017\n\007git_uri\030\001 \001(\t\032$\n\021F" +
      "unctionExtension\022\017\n\007git_uri\030\001 \001(\tB\020\n\016ext" +
      "ension_type\032\320\004\n\007Mapping\022D\n\014type_mapping\030" +
      "\001 \001(\0132,.io.substrait.Extensions.Mapping." +
      "TypeMappingH\000\022L\n\020function_mapping\030\002 \001(\0132" +
      "0.io.substrait.Extensions.Mapping.Functi" +
      "onMappingH\000\032\211\001\n\013TypeMapping\0220\n\007type_id\030\001" +
      " \001(\0132\037.io.substrait.Extensions.TypeId\022:\n" +
      "\014extension_id\030\002 \001(\0132$.io.substrait.Exten" +
      "sions.ExtensionId\022\014\n\004name\030\003 \001(\t\032\224\002\n\017Func" +
      "tionMapping\0228\n\013function_id\030\001 \001(\0132#.io.su" +
      "bstrait.Extensions.FunctionId\022:\n\014extensi" +
      "on_id\030\002 \001(\0132$.io.substrait.Extensions.Ex" +
      "tensionId\022\014\n\004name\030\003 \001(\t\022\r\n\005index\030\004 \001(\r\022H" +
      "\n\007options\030\005 \003(\01327.io.substrait.Extension" +
      "s.Mapping.FunctionMapping.Option\032$\n\006Opti" +
      "on\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\tB\016\n\014mappin" +
      "g_type\032\031\n\013ExtensionId\022\n\n\002id\030\001 \001(\r\032\030\n\nFun" +
      "ctionId\022\n\n\002id\030\001 \001(\004\032\024\n\006TypeId\022\n\n\002id\030\001 \001(" +
      "\004B\027P\001\252\002\022Substrait.Protobufb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_io_substrait_Extensions_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_substrait_Extensions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_substrait_Extensions_descriptor,
        new java.lang.String[] { });
    internal_static_io_substrait_Extensions_Extension_descriptor =
      internal_static_io_substrait_Extensions_descriptor.getNestedTypes().get(0);
    internal_static_io_substrait_Extensions_Extension_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_substrait_Extensions_Extension_descriptor,
        new java.lang.String[] { "ExtensionId", "TypeExtension", "FunctionExtension", "ExtensionType", });
    internal_static_io_substrait_Extensions_Extension_TypeExtension_descriptor =
      internal_static_io_substrait_Extensions_Extension_descriptor.getNestedTypes().get(0);
    internal_static_io_substrait_Extensions_Extension_TypeExtension_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_substrait_Extensions_Extension_TypeExtension_descriptor,
        new java.lang.String[] { "GitUri", });
    internal_static_io_substrait_Extensions_Extension_FunctionExtension_descriptor =
      internal_static_io_substrait_Extensions_Extension_descriptor.getNestedTypes().get(1);
    internal_static_io_substrait_Extensions_Extension_FunctionExtension_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_substrait_Extensions_Extension_FunctionExtension_descriptor,
        new java.lang.String[] { "GitUri", });
    internal_static_io_substrait_Extensions_Mapping_descriptor =
      internal_static_io_substrait_Extensions_descriptor.getNestedTypes().get(1);
    internal_static_io_substrait_Extensions_Mapping_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_substrait_Extensions_Mapping_descriptor,
        new java.lang.String[] { "TypeMapping", "FunctionMapping", "MappingType", });
    internal_static_io_substrait_Extensions_Mapping_TypeMapping_descriptor =
      internal_static_io_substrait_Extensions_Mapping_descriptor.getNestedTypes().get(0);
    internal_static_io_substrait_Extensions_Mapping_TypeMapping_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_substrait_Extensions_Mapping_TypeMapping_descriptor,
        new java.lang.String[] { "TypeId", "ExtensionId", "Name", });
    internal_static_io_substrait_Extensions_Mapping_FunctionMapping_descriptor =
      internal_static_io_substrait_Extensions_Mapping_descriptor.getNestedTypes().get(1);
    internal_static_io_substrait_Extensions_Mapping_FunctionMapping_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_substrait_Extensions_Mapping_FunctionMapping_descriptor,
        new java.lang.String[] { "FunctionId", "ExtensionId", "Name", "Index", "Options", });
    internal_static_io_substrait_Extensions_Mapping_FunctionMapping_Option_descriptor =
      internal_static_io_substrait_Extensions_Mapping_FunctionMapping_descriptor.getNestedTypes().get(0);
    internal_static_io_substrait_Extensions_Mapping_FunctionMapping_Option_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_substrait_Extensions_Mapping_FunctionMapping_Option_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_io_substrait_Extensions_ExtensionId_descriptor =
      internal_static_io_substrait_Extensions_descriptor.getNestedTypes().get(2);
    internal_static_io_substrait_Extensions_ExtensionId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_substrait_Extensions_ExtensionId_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_io_substrait_Extensions_FunctionId_descriptor =
      internal_static_io_substrait_Extensions_descriptor.getNestedTypes().get(3);
    internal_static_io_substrait_Extensions_FunctionId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_substrait_Extensions_FunctionId_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_io_substrait_Extensions_TypeId_descriptor =
      internal_static_io_substrait_Extensions_descriptor.getNestedTypes().get(4);
    internal_static_io_substrait_Extensions_TypeId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_substrait_Extensions_TypeId_descriptor,
        new java.lang.String[] { "Id", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
