// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: relations.proto

package io.substrait;

public interface FetchRelOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.substrait.FetchRel)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.io.substrait.RelCommon common = 1;</code>
   * @return Whether the common field is set.
   */
  boolean hasCommon();
  /**
   * <code>.io.substrait.RelCommon common = 1;</code>
   * @return The common.
   */
  io.substrait.RelCommon getCommon();
  /**
   * <code>.io.substrait.RelCommon common = 1;</code>
   */
  io.substrait.RelCommonOrBuilder getCommonOrBuilder();

  /**
   * <code>.io.substrait.Rel input = 2;</code>
   * @return Whether the input field is set.
   */
  boolean hasInput();
  /**
   * <code>.io.substrait.Rel input = 2;</code>
   * @return The input.
   */
  io.substrait.Rel getInput();
  /**
   * <code>.io.substrait.Rel input = 2;</code>
   */
  io.substrait.RelOrBuilder getInputOrBuilder();

  /**
   * <code>int64 offset = 3;</code>
   * @return The offset.
   */
  long getOffset();

  /**
   * <code>int64 count = 4;</code>
   * @return The count.
   */
  long getCount();
}
