// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: selection.proto

package io.substrait;

/**
 * Protobuf type {@code io.substrait.FieldReference}
 */
public final class FieldReference extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:io.substrait.FieldReference)
    FieldReferenceOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FieldReference.newBuilder() to construct.
  private FieldReference(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FieldReference() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new FieldReference();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private FieldReference(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            io.substrait.ReferenceSegment.Builder subBuilder = null;
            if (referenceTypeCase_ == 1) {
              subBuilder = ((io.substrait.ReferenceSegment) referenceType_).toBuilder();
            }
            referenceType_ =
                input.readMessage(io.substrait.ReferenceSegment.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((io.substrait.ReferenceSegment) referenceType_);
              referenceType_ = subBuilder.buildPartial();
            }
            referenceTypeCase_ = 1;
            break;
          }
          case 18: {
            io.substrait.MaskExpression.Builder subBuilder = null;
            if (referenceTypeCase_ == 2) {
              subBuilder = ((io.substrait.MaskExpression) referenceType_).toBuilder();
            }
            referenceType_ =
                input.readMessage(io.substrait.MaskExpression.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((io.substrait.MaskExpression) referenceType_);
              referenceType_ = subBuilder.buildPartial();
            }
            referenceTypeCase_ = 2;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.substrait.Selection.internal_static_io_substrait_FieldReference_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.substrait.Selection.internal_static_io_substrait_FieldReference_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.substrait.FieldReference.class, io.substrait.FieldReference.Builder.class);
  }

  private int referenceTypeCase_ = 0;
  private java.lang.Object referenceType_;
  public enum ReferenceTypeCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    DIRECT_REFERENCE(1),
    MASKED_REFERENCE(2),
    REFERENCETYPE_NOT_SET(0);
    private final int value;
    private ReferenceTypeCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ReferenceTypeCase valueOf(int value) {
      return forNumber(value);
    }

    public static ReferenceTypeCase forNumber(int value) {
      switch (value) {
        case 1: return DIRECT_REFERENCE;
        case 2: return MASKED_REFERENCE;
        case 0: return REFERENCETYPE_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public ReferenceTypeCase
  getReferenceTypeCase() {
    return ReferenceTypeCase.forNumber(
        referenceTypeCase_);
  }

  public static final int DIRECT_REFERENCE_FIELD_NUMBER = 1;
  /**
   * <code>.io.substrait.ReferenceSegment direct_reference = 1;</code>
   * @return Whether the directReference field is set.
   */
  @java.lang.Override
  public boolean hasDirectReference() {
    return referenceTypeCase_ == 1;
  }
  /**
   * <code>.io.substrait.ReferenceSegment direct_reference = 1;</code>
   * @return The directReference.
   */
  @java.lang.Override
  public io.substrait.ReferenceSegment getDirectReference() {
    if (referenceTypeCase_ == 1) {
       return (io.substrait.ReferenceSegment) referenceType_;
    }
    return io.substrait.ReferenceSegment.getDefaultInstance();
  }
  /**
   * <code>.io.substrait.ReferenceSegment direct_reference = 1;</code>
   */
  @java.lang.Override
  public io.substrait.ReferenceSegmentOrBuilder getDirectReferenceOrBuilder() {
    if (referenceTypeCase_ == 1) {
       return (io.substrait.ReferenceSegment) referenceType_;
    }
    return io.substrait.ReferenceSegment.getDefaultInstance();
  }

  public static final int MASKED_REFERENCE_FIELD_NUMBER = 2;
  /**
   * <code>.io.substrait.MaskExpression masked_reference = 2;</code>
   * @return Whether the maskedReference field is set.
   */
  @java.lang.Override
  public boolean hasMaskedReference() {
    return referenceTypeCase_ == 2;
  }
  /**
   * <code>.io.substrait.MaskExpression masked_reference = 2;</code>
   * @return The maskedReference.
   */
  @java.lang.Override
  public io.substrait.MaskExpression getMaskedReference() {
    if (referenceTypeCase_ == 2) {
       return (io.substrait.MaskExpression) referenceType_;
    }
    return io.substrait.MaskExpression.getDefaultInstance();
  }
  /**
   * <code>.io.substrait.MaskExpression masked_reference = 2;</code>
   */
  @java.lang.Override
  public io.substrait.MaskExpressionOrBuilder getMaskedReferenceOrBuilder() {
    if (referenceTypeCase_ == 2) {
       return (io.substrait.MaskExpression) referenceType_;
    }
    return io.substrait.MaskExpression.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (referenceTypeCase_ == 1) {
      output.writeMessage(1, (io.substrait.ReferenceSegment) referenceType_);
    }
    if (referenceTypeCase_ == 2) {
      output.writeMessage(2, (io.substrait.MaskExpression) referenceType_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (referenceTypeCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (io.substrait.ReferenceSegment) referenceType_);
    }
    if (referenceTypeCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (io.substrait.MaskExpression) referenceType_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.substrait.FieldReference)) {
      return super.equals(obj);
    }
    io.substrait.FieldReference other = (io.substrait.FieldReference) obj;

    if (!getReferenceTypeCase().equals(other.getReferenceTypeCase())) return false;
    switch (referenceTypeCase_) {
      case 1:
        if (!getDirectReference()
            .equals(other.getDirectReference())) return false;
        break;
      case 2:
        if (!getMaskedReference()
            .equals(other.getMaskedReference())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (referenceTypeCase_) {
      case 1:
        hash = (37 * hash) + DIRECT_REFERENCE_FIELD_NUMBER;
        hash = (53 * hash) + getDirectReference().hashCode();
        break;
      case 2:
        hash = (37 * hash) + MASKED_REFERENCE_FIELD_NUMBER;
        hash = (53 * hash) + getMaskedReference().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.substrait.FieldReference parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.substrait.FieldReference parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.substrait.FieldReference parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.substrait.FieldReference parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.substrait.FieldReference parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.substrait.FieldReference parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.substrait.FieldReference parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.substrait.FieldReference parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.substrait.FieldReference parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.substrait.FieldReference parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.substrait.FieldReference parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.substrait.FieldReference parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.substrait.FieldReference prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code io.substrait.FieldReference}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:io.substrait.FieldReference)
      io.substrait.FieldReferenceOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.substrait.Selection.internal_static_io_substrait_FieldReference_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.substrait.Selection.internal_static_io_substrait_FieldReference_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.substrait.FieldReference.class, io.substrait.FieldReference.Builder.class);
    }

    // Construct using io.substrait.FieldReference.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      referenceTypeCase_ = 0;
      referenceType_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.substrait.Selection.internal_static_io_substrait_FieldReference_descriptor;
    }

    @java.lang.Override
    public io.substrait.FieldReference getDefaultInstanceForType() {
      return io.substrait.FieldReference.getDefaultInstance();
    }

    @java.lang.Override
    public io.substrait.FieldReference build() {
      io.substrait.FieldReference result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.substrait.FieldReference buildPartial() {
      io.substrait.FieldReference result = new io.substrait.FieldReference(this);
      if (referenceTypeCase_ == 1) {
        if (directReferenceBuilder_ == null) {
          result.referenceType_ = referenceType_;
        } else {
          result.referenceType_ = directReferenceBuilder_.build();
        }
      }
      if (referenceTypeCase_ == 2) {
        if (maskedReferenceBuilder_ == null) {
          result.referenceType_ = referenceType_;
        } else {
          result.referenceType_ = maskedReferenceBuilder_.build();
        }
      }
      result.referenceTypeCase_ = referenceTypeCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.substrait.FieldReference) {
        return mergeFrom((io.substrait.FieldReference)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.substrait.FieldReference other) {
      if (other == io.substrait.FieldReference.getDefaultInstance()) return this;
      switch (other.getReferenceTypeCase()) {
        case DIRECT_REFERENCE: {
          mergeDirectReference(other.getDirectReference());
          break;
        }
        case MASKED_REFERENCE: {
          mergeMaskedReference(other.getMaskedReference());
          break;
        }
        case REFERENCETYPE_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.substrait.FieldReference parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.substrait.FieldReference) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int referenceTypeCase_ = 0;
    private java.lang.Object referenceType_;
    public ReferenceTypeCase
        getReferenceTypeCase() {
      return ReferenceTypeCase.forNumber(
          referenceTypeCase_);
    }

    public Builder clearReferenceType() {
      referenceTypeCase_ = 0;
      referenceType_ = null;
      onChanged();
      return this;
    }


    private com.google.protobuf.SingleFieldBuilderV3<
        io.substrait.ReferenceSegment, io.substrait.ReferenceSegment.Builder, io.substrait.ReferenceSegmentOrBuilder> directReferenceBuilder_;
    /**
     * <code>.io.substrait.ReferenceSegment direct_reference = 1;</code>
     * @return Whether the directReference field is set.
     */
    @java.lang.Override
    public boolean hasDirectReference() {
      return referenceTypeCase_ == 1;
    }
    /**
     * <code>.io.substrait.ReferenceSegment direct_reference = 1;</code>
     * @return The directReference.
     */
    @java.lang.Override
    public io.substrait.ReferenceSegment getDirectReference() {
      if (directReferenceBuilder_ == null) {
        if (referenceTypeCase_ == 1) {
          return (io.substrait.ReferenceSegment) referenceType_;
        }
        return io.substrait.ReferenceSegment.getDefaultInstance();
      } else {
        if (referenceTypeCase_ == 1) {
          return directReferenceBuilder_.getMessage();
        }
        return io.substrait.ReferenceSegment.getDefaultInstance();
      }
    }
    /**
     * <code>.io.substrait.ReferenceSegment direct_reference = 1;</code>
     */
    public Builder setDirectReference(io.substrait.ReferenceSegment value) {
      if (directReferenceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        referenceType_ = value;
        onChanged();
      } else {
        directReferenceBuilder_.setMessage(value);
      }
      referenceTypeCase_ = 1;
      return this;
    }
    /**
     * <code>.io.substrait.ReferenceSegment direct_reference = 1;</code>
     */
    public Builder setDirectReference(
        io.substrait.ReferenceSegment.Builder builderForValue) {
      if (directReferenceBuilder_ == null) {
        referenceType_ = builderForValue.build();
        onChanged();
      } else {
        directReferenceBuilder_.setMessage(builderForValue.build());
      }
      referenceTypeCase_ = 1;
      return this;
    }
    /**
     * <code>.io.substrait.ReferenceSegment direct_reference = 1;</code>
     */
    public Builder mergeDirectReference(io.substrait.ReferenceSegment value) {
      if (directReferenceBuilder_ == null) {
        if (referenceTypeCase_ == 1 &&
            referenceType_ != io.substrait.ReferenceSegment.getDefaultInstance()) {
          referenceType_ = io.substrait.ReferenceSegment.newBuilder((io.substrait.ReferenceSegment) referenceType_)
              .mergeFrom(value).buildPartial();
        } else {
          referenceType_ = value;
        }
        onChanged();
      } else {
        if (referenceTypeCase_ == 1) {
          directReferenceBuilder_.mergeFrom(value);
        }
        directReferenceBuilder_.setMessage(value);
      }
      referenceTypeCase_ = 1;
      return this;
    }
    /**
     * <code>.io.substrait.ReferenceSegment direct_reference = 1;</code>
     */
    public Builder clearDirectReference() {
      if (directReferenceBuilder_ == null) {
        if (referenceTypeCase_ == 1) {
          referenceTypeCase_ = 0;
          referenceType_ = null;
          onChanged();
        }
      } else {
        if (referenceTypeCase_ == 1) {
          referenceTypeCase_ = 0;
          referenceType_ = null;
        }
        directReferenceBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.io.substrait.ReferenceSegment direct_reference = 1;</code>
     */
    public io.substrait.ReferenceSegment.Builder getDirectReferenceBuilder() {
      return getDirectReferenceFieldBuilder().getBuilder();
    }
    /**
     * <code>.io.substrait.ReferenceSegment direct_reference = 1;</code>
     */
    @java.lang.Override
    public io.substrait.ReferenceSegmentOrBuilder getDirectReferenceOrBuilder() {
      if ((referenceTypeCase_ == 1) && (directReferenceBuilder_ != null)) {
        return directReferenceBuilder_.getMessageOrBuilder();
      } else {
        if (referenceTypeCase_ == 1) {
          return (io.substrait.ReferenceSegment) referenceType_;
        }
        return io.substrait.ReferenceSegment.getDefaultInstance();
      }
    }
    /**
     * <code>.io.substrait.ReferenceSegment direct_reference = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.substrait.ReferenceSegment, io.substrait.ReferenceSegment.Builder, io.substrait.ReferenceSegmentOrBuilder> 
        getDirectReferenceFieldBuilder() {
      if (directReferenceBuilder_ == null) {
        if (!(referenceTypeCase_ == 1)) {
          referenceType_ = io.substrait.ReferenceSegment.getDefaultInstance();
        }
        directReferenceBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.substrait.ReferenceSegment, io.substrait.ReferenceSegment.Builder, io.substrait.ReferenceSegmentOrBuilder>(
                (io.substrait.ReferenceSegment) referenceType_,
                getParentForChildren(),
                isClean());
        referenceType_ = null;
      }
      referenceTypeCase_ = 1;
      onChanged();;
      return directReferenceBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        io.substrait.MaskExpression, io.substrait.MaskExpression.Builder, io.substrait.MaskExpressionOrBuilder> maskedReferenceBuilder_;
    /**
     * <code>.io.substrait.MaskExpression masked_reference = 2;</code>
     * @return Whether the maskedReference field is set.
     */
    @java.lang.Override
    public boolean hasMaskedReference() {
      return referenceTypeCase_ == 2;
    }
    /**
     * <code>.io.substrait.MaskExpression masked_reference = 2;</code>
     * @return The maskedReference.
     */
    @java.lang.Override
    public io.substrait.MaskExpression getMaskedReference() {
      if (maskedReferenceBuilder_ == null) {
        if (referenceTypeCase_ == 2) {
          return (io.substrait.MaskExpression) referenceType_;
        }
        return io.substrait.MaskExpression.getDefaultInstance();
      } else {
        if (referenceTypeCase_ == 2) {
          return maskedReferenceBuilder_.getMessage();
        }
        return io.substrait.MaskExpression.getDefaultInstance();
      }
    }
    /**
     * <code>.io.substrait.MaskExpression masked_reference = 2;</code>
     */
    public Builder setMaskedReference(io.substrait.MaskExpression value) {
      if (maskedReferenceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        referenceType_ = value;
        onChanged();
      } else {
        maskedReferenceBuilder_.setMessage(value);
      }
      referenceTypeCase_ = 2;
      return this;
    }
    /**
     * <code>.io.substrait.MaskExpression masked_reference = 2;</code>
     */
    public Builder setMaskedReference(
        io.substrait.MaskExpression.Builder builderForValue) {
      if (maskedReferenceBuilder_ == null) {
        referenceType_ = builderForValue.build();
        onChanged();
      } else {
        maskedReferenceBuilder_.setMessage(builderForValue.build());
      }
      referenceTypeCase_ = 2;
      return this;
    }
    /**
     * <code>.io.substrait.MaskExpression masked_reference = 2;</code>
     */
    public Builder mergeMaskedReference(io.substrait.MaskExpression value) {
      if (maskedReferenceBuilder_ == null) {
        if (referenceTypeCase_ == 2 &&
            referenceType_ != io.substrait.MaskExpression.getDefaultInstance()) {
          referenceType_ = io.substrait.MaskExpression.newBuilder((io.substrait.MaskExpression) referenceType_)
              .mergeFrom(value).buildPartial();
        } else {
          referenceType_ = value;
        }
        onChanged();
      } else {
        if (referenceTypeCase_ == 2) {
          maskedReferenceBuilder_.mergeFrom(value);
        }
        maskedReferenceBuilder_.setMessage(value);
      }
      referenceTypeCase_ = 2;
      return this;
    }
    /**
     * <code>.io.substrait.MaskExpression masked_reference = 2;</code>
     */
    public Builder clearMaskedReference() {
      if (maskedReferenceBuilder_ == null) {
        if (referenceTypeCase_ == 2) {
          referenceTypeCase_ = 0;
          referenceType_ = null;
          onChanged();
        }
      } else {
        if (referenceTypeCase_ == 2) {
          referenceTypeCase_ = 0;
          referenceType_ = null;
        }
        maskedReferenceBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.io.substrait.MaskExpression masked_reference = 2;</code>
     */
    public io.substrait.MaskExpression.Builder getMaskedReferenceBuilder() {
      return getMaskedReferenceFieldBuilder().getBuilder();
    }
    /**
     * <code>.io.substrait.MaskExpression masked_reference = 2;</code>
     */
    @java.lang.Override
    public io.substrait.MaskExpressionOrBuilder getMaskedReferenceOrBuilder() {
      if ((referenceTypeCase_ == 2) && (maskedReferenceBuilder_ != null)) {
        return maskedReferenceBuilder_.getMessageOrBuilder();
      } else {
        if (referenceTypeCase_ == 2) {
          return (io.substrait.MaskExpression) referenceType_;
        }
        return io.substrait.MaskExpression.getDefaultInstance();
      }
    }
    /**
     * <code>.io.substrait.MaskExpression masked_reference = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.substrait.MaskExpression, io.substrait.MaskExpression.Builder, io.substrait.MaskExpressionOrBuilder> 
        getMaskedReferenceFieldBuilder() {
      if (maskedReferenceBuilder_ == null) {
        if (!(referenceTypeCase_ == 2)) {
          referenceType_ = io.substrait.MaskExpression.getDefaultInstance();
        }
        maskedReferenceBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.substrait.MaskExpression, io.substrait.MaskExpression.Builder, io.substrait.MaskExpressionOrBuilder>(
                (io.substrait.MaskExpression) referenceType_,
                getParentForChildren(),
                isClean());
        referenceType_ = null;
      }
      referenceTypeCase_ = 2;
      onChanged();;
      return maskedReferenceBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:io.substrait.FieldReference)
  }

  // @@protoc_insertion_point(class_scope:io.substrait.FieldReference)
  private static final io.substrait.FieldReference DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.substrait.FieldReference();
  }

  public static io.substrait.FieldReference getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FieldReference>
      PARSER = new com.google.protobuf.AbstractParser<FieldReference>() {
    @java.lang.Override
    public FieldReference parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new FieldReference(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FieldReference> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FieldReference> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.substrait.FieldReference getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

