// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: function.proto

package io.substrait;

public final class Function {
  private Function() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_substrait_FunctionSignature_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_substrait_FunctionSignature_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_substrait_FunctionSignature_FinalArgVariadic_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_substrait_FunctionSignature_FinalArgVariadic_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_substrait_FunctionSignature_FinalArgNormal_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_substrait_FunctionSignature_FinalArgNormal_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_substrait_FunctionSignature_Scalar_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_substrait_FunctionSignature_Scalar_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_substrait_FunctionSignature_Aggregate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_substrait_FunctionSignature_Aggregate_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_substrait_FunctionSignature_Window_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_substrait_FunctionSignature_Window_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_substrait_FunctionSignature_Description_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_substrait_FunctionSignature_Description_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_substrait_FunctionSignature_Implementation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_substrait_FunctionSignature_Implementation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_substrait_FunctionSignature_Argument_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_substrait_FunctionSignature_Argument_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_substrait_FunctionSignature_Argument_ValueArgument_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_substrait_FunctionSignature_Argument_ValueArgument_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_substrait_FunctionSignature_Argument_TypeArgument_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_substrait_FunctionSignature_Argument_TypeArgument_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_substrait_FunctionSignature_Argument_EnumArgument_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_substrait_FunctionSignature_Argument_EnumArgument_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016function.proto\022\014io.substrait\032\ntype.pro" +
      "to\032\031parameterized_types.proto\032\026type_expr" +
      "essions.proto\032\020extensions.proto\"\246\026\n\021Func" +
      "tionSignature\032\331\001\n\020FinalArgVariadic\022\020\n\010mi" +
      "n_args\030\001 \001(\003\022\020\n\010max_args\030\002 \001(\003\022Z\n\013consis" +
      "tency\030\003 \001(\0162E.io.substrait.FunctionSigna" +
      "ture.FinalArgVariadic.ParameterConsisten" +
      "cy\"E\n\024ParameterConsistency\022\013\n\007UNKNOWN\020\000\022" +
      "\016\n\nCONSISTENT\020\001\022\020\n\014INCONSISTENT\020\002\032\020\n\016Fin" +
      "alArgNormal\032\235\004\n\006Scalar\022/\n\002id\030\001 \001(\0132#.io." +
      "substrait.Extensions.FunctionId\022;\n\targum" +
      "ents\030\002 \003(\0132(.io.substrait.FunctionSignat" +
      "ure.Argument\022\014\n\004name\030\003 \003(\t\022@\n\013descriptio" +
      "n\030\004 \001(\0132+.io.substrait.FunctionSignature" +
      ".Description\022\025\n\rdeterministic\030\007 \001(\010\022\031\n\021s" +
      "ession_dependent\030\010 \001(\010\0227\n\013output_type\030\t " +
      "\001(\0132\".io.substrait.DerivationExpression\022" +
      "D\n\010variadic\030\n \001(\01320.io.substrait.Functio" +
      "nSignature.FinalArgVariadicH\000\022@\n\006normal\030" +
      "\013 \001(\0132..io.substrait.FunctionSignature.F" +
      "inalArgNormalH\000\022G\n\017implementations\030\014 \003(\013" +
      "2..io.substrait.FunctionSignature.Implem" +
      "entationB\031\n\027final_variable_behavior\032\361\004\n\t" +
      "Aggregate\022/\n\002id\030\001 \001(\0132#.io.substrait.Ext" +
      "ensions.FunctionId\022;\n\targuments\030\002 \003(\0132(." +
      "io.substrait.FunctionSignature.Argument\022" +
      "\014\n\004name\030\003 \003(\t\022@\n\013description\030\004 \001(\0132+.io." +
      "substrait.FunctionSignature.Description\022" +
      "\025\n\rdeterministic\030\007 \001(\010\022\031\n\021session_depend" +
      "ent\030\010 \001(\010\0227\n\013output_type\030\t \001(\0132\".io.subs" +
      "trait.DerivationExpression\022D\n\010variadic\030\n" +
      " \001(\01320.io.substrait.FunctionSignature.Fi" +
      "nalArgVariadicH\000\022@\n\006normal\030\013 \001(\0132..io.su" +
      "bstrait.FunctionSignature.FinalArgNormal" +
      "H\000\022\017\n\007ordered\030\016 \001(\010\022\017\n\007max_set\030\014 \001(\004\022-\n\021" +
      "intermediate_type\030\r \001(\0132\022.io.substrait.T" +
      "ype\022G\n\017implementations\030\017 \003(\0132..io.substr" +
      "ait.FunctionSignature.ImplementationB\031\n\027" +
      "final_variable_behavior\032\377\005\n\006Window\022/\n\002id" +
      "\030\001 \001(\0132#.io.substrait.Extensions.Functio" +
      "nId\022;\n\targuments\030\002 \003(\0132(.io.substrait.Fu" +
      "nctionSignature.Argument\022\014\n\004name\030\003 \003(\t\022@" +
      "\n\013description\030\004 \001(\0132+.io.substrait.Funct" +
      "ionSignature.Description\022\025\n\rdeterministi" +
      "c\030\007 \001(\010\022\031\n\021session_dependent\030\010 \001(\010\022=\n\021in" +
      "termediate_type\030\t \001(\0132\".io.substrait.Der" +
      "ivationExpression\0227\n\013output_type\030\n \001(\0132\"" +
      ".io.substrait.DerivationExpression\022D\n\010va" +
      "riadic\030\020 \001(\01320.io.substrait.FunctionSign" +
      "ature.FinalArgVariadicH\000\022@\n\006normal\030\021 \001(\013" +
      "2..io.substrait.FunctionSignature.FinalA" +
      "rgNormalH\000\022\017\n\007ordered\030\013 \001(\010\022\017\n\007max_set\030\014" +
      " \001(\004\022F\n\013window_type\030\016 \001(\01621.io.substrait" +
      ".FunctionSignature.Window.WindowType\022G\n\017" +
      "implementations\030\017 \003(\0132..io.substrait.Fun" +
      "ctionSignature.Implementation\"7\n\nWindowT" +
      "ype\022\013\n\007UNKNOWN\020\000\022\r\n\tSTREAMING\020\001\022\r\n\tPARTI" +
      "TION\020\002B\031\n\027final_variable_behavior\032-\n\013Des" +
      "cription\022\020\n\010language\030\001 \001(\t\022\014\n\004body\030\002 \001(\t" +
      "\032\226\001\n\016Implementation\022A\n\004type\030\001 \001(\01623.io.s" +
      "ubstrait.FunctionSignature.Implementatio" +
      "n.Type\022\013\n\003uri\030\002 \001(\t\"4\n\004Type\022\013\n\007UNKNOWN\020\000" +
      "\022\020\n\014WEB_ASSEMBLY\020\001\022\r\n\tTRINO_JAR\020\002\032\304\003\n\010Ar" +
      "gument\022\014\n\004name\030\001 \001(\t\022G\n\005value\030\002 \001(\01326.io" +
      ".substrait.FunctionSignature.Argument.Va" +
      "lueArgumentH\000\022E\n\004type\030\003 \001(\01325.io.substra" +
      "it.FunctionSignature.Argument.TypeArgume" +
      "ntH\000\022E\n\004enum\030\004 \001(\01325.io.substrait.Functi" +
      "onSignature.Argument.EnumArgumentH\000\032P\n\rV" +
      "alueArgument\022-\n\004type\030\001 \001(\0132\037.io.substrai" +
      "t.ParameterizedType\022\020\n\010constant\030\002 \001(\010\032=\n" +
      "\014TypeArgument\022-\n\004type\030\001 \001(\0132\037.io.substra" +
      "it.ParameterizedType\0321\n\014EnumArgument\022\017\n\007" +
      "options\030\001 \003(\t\022\020\n\010optional\030\002 \001(\010B\017\n\rargum" +
      "ent_kindB\027P\001\252\002\022Substrait.Protobufb\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.substrait.TypeOuterClass.getDescriptor(),
          io.substrait.ParameterizedTypes.getDescriptor(),
          io.substrait.TypeExpressions.getDescriptor(),
          io.substrait.ExtensionsOuterClass.getDescriptor(),
        });
    internal_static_io_substrait_FunctionSignature_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_substrait_FunctionSignature_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_substrait_FunctionSignature_descriptor,
        new java.lang.String[] { });
    internal_static_io_substrait_FunctionSignature_FinalArgVariadic_descriptor =
      internal_static_io_substrait_FunctionSignature_descriptor.getNestedTypes().get(0);
    internal_static_io_substrait_FunctionSignature_FinalArgVariadic_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_substrait_FunctionSignature_FinalArgVariadic_descriptor,
        new java.lang.String[] { "MinArgs", "MaxArgs", "Consistency", });
    internal_static_io_substrait_FunctionSignature_FinalArgNormal_descriptor =
      internal_static_io_substrait_FunctionSignature_descriptor.getNestedTypes().get(1);
    internal_static_io_substrait_FunctionSignature_FinalArgNormal_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_substrait_FunctionSignature_FinalArgNormal_descriptor,
        new java.lang.String[] { });
    internal_static_io_substrait_FunctionSignature_Scalar_descriptor =
      internal_static_io_substrait_FunctionSignature_descriptor.getNestedTypes().get(2);
    internal_static_io_substrait_FunctionSignature_Scalar_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_substrait_FunctionSignature_Scalar_descriptor,
        new java.lang.String[] { "Id", "Arguments", "Name", "Description", "Deterministic", "SessionDependent", "OutputType", "Variadic", "Normal", "Implementations", "FinalVariableBehavior", });
    internal_static_io_substrait_FunctionSignature_Aggregate_descriptor =
      internal_static_io_substrait_FunctionSignature_descriptor.getNestedTypes().get(3);
    internal_static_io_substrait_FunctionSignature_Aggregate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_substrait_FunctionSignature_Aggregate_descriptor,
        new java.lang.String[] { "Id", "Arguments", "Name", "Description", "Deterministic", "SessionDependent", "OutputType", "Variadic", "Normal", "Ordered", "MaxSet", "IntermediateType", "Implementations", "FinalVariableBehavior", });
    internal_static_io_substrait_FunctionSignature_Window_descriptor =
      internal_static_io_substrait_FunctionSignature_descriptor.getNestedTypes().get(4);
    internal_static_io_substrait_FunctionSignature_Window_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_substrait_FunctionSignature_Window_descriptor,
        new java.lang.String[] { "Id", "Arguments", "Name", "Description", "Deterministic", "SessionDependent", "IntermediateType", "OutputType", "Variadic", "Normal", "Ordered", "MaxSet", "WindowType", "Implementations", "FinalVariableBehavior", });
    internal_static_io_substrait_FunctionSignature_Description_descriptor =
      internal_static_io_substrait_FunctionSignature_descriptor.getNestedTypes().get(5);
    internal_static_io_substrait_FunctionSignature_Description_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_substrait_FunctionSignature_Description_descriptor,
        new java.lang.String[] { "Language", "Body", });
    internal_static_io_substrait_FunctionSignature_Implementation_descriptor =
      internal_static_io_substrait_FunctionSignature_descriptor.getNestedTypes().get(6);
    internal_static_io_substrait_FunctionSignature_Implementation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_substrait_FunctionSignature_Implementation_descriptor,
        new java.lang.String[] { "Type", "Uri", });
    internal_static_io_substrait_FunctionSignature_Argument_descriptor =
      internal_static_io_substrait_FunctionSignature_descriptor.getNestedTypes().get(7);
    internal_static_io_substrait_FunctionSignature_Argument_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_substrait_FunctionSignature_Argument_descriptor,
        new java.lang.String[] { "Name", "Value", "Type", "Enum", "ArgumentKind", });
    internal_static_io_substrait_FunctionSignature_Argument_ValueArgument_descriptor =
      internal_static_io_substrait_FunctionSignature_Argument_descriptor.getNestedTypes().get(0);
    internal_static_io_substrait_FunctionSignature_Argument_ValueArgument_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_substrait_FunctionSignature_Argument_ValueArgument_descriptor,
        new java.lang.String[] { "Type", "Constant", });
    internal_static_io_substrait_FunctionSignature_Argument_TypeArgument_descriptor =
      internal_static_io_substrait_FunctionSignature_Argument_descriptor.getNestedTypes().get(1);
    internal_static_io_substrait_FunctionSignature_Argument_TypeArgument_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_substrait_FunctionSignature_Argument_TypeArgument_descriptor,
        new java.lang.String[] { "Type", });
    internal_static_io_substrait_FunctionSignature_Argument_EnumArgument_descriptor =
      internal_static_io_substrait_FunctionSignature_Argument_descriptor.getNestedTypes().get(2);
    internal_static_io_substrait_FunctionSignature_Argument_EnumArgument_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_substrait_FunctionSignature_Argument_EnumArgument_descriptor,
        new java.lang.String[] { "Options", "Optional", });
    io.substrait.TypeOuterClass.getDescriptor();
    io.substrait.ParameterizedTypes.getDescriptor();
    io.substrait.TypeExpressions.getDescriptor();
    io.substrait.ExtensionsOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
