// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: selection.proto

package io.substrait;

public interface MaskExpressionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.substrait.MaskExpression)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.io.substrait.MaskExpression.StructSelect select = 1;</code>
   * @return Whether the select field is set.
   */
  boolean hasSelect();
  /**
   * <code>.io.substrait.MaskExpression.StructSelect select = 1;</code>
   * @return The select.
   */
  io.substrait.MaskExpression.StructSelect getSelect();
  /**
   * <code>.io.substrait.MaskExpression.StructSelect select = 1;</code>
   */
  io.substrait.MaskExpression.StructSelectOrBuilder getSelectOrBuilder();

  /**
   * <code>bool maintain_singular_struct = 2;</code>
   * @return The maintainSingularStruct.
   */
  boolean getMaintainSingularStruct();
}
