// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: selection.proto

package io.substrait;

public final class Selection {
  private Selection() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_substrait_ReferenceSegment_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_substrait_ReferenceSegment_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_substrait_ReferenceSegment_MapKey_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_substrait_ReferenceSegment_MapKey_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_substrait_ReferenceSegment_MapKeyExpression_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_substrait_ReferenceSegment_MapKeyExpression_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_substrait_ReferenceSegment_StructField_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_substrait_ReferenceSegment_StructField_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_substrait_ReferenceSegment_ListElement_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_substrait_ReferenceSegment_ListElement_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_substrait_ReferenceSegment_ListRange_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_substrait_ReferenceSegment_ListRange_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_substrait_MaskExpression_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_substrait_MaskExpression_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_substrait_MaskExpression_Select_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_substrait_MaskExpression_Select_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_substrait_MaskExpression_StructSelect_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_substrait_MaskExpression_StructSelect_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_substrait_MaskExpression_StructItem_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_substrait_MaskExpression_StructItem_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_substrait_MaskExpression_ListSelect_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_substrait_MaskExpression_ListSelect_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_substrait_MaskExpression_ListSelect_ListSelectItem_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_substrait_MaskExpression_ListSelect_ListSelectItem_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_substrait_MaskExpression_ListSelect_ListSelectItem_ListElement_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_substrait_MaskExpression_ListSelect_ListSelectItem_ListElement_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_substrait_MaskExpression_ListSelect_ListSelectItem_ListSlice_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_substrait_MaskExpression_ListSelect_ListSelectItem_ListSlice_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_substrait_MaskExpression_MapSelect_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_substrait_MaskExpression_MapSelect_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_substrait_MaskExpression_MapSelect_MapKey_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_substrait_MaskExpression_MapSelect_MapKey_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_substrait_MaskExpression_MapSelect_MapKeyExpression_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_substrait_MaskExpression_MapSelect_MapKeyExpression_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_substrait_FieldReference_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_substrait_FieldReference_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017selection.proto\022\014io.substrait\"\211\006\n\020Refe" +
      "renceSegment\0228\n\007map_key\030\001 \001(\0132%.io.subst" +
      "rait.ReferenceSegment.MapKeyH\000\022E\n\nexpres" +
      "sion\030\002 \001(\0132/.io.substrait.ReferenceSegme" +
      "nt.MapKeyExpressionH\000\022B\n\014struct_field\030\003 " +
      "\001(\0132*.io.substrait.ReferenceSegment.Stru" +
      "ctFieldH\000\022B\n\014list_element\030\004 \001(\0132*.io.sub" +
      "strait.ReferenceSegment.ListElementH\000\022>\n" +
      "\nlist_range\030\005 \001(\0132(.io.substrait.Referen" +
      "ceSegment.ListRangeH\000\032H\n\006MapKey\022\017\n\007map_k" +
      "ey\030\001 \001(\t\022-\n\005child\030\002 \001(\0132\036.io.substrait.R" +
      "eferenceSegment\032]\n\020MapKeyExpression\022\032\n\022m" +
      "ap_key_expression\030\001 \001(\t\022-\n\005child\030\002 \001(\0132\036" +
      ".io.substrait.ReferenceSegment\032K\n\013Struct" +
      "Field\022\r\n\005field\030\001 \001(\005\022-\n\005child\030\002 \001(\0132\036.io" +
      ".substrait.ReferenceSegment\032L\n\013ListEleme" +
      "nt\022\016\n\006offset\030\001 \001(\005\022-\n\005child\030\002 \001(\0132\036.io.s" +
      "ubstrait.ReferenceSegment\032V\n\tListRange\022\r" +
      "\n\005start\030\001 \001(\005\022\013\n\003end\030\002 \001(\005\022-\n\005child\030\003 \001(" +
      "\0132\036.io.substrait.ReferenceSegmentB\020\n\016ref" +
      "erence_type\"\210\t\n\016MaskExpression\0229\n\006select" +
      "\030\001 \001(\0132).io.substrait.MaskExpression.Str" +
      "uctSelect\022 \n\030maintain_singular_struct\030\002 " +
      "\001(\010\032\275\001\n\006Select\022;\n\006struct\030\001 \001(\0132).io.subs" +
      "trait.MaskExpression.StructSelectH\000\0227\n\004l" +
      "ist\030\002 \001(\0132\'.io.substrait.MaskExpression." +
      "ListSelectH\000\0225\n\003map\030\003 \001(\0132&.io.substrait" +
      ".MaskExpression.MapSelectH\000B\006\n\004type\032M\n\014S" +
      "tructSelect\022=\n\014struct_items\030\001 \003(\0132\'.io.s" +
      "ubstrait.MaskExpression.StructItem\032O\n\nSt" +
      "ructItem\022\r\n\005field\030\001 \001(\005\0222\n\005child\030\002 \001(\0132#" +
      ".io.substrait.MaskExpression.Select\032\224\003\n\n" +
      "ListSelect\022I\n\tselection\030\001 \003(\01326.io.subst" +
      "rait.MaskExpression.ListSelect.ListSelec" +
      "tItem\0222\n\005child\030\002 \001(\0132#.io.substrait.Mask" +
      "Expression.Select\032\206\002\n\016ListSelectItem\022R\n\004" +
      "item\030\001 \001(\0132B.io.substrait.MaskExpression" +
      ".ListSelect.ListSelectItem.ListElementH\000" +
      "\022Q\n\005slice\030\002 \001(\0132@.io.substrait.MaskExpre" +
      "ssion.ListSelect.ListSelectItem.ListSlic" +
      "eH\000\032\034\n\013ListElement\022\r\n\005field\030\001 \001(\005\032\'\n\tLis" +
      "tSlice\022\r\n\005start\030\001 \001(\005\022\013\n\003end\030\002 \001(\005B\006\n\004ty" +
      "pe\032\241\002\n\tMapSelect\022<\n\003key\030\001 \001(\0132-.io.subst" +
      "rait.MaskExpression.MapSelect.MapKeyH\000\022M" +
      "\n\nexpression\030\002 \001(\01327.io.substrait.MaskEx" +
      "pression.MapSelect.MapKeyExpressionH\000\0222\n" +
      "\005child\030\003 \001(\0132#.io.substrait.MaskExpressi" +
      "on.Select\032\031\n\006MapKey\022\017\n\007map_key\030\001 \001(\t\032.\n\020" +
      "MapKeyExpression\022\032\n\022map_key_expression\030\001" +
      " \001(\tB\010\n\006select\"\230\001\n\016FieldReference\022:\n\020dir" +
      "ect_reference\030\001 \001(\0132\036.io.substrait.Refer" +
      "enceSegmentH\000\0228\n\020masked_reference\030\002 \001(\0132" +
      "\034.io.substrait.MaskExpressionH\000B\020\n\016refer" +
      "ence_typeB\027P\001\252\002\022Substrait.Protobufb\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_io_substrait_ReferenceSegment_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_substrait_ReferenceSegment_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_substrait_ReferenceSegment_descriptor,
        new java.lang.String[] { "MapKey", "Expression", "StructField", "ListElement", "ListRange", "ReferenceType", });
    internal_static_io_substrait_ReferenceSegment_MapKey_descriptor =
      internal_static_io_substrait_ReferenceSegment_descriptor.getNestedTypes().get(0);
    internal_static_io_substrait_ReferenceSegment_MapKey_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_substrait_ReferenceSegment_MapKey_descriptor,
        new java.lang.String[] { "MapKey", "Child", });
    internal_static_io_substrait_ReferenceSegment_MapKeyExpression_descriptor =
      internal_static_io_substrait_ReferenceSegment_descriptor.getNestedTypes().get(1);
    internal_static_io_substrait_ReferenceSegment_MapKeyExpression_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_substrait_ReferenceSegment_MapKeyExpression_descriptor,
        new java.lang.String[] { "MapKeyExpression", "Child", });
    internal_static_io_substrait_ReferenceSegment_StructField_descriptor =
      internal_static_io_substrait_ReferenceSegment_descriptor.getNestedTypes().get(2);
    internal_static_io_substrait_ReferenceSegment_StructField_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_substrait_ReferenceSegment_StructField_descriptor,
        new java.lang.String[] { "Field", "Child", });
    internal_static_io_substrait_ReferenceSegment_ListElement_descriptor =
      internal_static_io_substrait_ReferenceSegment_descriptor.getNestedTypes().get(3);
    internal_static_io_substrait_ReferenceSegment_ListElement_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_substrait_ReferenceSegment_ListElement_descriptor,
        new java.lang.String[] { "Offset", "Child", });
    internal_static_io_substrait_ReferenceSegment_ListRange_descriptor =
      internal_static_io_substrait_ReferenceSegment_descriptor.getNestedTypes().get(4);
    internal_static_io_substrait_ReferenceSegment_ListRange_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_substrait_ReferenceSegment_ListRange_descriptor,
        new java.lang.String[] { "Start", "End", "Child", });
    internal_static_io_substrait_MaskExpression_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_io_substrait_MaskExpression_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_substrait_MaskExpression_descriptor,
        new java.lang.String[] { "Select", "MaintainSingularStruct", });
    internal_static_io_substrait_MaskExpression_Select_descriptor =
      internal_static_io_substrait_MaskExpression_descriptor.getNestedTypes().get(0);
    internal_static_io_substrait_MaskExpression_Select_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_substrait_MaskExpression_Select_descriptor,
        new java.lang.String[] { "Struct", "List", "Map", "Type", });
    internal_static_io_substrait_MaskExpression_StructSelect_descriptor =
      internal_static_io_substrait_MaskExpression_descriptor.getNestedTypes().get(1);
    internal_static_io_substrait_MaskExpression_StructSelect_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_substrait_MaskExpression_StructSelect_descriptor,
        new java.lang.String[] { "StructItems", });
    internal_static_io_substrait_MaskExpression_StructItem_descriptor =
      internal_static_io_substrait_MaskExpression_descriptor.getNestedTypes().get(2);
    internal_static_io_substrait_MaskExpression_StructItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_substrait_MaskExpression_StructItem_descriptor,
        new java.lang.String[] { "Field", "Child", });
    internal_static_io_substrait_MaskExpression_ListSelect_descriptor =
      internal_static_io_substrait_MaskExpression_descriptor.getNestedTypes().get(3);
    internal_static_io_substrait_MaskExpression_ListSelect_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_substrait_MaskExpression_ListSelect_descriptor,
        new java.lang.String[] { "Selection", "Child", });
    internal_static_io_substrait_MaskExpression_ListSelect_ListSelectItem_descriptor =
      internal_static_io_substrait_MaskExpression_ListSelect_descriptor.getNestedTypes().get(0);
    internal_static_io_substrait_MaskExpression_ListSelect_ListSelectItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_substrait_MaskExpression_ListSelect_ListSelectItem_descriptor,
        new java.lang.String[] { "Item", "Slice", "Type", });
    internal_static_io_substrait_MaskExpression_ListSelect_ListSelectItem_ListElement_descriptor =
      internal_static_io_substrait_MaskExpression_ListSelect_ListSelectItem_descriptor.getNestedTypes().get(0);
    internal_static_io_substrait_MaskExpression_ListSelect_ListSelectItem_ListElement_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_substrait_MaskExpression_ListSelect_ListSelectItem_ListElement_descriptor,
        new java.lang.String[] { "Field", });
    internal_static_io_substrait_MaskExpression_ListSelect_ListSelectItem_ListSlice_descriptor =
      internal_static_io_substrait_MaskExpression_ListSelect_ListSelectItem_descriptor.getNestedTypes().get(1);
    internal_static_io_substrait_MaskExpression_ListSelect_ListSelectItem_ListSlice_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_substrait_MaskExpression_ListSelect_ListSelectItem_ListSlice_descriptor,
        new java.lang.String[] { "Start", "End", });
    internal_static_io_substrait_MaskExpression_MapSelect_descriptor =
      internal_static_io_substrait_MaskExpression_descriptor.getNestedTypes().get(4);
    internal_static_io_substrait_MaskExpression_MapSelect_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_substrait_MaskExpression_MapSelect_descriptor,
        new java.lang.String[] { "Key", "Expression", "Child", "Select", });
    internal_static_io_substrait_MaskExpression_MapSelect_MapKey_descriptor =
      internal_static_io_substrait_MaskExpression_MapSelect_descriptor.getNestedTypes().get(0);
    internal_static_io_substrait_MaskExpression_MapSelect_MapKey_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_substrait_MaskExpression_MapSelect_MapKey_descriptor,
        new java.lang.String[] { "MapKey", });
    internal_static_io_substrait_MaskExpression_MapSelect_MapKeyExpression_descriptor =
      internal_static_io_substrait_MaskExpression_MapSelect_descriptor.getNestedTypes().get(1);
    internal_static_io_substrait_MaskExpression_MapSelect_MapKeyExpression_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_substrait_MaskExpression_MapSelect_MapKeyExpression_descriptor,
        new java.lang.String[] { "MapKeyExpression", });
    internal_static_io_substrait_FieldReference_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_io_substrait_FieldReference_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_substrait_FieldReference_descriptor,
        new java.lang.String[] { "DirectReference", "MaskedReference", "ReferenceType", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
