// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: relations.proto

package io.substrait;

public interface SetRelOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.substrait.SetRel)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.io.substrait.RelCommon common = 1;</code>
   * @return Whether the common field is set.
   */
  boolean hasCommon();
  /**
   * <code>.io.substrait.RelCommon common = 1;</code>
   * @return The common.
   */
  io.substrait.RelCommon getCommon();
  /**
   * <code>.io.substrait.RelCommon common = 1;</code>
   */
  io.substrait.RelCommonOrBuilder getCommonOrBuilder();

  /**
   * <code>repeated .io.substrait.Rel inputs = 2;</code>
   */
  java.util.List<io.substrait.Rel> 
      getInputsList();
  /**
   * <code>repeated .io.substrait.Rel inputs = 2;</code>
   */
  io.substrait.Rel getInputs(int index);
  /**
   * <code>repeated .io.substrait.Rel inputs = 2;</code>
   */
  int getInputsCount();
  /**
   * <code>repeated .io.substrait.Rel inputs = 2;</code>
   */
  java.util.List<? extends io.substrait.RelOrBuilder> 
      getInputsOrBuilderList();
  /**
   * <code>repeated .io.substrait.Rel inputs = 2;</code>
   */
  io.substrait.RelOrBuilder getInputsOrBuilder(
      int index);

  /**
   * <code>.io.substrait.SetRel.SetOp op = 3;</code>
   * @return The enum numeric value on the wire for op.
   */
  int getOpValue();
  /**
   * <code>.io.substrait.SetRel.SetOp op = 3;</code>
   * @return The op.
   */
  io.substrait.SetRel.SetOp getOp();
}
