// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: relations.proto

package io.substrait;

/**
 * Protobuf type {@code io.substrait.SortRel}
 */
public final class SortRel extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:io.substrait.SortRel)
    SortRelOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SortRel.newBuilder() to construct.
  private SortRel(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SortRel() {
    sorts_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SortRel();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SortRel(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            io.substrait.RelCommon.Builder subBuilder = null;
            if (common_ != null) {
              subBuilder = common_.toBuilder();
            }
            common_ = input.readMessage(io.substrait.RelCommon.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(common_);
              common_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            io.substrait.Rel.Builder subBuilder = null;
            if (input_ != null) {
              subBuilder = input_.toBuilder();
            }
            input_ = input.readMessage(io.substrait.Rel.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(input_);
              input_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              sorts_ = new java.util.ArrayList<io.substrait.Expression.SortField>();
              mutable_bitField0_ |= 0x00000001;
            }
            sorts_.add(
                input.readMessage(io.substrait.Expression.SortField.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        sorts_ = java.util.Collections.unmodifiableList(sorts_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.substrait.Relations.internal_static_io_substrait_SortRel_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.substrait.Relations.internal_static_io_substrait_SortRel_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.substrait.SortRel.class, io.substrait.SortRel.Builder.class);
  }

  public static final int COMMON_FIELD_NUMBER = 1;
  private io.substrait.RelCommon common_;
  /**
   * <code>.io.substrait.RelCommon common = 1;</code>
   * @return Whether the common field is set.
   */
  @java.lang.Override
  public boolean hasCommon() {
    return common_ != null;
  }
  /**
   * <code>.io.substrait.RelCommon common = 1;</code>
   * @return The common.
   */
  @java.lang.Override
  public io.substrait.RelCommon getCommon() {
    return common_ == null ? io.substrait.RelCommon.getDefaultInstance() : common_;
  }
  /**
   * <code>.io.substrait.RelCommon common = 1;</code>
   */
  @java.lang.Override
  public io.substrait.RelCommonOrBuilder getCommonOrBuilder() {
    return getCommon();
  }

  public static final int INPUT_FIELD_NUMBER = 2;
  private io.substrait.Rel input_;
  /**
   * <code>.io.substrait.Rel input = 2;</code>
   * @return Whether the input field is set.
   */
  @java.lang.Override
  public boolean hasInput() {
    return input_ != null;
  }
  /**
   * <code>.io.substrait.Rel input = 2;</code>
   * @return The input.
   */
  @java.lang.Override
  public io.substrait.Rel getInput() {
    return input_ == null ? io.substrait.Rel.getDefaultInstance() : input_;
  }
  /**
   * <code>.io.substrait.Rel input = 2;</code>
   */
  @java.lang.Override
  public io.substrait.RelOrBuilder getInputOrBuilder() {
    return getInput();
  }

  public static final int SORTS_FIELD_NUMBER = 3;
  private java.util.List<io.substrait.Expression.SortField> sorts_;
  /**
   * <code>repeated .io.substrait.Expression.SortField sorts = 3;</code>
   */
  @java.lang.Override
  public java.util.List<io.substrait.Expression.SortField> getSortsList() {
    return sorts_;
  }
  /**
   * <code>repeated .io.substrait.Expression.SortField sorts = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends io.substrait.Expression.SortFieldOrBuilder> 
      getSortsOrBuilderList() {
    return sorts_;
  }
  /**
   * <code>repeated .io.substrait.Expression.SortField sorts = 3;</code>
   */
  @java.lang.Override
  public int getSortsCount() {
    return sorts_.size();
  }
  /**
   * <code>repeated .io.substrait.Expression.SortField sorts = 3;</code>
   */
  @java.lang.Override
  public io.substrait.Expression.SortField getSorts(int index) {
    return sorts_.get(index);
  }
  /**
   * <code>repeated .io.substrait.Expression.SortField sorts = 3;</code>
   */
  @java.lang.Override
  public io.substrait.Expression.SortFieldOrBuilder getSortsOrBuilder(
      int index) {
    return sorts_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (common_ != null) {
      output.writeMessage(1, getCommon());
    }
    if (input_ != null) {
      output.writeMessage(2, getInput());
    }
    for (int i = 0; i < sorts_.size(); i++) {
      output.writeMessage(3, sorts_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (common_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getCommon());
    }
    if (input_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getInput());
    }
    for (int i = 0; i < sorts_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, sorts_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.substrait.SortRel)) {
      return super.equals(obj);
    }
    io.substrait.SortRel other = (io.substrait.SortRel) obj;

    if (hasCommon() != other.hasCommon()) return false;
    if (hasCommon()) {
      if (!getCommon()
          .equals(other.getCommon())) return false;
    }
    if (hasInput() != other.hasInput()) return false;
    if (hasInput()) {
      if (!getInput()
          .equals(other.getInput())) return false;
    }
    if (!getSortsList()
        .equals(other.getSortsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasCommon()) {
      hash = (37 * hash) + COMMON_FIELD_NUMBER;
      hash = (53 * hash) + getCommon().hashCode();
    }
    if (hasInput()) {
      hash = (37 * hash) + INPUT_FIELD_NUMBER;
      hash = (53 * hash) + getInput().hashCode();
    }
    if (getSortsCount() > 0) {
      hash = (37 * hash) + SORTS_FIELD_NUMBER;
      hash = (53 * hash) + getSortsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.substrait.SortRel parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.substrait.SortRel parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.substrait.SortRel parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.substrait.SortRel parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.substrait.SortRel parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.substrait.SortRel parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.substrait.SortRel parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.substrait.SortRel parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.substrait.SortRel parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.substrait.SortRel parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.substrait.SortRel parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.substrait.SortRel parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.substrait.SortRel prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code io.substrait.SortRel}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:io.substrait.SortRel)
      io.substrait.SortRelOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.substrait.Relations.internal_static_io_substrait_SortRel_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.substrait.Relations.internal_static_io_substrait_SortRel_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.substrait.SortRel.class, io.substrait.SortRel.Builder.class);
    }

    // Construct using io.substrait.SortRel.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getSortsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (commonBuilder_ == null) {
        common_ = null;
      } else {
        common_ = null;
        commonBuilder_ = null;
      }
      if (inputBuilder_ == null) {
        input_ = null;
      } else {
        input_ = null;
        inputBuilder_ = null;
      }
      if (sortsBuilder_ == null) {
        sorts_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        sortsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.substrait.Relations.internal_static_io_substrait_SortRel_descriptor;
    }

    @java.lang.Override
    public io.substrait.SortRel getDefaultInstanceForType() {
      return io.substrait.SortRel.getDefaultInstance();
    }

    @java.lang.Override
    public io.substrait.SortRel build() {
      io.substrait.SortRel result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.substrait.SortRel buildPartial() {
      io.substrait.SortRel result = new io.substrait.SortRel(this);
      int from_bitField0_ = bitField0_;
      if (commonBuilder_ == null) {
        result.common_ = common_;
      } else {
        result.common_ = commonBuilder_.build();
      }
      if (inputBuilder_ == null) {
        result.input_ = input_;
      } else {
        result.input_ = inputBuilder_.build();
      }
      if (sortsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          sorts_ = java.util.Collections.unmodifiableList(sorts_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.sorts_ = sorts_;
      } else {
        result.sorts_ = sortsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.substrait.SortRel) {
        return mergeFrom((io.substrait.SortRel)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.substrait.SortRel other) {
      if (other == io.substrait.SortRel.getDefaultInstance()) return this;
      if (other.hasCommon()) {
        mergeCommon(other.getCommon());
      }
      if (other.hasInput()) {
        mergeInput(other.getInput());
      }
      if (sortsBuilder_ == null) {
        if (!other.sorts_.isEmpty()) {
          if (sorts_.isEmpty()) {
            sorts_ = other.sorts_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureSortsIsMutable();
            sorts_.addAll(other.sorts_);
          }
          onChanged();
        }
      } else {
        if (!other.sorts_.isEmpty()) {
          if (sortsBuilder_.isEmpty()) {
            sortsBuilder_.dispose();
            sortsBuilder_ = null;
            sorts_ = other.sorts_;
            bitField0_ = (bitField0_ & ~0x00000001);
            sortsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getSortsFieldBuilder() : null;
          } else {
            sortsBuilder_.addAllMessages(other.sorts_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.substrait.SortRel parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.substrait.SortRel) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private io.substrait.RelCommon common_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.substrait.RelCommon, io.substrait.RelCommon.Builder, io.substrait.RelCommonOrBuilder> commonBuilder_;
    /**
     * <code>.io.substrait.RelCommon common = 1;</code>
     * @return Whether the common field is set.
     */
    public boolean hasCommon() {
      return commonBuilder_ != null || common_ != null;
    }
    /**
     * <code>.io.substrait.RelCommon common = 1;</code>
     * @return The common.
     */
    public io.substrait.RelCommon getCommon() {
      if (commonBuilder_ == null) {
        return common_ == null ? io.substrait.RelCommon.getDefaultInstance() : common_;
      } else {
        return commonBuilder_.getMessage();
      }
    }
    /**
     * <code>.io.substrait.RelCommon common = 1;</code>
     */
    public Builder setCommon(io.substrait.RelCommon value) {
      if (commonBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        common_ = value;
        onChanged();
      } else {
        commonBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.io.substrait.RelCommon common = 1;</code>
     */
    public Builder setCommon(
        io.substrait.RelCommon.Builder builderForValue) {
      if (commonBuilder_ == null) {
        common_ = builderForValue.build();
        onChanged();
      } else {
        commonBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.io.substrait.RelCommon common = 1;</code>
     */
    public Builder mergeCommon(io.substrait.RelCommon value) {
      if (commonBuilder_ == null) {
        if (common_ != null) {
          common_ =
            io.substrait.RelCommon.newBuilder(common_).mergeFrom(value).buildPartial();
        } else {
          common_ = value;
        }
        onChanged();
      } else {
        commonBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.io.substrait.RelCommon common = 1;</code>
     */
    public Builder clearCommon() {
      if (commonBuilder_ == null) {
        common_ = null;
        onChanged();
      } else {
        common_ = null;
        commonBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.io.substrait.RelCommon common = 1;</code>
     */
    public io.substrait.RelCommon.Builder getCommonBuilder() {
      
      onChanged();
      return getCommonFieldBuilder().getBuilder();
    }
    /**
     * <code>.io.substrait.RelCommon common = 1;</code>
     */
    public io.substrait.RelCommonOrBuilder getCommonOrBuilder() {
      if (commonBuilder_ != null) {
        return commonBuilder_.getMessageOrBuilder();
      } else {
        return common_ == null ?
            io.substrait.RelCommon.getDefaultInstance() : common_;
      }
    }
    /**
     * <code>.io.substrait.RelCommon common = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.substrait.RelCommon, io.substrait.RelCommon.Builder, io.substrait.RelCommonOrBuilder> 
        getCommonFieldBuilder() {
      if (commonBuilder_ == null) {
        commonBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.substrait.RelCommon, io.substrait.RelCommon.Builder, io.substrait.RelCommonOrBuilder>(
                getCommon(),
                getParentForChildren(),
                isClean());
        common_ = null;
      }
      return commonBuilder_;
    }

    private io.substrait.Rel input_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.substrait.Rel, io.substrait.Rel.Builder, io.substrait.RelOrBuilder> inputBuilder_;
    /**
     * <code>.io.substrait.Rel input = 2;</code>
     * @return Whether the input field is set.
     */
    public boolean hasInput() {
      return inputBuilder_ != null || input_ != null;
    }
    /**
     * <code>.io.substrait.Rel input = 2;</code>
     * @return The input.
     */
    public io.substrait.Rel getInput() {
      if (inputBuilder_ == null) {
        return input_ == null ? io.substrait.Rel.getDefaultInstance() : input_;
      } else {
        return inputBuilder_.getMessage();
      }
    }
    /**
     * <code>.io.substrait.Rel input = 2;</code>
     */
    public Builder setInput(io.substrait.Rel value) {
      if (inputBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        input_ = value;
        onChanged();
      } else {
        inputBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.io.substrait.Rel input = 2;</code>
     */
    public Builder setInput(
        io.substrait.Rel.Builder builderForValue) {
      if (inputBuilder_ == null) {
        input_ = builderForValue.build();
        onChanged();
      } else {
        inputBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.io.substrait.Rel input = 2;</code>
     */
    public Builder mergeInput(io.substrait.Rel value) {
      if (inputBuilder_ == null) {
        if (input_ != null) {
          input_ =
            io.substrait.Rel.newBuilder(input_).mergeFrom(value).buildPartial();
        } else {
          input_ = value;
        }
        onChanged();
      } else {
        inputBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.io.substrait.Rel input = 2;</code>
     */
    public Builder clearInput() {
      if (inputBuilder_ == null) {
        input_ = null;
        onChanged();
      } else {
        input_ = null;
        inputBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.io.substrait.Rel input = 2;</code>
     */
    public io.substrait.Rel.Builder getInputBuilder() {
      
      onChanged();
      return getInputFieldBuilder().getBuilder();
    }
    /**
     * <code>.io.substrait.Rel input = 2;</code>
     */
    public io.substrait.RelOrBuilder getInputOrBuilder() {
      if (inputBuilder_ != null) {
        return inputBuilder_.getMessageOrBuilder();
      } else {
        return input_ == null ?
            io.substrait.Rel.getDefaultInstance() : input_;
      }
    }
    /**
     * <code>.io.substrait.Rel input = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.substrait.Rel, io.substrait.Rel.Builder, io.substrait.RelOrBuilder> 
        getInputFieldBuilder() {
      if (inputBuilder_ == null) {
        inputBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.substrait.Rel, io.substrait.Rel.Builder, io.substrait.RelOrBuilder>(
                getInput(),
                getParentForChildren(),
                isClean());
        input_ = null;
      }
      return inputBuilder_;
    }

    private java.util.List<io.substrait.Expression.SortField> sorts_ =
      java.util.Collections.emptyList();
    private void ensureSortsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        sorts_ = new java.util.ArrayList<io.substrait.Expression.SortField>(sorts_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.substrait.Expression.SortField, io.substrait.Expression.SortField.Builder, io.substrait.Expression.SortFieldOrBuilder> sortsBuilder_;

    /**
     * <code>repeated .io.substrait.Expression.SortField sorts = 3;</code>
     */
    public java.util.List<io.substrait.Expression.SortField> getSortsList() {
      if (sortsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(sorts_);
      } else {
        return sortsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .io.substrait.Expression.SortField sorts = 3;</code>
     */
    public int getSortsCount() {
      if (sortsBuilder_ == null) {
        return sorts_.size();
      } else {
        return sortsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .io.substrait.Expression.SortField sorts = 3;</code>
     */
    public io.substrait.Expression.SortField getSorts(int index) {
      if (sortsBuilder_ == null) {
        return sorts_.get(index);
      } else {
        return sortsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .io.substrait.Expression.SortField sorts = 3;</code>
     */
    public Builder setSorts(
        int index, io.substrait.Expression.SortField value) {
      if (sortsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSortsIsMutable();
        sorts_.set(index, value);
        onChanged();
      } else {
        sortsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .io.substrait.Expression.SortField sorts = 3;</code>
     */
    public Builder setSorts(
        int index, io.substrait.Expression.SortField.Builder builderForValue) {
      if (sortsBuilder_ == null) {
        ensureSortsIsMutable();
        sorts_.set(index, builderForValue.build());
        onChanged();
      } else {
        sortsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .io.substrait.Expression.SortField sorts = 3;</code>
     */
    public Builder addSorts(io.substrait.Expression.SortField value) {
      if (sortsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSortsIsMutable();
        sorts_.add(value);
        onChanged();
      } else {
        sortsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .io.substrait.Expression.SortField sorts = 3;</code>
     */
    public Builder addSorts(
        int index, io.substrait.Expression.SortField value) {
      if (sortsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSortsIsMutable();
        sorts_.add(index, value);
        onChanged();
      } else {
        sortsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .io.substrait.Expression.SortField sorts = 3;</code>
     */
    public Builder addSorts(
        io.substrait.Expression.SortField.Builder builderForValue) {
      if (sortsBuilder_ == null) {
        ensureSortsIsMutable();
        sorts_.add(builderForValue.build());
        onChanged();
      } else {
        sortsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .io.substrait.Expression.SortField sorts = 3;</code>
     */
    public Builder addSorts(
        int index, io.substrait.Expression.SortField.Builder builderForValue) {
      if (sortsBuilder_ == null) {
        ensureSortsIsMutable();
        sorts_.add(index, builderForValue.build());
        onChanged();
      } else {
        sortsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .io.substrait.Expression.SortField sorts = 3;</code>
     */
    public Builder addAllSorts(
        java.lang.Iterable<? extends io.substrait.Expression.SortField> values) {
      if (sortsBuilder_ == null) {
        ensureSortsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, sorts_);
        onChanged();
      } else {
        sortsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .io.substrait.Expression.SortField sorts = 3;</code>
     */
    public Builder clearSorts() {
      if (sortsBuilder_ == null) {
        sorts_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        sortsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .io.substrait.Expression.SortField sorts = 3;</code>
     */
    public Builder removeSorts(int index) {
      if (sortsBuilder_ == null) {
        ensureSortsIsMutable();
        sorts_.remove(index);
        onChanged();
      } else {
        sortsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .io.substrait.Expression.SortField sorts = 3;</code>
     */
    public io.substrait.Expression.SortField.Builder getSortsBuilder(
        int index) {
      return getSortsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .io.substrait.Expression.SortField sorts = 3;</code>
     */
    public io.substrait.Expression.SortFieldOrBuilder getSortsOrBuilder(
        int index) {
      if (sortsBuilder_ == null) {
        return sorts_.get(index);  } else {
        return sortsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .io.substrait.Expression.SortField sorts = 3;</code>
     */
    public java.util.List<? extends io.substrait.Expression.SortFieldOrBuilder> 
         getSortsOrBuilderList() {
      if (sortsBuilder_ != null) {
        return sortsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(sorts_);
      }
    }
    /**
     * <code>repeated .io.substrait.Expression.SortField sorts = 3;</code>
     */
    public io.substrait.Expression.SortField.Builder addSortsBuilder() {
      return getSortsFieldBuilder().addBuilder(
          io.substrait.Expression.SortField.getDefaultInstance());
    }
    /**
     * <code>repeated .io.substrait.Expression.SortField sorts = 3;</code>
     */
    public io.substrait.Expression.SortField.Builder addSortsBuilder(
        int index) {
      return getSortsFieldBuilder().addBuilder(
          index, io.substrait.Expression.SortField.getDefaultInstance());
    }
    /**
     * <code>repeated .io.substrait.Expression.SortField sorts = 3;</code>
     */
    public java.util.List<io.substrait.Expression.SortField.Builder> 
         getSortsBuilderList() {
      return getSortsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.substrait.Expression.SortField, io.substrait.Expression.SortField.Builder, io.substrait.Expression.SortFieldOrBuilder> 
        getSortsFieldBuilder() {
      if (sortsBuilder_ == null) {
        sortsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            io.substrait.Expression.SortField, io.substrait.Expression.SortField.Builder, io.substrait.Expression.SortFieldOrBuilder>(
                sorts_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        sorts_ = null;
      }
      return sortsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:io.substrait.SortRel)
  }

  // @@protoc_insertion_point(class_scope:io.substrait.SortRel)
  private static final io.substrait.SortRel DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.substrait.SortRel();
  }

  public static io.substrait.SortRel getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SortRel>
      PARSER = new com.google.protobuf.AbstractParser<SortRel>() {
    @java.lang.Override
    public SortRel parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SortRel(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SortRel> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SortRel> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.substrait.SortRel getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

