// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: type_expressions.proto

package io.substrait;

public final class TypeExpressions {
  private TypeExpressions() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_substrait_DerivationExpression_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_substrait_DerivationExpression_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_substrait_DerivationExpression_ExpressionFixedChar_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_substrait_DerivationExpression_ExpressionFixedChar_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_substrait_DerivationExpression_ExpressionVarChar_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_substrait_DerivationExpression_ExpressionVarChar_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_substrait_DerivationExpression_ExpressionFixedBinary_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_substrait_DerivationExpression_ExpressionFixedBinary_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_substrait_DerivationExpression_ExpressionDecimal_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_substrait_DerivationExpression_ExpressionDecimal_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_substrait_DerivationExpression_ExpressionStruct_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_substrait_DerivationExpression_ExpressionStruct_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_substrait_DerivationExpression_ExpressionNamedStruct_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_substrait_DerivationExpression_ExpressionNamedStruct_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_substrait_DerivationExpression_ExpressionList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_substrait_DerivationExpression_ExpressionList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_substrait_DerivationExpression_ExpressionMap_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_substrait_DerivationExpression_ExpressionMap_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_substrait_DerivationExpression_IfElse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_substrait_DerivationExpression_IfElse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_substrait_DerivationExpression_UnaryOp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_substrait_DerivationExpression_UnaryOp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_substrait_DerivationExpression_BinaryOp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_substrait_DerivationExpression_BinaryOp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026type_expressions.proto\022\014io.substrait\032\n" +
      "type.proto\032\020extensions.proto\"\302\035\n\024Derivat" +
      "ionExpression\022*\n\004bool\030\001 \001(\0132\032.io.substra" +
      "it.Type.BooleanH\000\022#\n\002i8\030\002 \001(\0132\025.io.subst" +
      "rait.Type.I8H\000\022%\n\003i16\030\003 \001(\0132\026.io.substra" +
      "it.Type.I16H\000\022%\n\003i32\030\005 \001(\0132\026.io.substrai" +
      "t.Type.I32H\000\022%\n\003i64\030\007 \001(\0132\026.io.substrait" +
      ".Type.I64H\000\022\'\n\004fp32\030\n \001(\0132\027.io.substrait" +
      ".Type.FP32H\000\022\'\n\004fp64\030\013 \001(\0132\027.io.substrai" +
      "t.Type.FP64H\000\022+\n\006string\030\014 \001(\0132\031.io.subst" +
      "rait.Type.StringH\000\022+\n\006binary\030\r \001(\0132\031.io." +
      "substrait.Type.BinaryH\000\0221\n\ttimestamp\030\016 \001" +
      "(\0132\034.io.substrait.Type.TimestampH\000\022\'\n\004da" +
      "te\030\020 \001(\0132\027.io.substrait.Type.DateH\000\022\'\n\004t" +
      "ime\030\021 \001(\0132\027.io.substrait.Type.TimeH\000\0228\n\r" +
      "interval_year\030\023 \001(\0132\037.io.substrait.Type." +
      "IntervalYearH\000\0226\n\014interval_day\030\024 \001(\0132\036.i" +
      "o.substrait.Type.IntervalDayH\000\0226\n\014timest" +
      "amp_tz\030\035 \001(\0132\036.io.substrait.Type.Timesta" +
      "mpTZH\000\022\'\n\004uuid\030  \001(\0132\027.io.substrait.Type" +
      ".UUIDH\000\022L\n\nfixed_char\030\025 \001(\01326.io.substra" +
      "it.DerivationExpression.ExpressionFixedC" +
      "harH\000\022G\n\007varchar\030\026 \001(\01324.io.substrait.De" +
      "rivationExpression.ExpressionVarCharH\000\022P" +
      "\n\014fixed_binary\030\027 \001(\01328.io.substrait.Deri" +
      "vationExpression.ExpressionFixedBinaryH\000" +
      "\022G\n\007decimal\030\030 \001(\01324.io.substrait.Derivat" +
      "ionExpression.ExpressionDecimalH\000\022E\n\006str" +
      "uct\030\031 \001(\01323.io.substrait.DerivationExpre" +
      "ssion.ExpressionStructH\000\022A\n\004list\030\033 \001(\01321" +
      ".io.substrait.DerivationExpression.Expre" +
      "ssionListH\000\022?\n\003map\030\034 \001(\01320.io.substrait." +
      "DerivationExpression.ExpressionMapH\000\0227\n\014" +
      "user_defined\030\037 \001(\0132\037.io.substrait.Extens" +
      "ions.TypeIdH\000\022\035\n\023type_parameter_name\030! \001" +
      "(\tH\000\022 \n\026integer_parameter_name\030\" \001(\tH\000\022\031" +
      "\n\017integer_literal\030# \001(\005H\000\022>\n\010unary_op\030$ " +
      "\001(\0132*.io.substrait.DerivationExpression." +
      "UnaryOpH\000\022@\n\tbinary_op\030% \001(\0132+.io.substr" +
      "ait.DerivationExpression.BinaryOpH\000\022<\n\007i" +
      "f_else\030& \001(\0132).io.substrait.DerivationEx" +
      "pression.IfElseH\000\032\257\001\n\023ExpressionFixedCha" +
      "r\0222\n\006length\030\001 \001(\0132\".io.substrait.Derivat" +
      "ionExpression\022/\n\tvariation\030\002 \001(\0132\034.io.su" +
      "bstrait.Type.Variation\0223\n\013nullability\030\003 " +
      "\001(\0162\036.io.substrait.Type.Nullability\032\255\001\n\021" +
      "ExpressionVarChar\0222\n\006length\030\001 \001(\0132\".io.s" +
      "ubstrait.DerivationExpression\022/\n\tvariati" +
      "on\030\002 \001(\0132\034.io.substrait.Type.Variation\0223" +
      "\n\013nullability\030\003 \001(\0162\036.io.substrait.Type." +
      "Nullability\032\261\001\n\025ExpressionFixedBinary\0222\n" +
      "\006length\030\001 \001(\0132\".io.substrait.DerivationE" +
      "xpression\022/\n\tvariation\030\002 \001(\0132\034.io.substr" +
      "ait.Type.Variation\0223\n\013nullability\030\003 \001(\0162" +
      "\036.io.substrait.Type.Nullability\032\343\001\n\021Expr" +
      "essionDecimal\0221\n\005scale\030\001 \001(\0132\".io.substr" +
      "ait.DerivationExpression\0225\n\tprecision\030\002 " +
      "\001(\0132\".io.substrait.DerivationExpression\022" +
      "/\n\tvariation\030\003 \001(\0132\034.io.substrait.Type.V" +
      "ariation\0223\n\013nullability\030\004 \001(\0162\036.io.subst" +
      "rait.Type.Nullability\032\253\001\n\020ExpressionStru" +
      "ct\0221\n\005types\030\001 \003(\0132\".io.substrait.Derivat" +
      "ionExpression\022/\n\tvariation\030\002 \001(\0132\034.io.su" +
      "bstrait.Type.Variation\0223\n\013nullability\030\003 " +
      "\001(\0162\036.io.substrait.Type.Nullability\032k\n\025E" +
      "xpressionNamedStruct\022\r\n\005names\030\001 \003(\t\022C\n\006s" +
      "truct\030\002 \001(\01323.io.substrait.DerivationExp" +
      "ression.ExpressionStruct\032\250\001\n\016ExpressionL" +
      "ist\0220\n\004type\030\001 \001(\0132\".io.substrait.Derivat" +
      "ionExpression\022/\n\tvariation\030\002 \001(\0132\034.io.su" +
      "bstrait.Type.Variation\0223\n\013nullability\030\003 " +
      "\001(\0162\036.io.substrait.Type.Nullability\032\331\001\n\r" +
      "ExpressionMap\022/\n\003key\030\001 \001(\0132\".io.substrai" +
      "t.DerivationExpression\0221\n\005value\030\002 \001(\0132\"." +
      "io.substrait.DerivationExpression\022/\n\tvar" +
      "iation\030\003 \001(\0132\034.io.substrait.Type.Variati" +
      "on\0223\n\013nullability\030\004 \001(\0162\036.io.substrait.T" +
      "ype.Nullability\032\262\001\n\006IfElse\0228\n\014if_conditi" +
      "on\030\001 \001(\0132\".io.substrait.DerivationExpres" +
      "sion\0225\n\tif_return\030\002 \001(\0132\".io.substrait.D" +
      "erivationExpression\0227\n\013else_return\030\003 \001(\013" +
      "2\".io.substrait.DerivationExpression\032\246\001\n" +
      "\007UnaryOp\022B\n\007op_type\030\001 \001(\01621.io.substrait" +
      ".DerivationExpression.UnaryOp.OpType\022/\n\003" +
      "arg\030\002 \001(\0132\".io.substrait.DerivationExpre" +
      "ssion\"&\n\006OpType\022\013\n\007UNKNOWN\020\000\022\017\n\013BOOLEAN_" +
      "NOT\020\001\032\211\003\n\010BinaryOp\022C\n\007op_type\030\001 \001(\01622.io" +
      ".substrait.DerivationExpression.BinaryOp" +
      ".OpType\0220\n\004arg1\030\002 \001(\0132\".io.substrait.Der" +
      "ivationExpression\0220\n\004arg2\030\003 \001(\0132\".io.sub" +
      "strait.DerivationExpression\"\323\001\n\006OpType\022\013" +
      "\n\007UNKNOWN\020\000\022\010\n\004PLUS\020\001\022\t\n\005MINUS\020\002\022\014\n\010MULT" +
      "IPLY\020\003\022\n\n\006DIVIDE\020\004\022\007\n\003MIN\020\005\022\007\n\003MAX\020\006\022\020\n\014" +
      "GREATER_THAN\020\007\022\r\n\tLESS_THAN\020\010\022\007\n\003AND\020\t\022\006" +
      "\n\002OR\020\n\022\n\n\006EQUALS\020\013\022\n\n\006COVERS\020\014\022\031\n\025GREATE" +
      "R_THAN_OR_EQUAL\020\r\022\026\n\022LESS_THAN_OR_EQUAL\020" +
      "\016B\006\n\004kindB\027P\001\252\002\022Substrait.Protobufb\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.substrait.TypeOuterClass.getDescriptor(),
          io.substrait.ExtensionsOuterClass.getDescriptor(),
        });
    internal_static_io_substrait_DerivationExpression_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_substrait_DerivationExpression_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_substrait_DerivationExpression_descriptor,
        new java.lang.String[] { "Bool", "I8", "I16", "I32", "I64", "Fp32", "Fp64", "String", "Binary", "Timestamp", "Date", "Time", "IntervalYear", "IntervalDay", "TimestampTz", "Uuid", "FixedChar", "Varchar", "FixedBinary", "Decimal", "Struct", "List", "Map", "UserDefined", "TypeParameterName", "IntegerParameterName", "IntegerLiteral", "UnaryOp", "BinaryOp", "IfElse", "Kind", });
    internal_static_io_substrait_DerivationExpression_ExpressionFixedChar_descriptor =
      internal_static_io_substrait_DerivationExpression_descriptor.getNestedTypes().get(0);
    internal_static_io_substrait_DerivationExpression_ExpressionFixedChar_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_substrait_DerivationExpression_ExpressionFixedChar_descriptor,
        new java.lang.String[] { "Length", "Variation", "Nullability", });
    internal_static_io_substrait_DerivationExpression_ExpressionVarChar_descriptor =
      internal_static_io_substrait_DerivationExpression_descriptor.getNestedTypes().get(1);
    internal_static_io_substrait_DerivationExpression_ExpressionVarChar_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_substrait_DerivationExpression_ExpressionVarChar_descriptor,
        new java.lang.String[] { "Length", "Variation", "Nullability", });
    internal_static_io_substrait_DerivationExpression_ExpressionFixedBinary_descriptor =
      internal_static_io_substrait_DerivationExpression_descriptor.getNestedTypes().get(2);
    internal_static_io_substrait_DerivationExpression_ExpressionFixedBinary_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_substrait_DerivationExpression_ExpressionFixedBinary_descriptor,
        new java.lang.String[] { "Length", "Variation", "Nullability", });
    internal_static_io_substrait_DerivationExpression_ExpressionDecimal_descriptor =
      internal_static_io_substrait_DerivationExpression_descriptor.getNestedTypes().get(3);
    internal_static_io_substrait_DerivationExpression_ExpressionDecimal_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_substrait_DerivationExpression_ExpressionDecimal_descriptor,
        new java.lang.String[] { "Scale", "Precision", "Variation", "Nullability", });
    internal_static_io_substrait_DerivationExpression_ExpressionStruct_descriptor =
      internal_static_io_substrait_DerivationExpression_descriptor.getNestedTypes().get(4);
    internal_static_io_substrait_DerivationExpression_ExpressionStruct_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_substrait_DerivationExpression_ExpressionStruct_descriptor,
        new java.lang.String[] { "Types", "Variation", "Nullability", });
    internal_static_io_substrait_DerivationExpression_ExpressionNamedStruct_descriptor =
      internal_static_io_substrait_DerivationExpression_descriptor.getNestedTypes().get(5);
    internal_static_io_substrait_DerivationExpression_ExpressionNamedStruct_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_substrait_DerivationExpression_ExpressionNamedStruct_descriptor,
        new java.lang.String[] { "Names", "Struct", });
    internal_static_io_substrait_DerivationExpression_ExpressionList_descriptor =
      internal_static_io_substrait_DerivationExpression_descriptor.getNestedTypes().get(6);
    internal_static_io_substrait_DerivationExpression_ExpressionList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_substrait_DerivationExpression_ExpressionList_descriptor,
        new java.lang.String[] { "Type", "Variation", "Nullability", });
    internal_static_io_substrait_DerivationExpression_ExpressionMap_descriptor =
      internal_static_io_substrait_DerivationExpression_descriptor.getNestedTypes().get(7);
    internal_static_io_substrait_DerivationExpression_ExpressionMap_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_substrait_DerivationExpression_ExpressionMap_descriptor,
        new java.lang.String[] { "Key", "Value", "Variation", "Nullability", });
    internal_static_io_substrait_DerivationExpression_IfElse_descriptor =
      internal_static_io_substrait_DerivationExpression_descriptor.getNestedTypes().get(8);
    internal_static_io_substrait_DerivationExpression_IfElse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_substrait_DerivationExpression_IfElse_descriptor,
        new java.lang.String[] { "IfCondition", "IfReturn", "ElseReturn", });
    internal_static_io_substrait_DerivationExpression_UnaryOp_descriptor =
      internal_static_io_substrait_DerivationExpression_descriptor.getNestedTypes().get(9);
    internal_static_io_substrait_DerivationExpression_UnaryOp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_substrait_DerivationExpression_UnaryOp_descriptor,
        new java.lang.String[] { "OpType", "Arg", });
    internal_static_io_substrait_DerivationExpression_BinaryOp_descriptor =
      internal_static_io_substrait_DerivationExpression_descriptor.getNestedTypes().get(10);
    internal_static_io_substrait_DerivationExpression_BinaryOp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_substrait_DerivationExpression_BinaryOp_descriptor,
        new java.lang.String[] { "OpType", "Arg1", "Arg2", });
    io.substrait.TypeOuterClass.getDescriptor();
    io.substrait.ExtensionsOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
